### DISCUSSION TITLE
How do I configure Alicloud OSS for backup

### DISCUSSION THREAD

**Discussion by stevefan1999-personal** [zalando/postgres-operator#1324] [Q&A]
I had issue going on with Alicloud, where I got 403 Forbidden in PutObject. The OSS claimed to be S3 compatible up until this point.
```
+ args+=("--sse=$LOGICAL_BACKUP_S3_SSE")
+ aws s3 cp - s3://0/spilo/acid-test/2ba430c6-d8ed-4bcd-a716-2c1b4980720d/logical_backups/1611244308.sql.gz --expected-size=4969593 --endpoint-url=http://postgres-backup.oss-cn-hongkong.aliyuncs.com --sse=
AES256                                                                                                                                                                                                       upload failed: - to s3://0/spilo/acid-test/2ba430c6-d8ed-4bcd-a716-2c1b4980720d/logical_backups/1611244308.sql.gz An error occurred (403) when calling the PutObject operation: Forbidden
stream closed
```
This is my helm config
```yaml
# configure K8s cron job managed by the operator
configLogicalBackup:
  # image for pods of the logical backup job (example runs pg_dumpall)
  logical_backup_docker_image: "registry.opensource.zalan.do/acid/logical-backup:v1.6.0"
  # path of google cloud service account json file
  # logical_backup_google_application_credentials: ""

  # prefix for the backup job name
  logical_backup_job_prefix: "logical-backup-"
  # storage provider - either "s3" or "gcs"
  logical_backup_provider: "s3"
  # S3 Access Key ID
  logical_backup_s3_access_key_id: "<REDACTED>"
  # S3 bucket to store backup results
  logical_backup_s3_bucket: "postgres-backup"
  # S3 endpoint url when not using AWS
  logical_backup_s3_endpoint: "http://oss-cn-hongkong.aliyuncs.com"
  # S3 region of bucket
  logical_backup_s3_region: ""
  # S3 Secret Access Key
  logical_backup_s3_secret_access_key: "<REDACTED>"
  # S3 server side encryption
  logical_backup_s3_sse: "AES256"
  # backup schedule in the cron format
  logical_backup_schedule: "30 00 * * *"
```
I have created the bucket `postgres-backup` in my OSS console.
I have created a RAM user, then I attached to my newly created bucket with full permission:
![image](https://user-images.githubusercontent.com/29133953/105376981-48465600-5c45-11eb-9d5f-d2c780b6e315.png)
Yet it doesn't seems to be working, more specifically, I have only some backup upload working. I'm auditing the access log but it doesn't seem to have anything yet.
