### DISCUSSION TITLE
Please help, master and slave are out of sync

### DISCUSSION THREAD

**Discussion by WebAdmFcm** [zalando/postgres-operator#1792] [Q&A]
Help, please, master and slave are not synchronized (only 2 nodes).
During the first installation, I imported the database to the master via, subsequently it was synchronized with the slave
I installed the operator initially with this patrony config:
```  patroni:
    initdb:
      data-checksums: "true"
      encoding: UTF8
      locale: en_US.UTF-8
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    retry_timeout: 10
    synchronous_mode: false
```
For a while everything worked.
Then I needed to delete the database and reload it.
Did everything the same way through pskl in the master.
I dropped the database, imported the database to the master, but now it is not synchronized with the slave.
I changed in the config, but it did not give a result synchronous_mode: true.
```
  patroni:
    initdb:
      data-checksums: "true"
      encoding: UTF8
      locale: en_US.UTF-8
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    retry_timeout: 10
    synchronous_mode: true
    synchronous_mode_strict: false
```
Can I somehow manually synchronize master and slave?
```
patronictl list
+ Cluster: iml-postgres (7015981101399175236) --------+----+-----------+
| Member         | Host           | Role    | State   | TL | Lag in MB |
+----------------+----------------+---------+---------+----+-----------+
| iml-postgres-0 | 10.233.121.134 | Replica | running |  6 |     25903 |
| iml-postgres-1 | 10.233.101.55  | Leader  | running | 30 |           |
+----------------+----------------+---------+---------+----+-----------+
```
I'm sorry if I made a mistake, because first time doing this...
