### DISCUSSION TITLE
Better elaborate what Teams & cluster/infrastructure/roles means?

### DISCUSSION THREAD

**Discussion by h0jeZvgoxFepBQ2C** [zalando/postgres-operator#1930] [Q&A]
The documentation often mentions teams - but for me it's not clear what teams mean?
I googled postgres teams, but couldn't find anything related? I guess this is featureset is pure developed by zalando for it's postgres operator?

Also the same applies for the roles (https://postgres-operator.readthedocs.io/en/latest/administrator/#postgres-roles-supported-by-the-operator), I'm missing somehow a really easy way to configure application-connection credentials for a new database?

Is there something like this:

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresqlDatabase
metadata:
  name: acid-minimal-cluster-table123
  namespace: default
spec:
  users:
    user1: "password123"
```

We are a small company and don't have/need any roles/infrastructure roles/etc..
