### DISCUSSION TITLE
WAL-G and scheduled backup

### DISCUSSION THREAD

**Discussion by ErikLundJensen** [zalando/postgres-operator#1971] [Q&A]
I have configured backup to use WAL-G, however, the backups are not scheduled.
For example:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-pod-config
data:
  BACKUP_SCHEDULE: "*/10 * * * * *"
  BACKUP_NUM_TO_RETAIN: "2"
  USE_WALG_BACKUP: "true"
  AWS_ENDPOINT: "foo"
  AWS_ACCESS_KEY_ID: "bar"
  AWS_SECRET_ACCESS_KEY: "some"
  WALG_DISABLE_S3_SSE: "true"
  USE_WALG_RESTORE: "false"
  AWS_S3_FORCE_PATH_STYLE: "true"
  ```

From the source code it looks like the parameter BACKUP_SCHEDULE  is only used by WAL-E:
[configure_spilo.py#L961](https://github.com/zalando/spilo/blob/0009da62c6e22a16d2ee9ac7b03b025d57bf6a26/postgres-appliance/scripts/configure_spilo.py#L961)

Isn't scheduled WAL-G backup supported by Spilo?
