### DISCUSSION TITLE
preparedDatabases schemas to get separate owner

### DISCUSSION THREAD

**Discussion by baznikin** [zalando/postgres-operator#2265] [General]
According to https://github.com/zalando/postgres-operator/blob/80fee5bda47fa98073fe3a175784152fc0ff463f/pkg/cluster/sync.go#L1196 owner for prepared schema should be `databasename_schemaname_owner`. However my schemes owned by `databasename_owner` role.

Cluster config:

```
spec:
  preparedDatabases:
    core:
      defaultUsers: true
      extensions:
        pg_partman: public
      schemas:
        public:
          defaultUsers: true
    kong:
      defaultUsers: true
      schemas:
        public:
          defaultRoles: true
          defaultUsers: true
```

Actual values right after cluster creation:
```
                                            List of schemas
      Name       |       Owner       |           Access privileges            |      Description       
-----------------+-------------------+----------------------------------------+------------------------
 metric_helpers  | postgres          | postgres=UC/postgres                  +| 
                 |                   | admin=U/postgres                      +| 
                 |                   | robot_zmon=U/postgres                  | 
 public          | pg_database_owner | pg_database_owner=UC/pg_database_owner+| standard public schema
                 |                   | =U/pg_database_owner                   | 
 user_management | postgres          | postgres=UC/postgres                  +| 
                 |                   | admin=U/postgres                       | 
(3 rows)

kong=# \c core 
You are now connected to database "core" as user "postgres".
core=# \dn+
                                            List of schemas
      Name       |       Owner       |           Access privileges            |      Description       
-----------------+-------------------+----------------------------------------+------------------------
 metric_helpers  | postgres          | postgres=UC/postgres                  +| 
                 |                   | admin=U/postgres                      +| 
                 |                   | robot_zmon=U/postgres                  | 
 public          | pg_database_owner | pg_database_owner=UC/pg_database_owner+| standard public schema
                 |                   | =U/pg_database_owner                   | 
 user_management | postgres          | postgres=UC/postgres                  +| 
                 |                   | admin=U/postgres                       | 
(3 rows)
```

Is it a bug? How to get postgres-operator to set separate schema owner for each schema?
