### DISCUSSION TITLE
Do you put a database URI in the Secret

### DISCUSSION THREAD

**Discussion by jfmatth** [zalando/postgres-operator#2305] [Q&A]
Hi,

I love your operator, very simple and fast.  

One thing I'd love to see is a URI (i.e. DATABASE_URL) value in the secret that would make it easy for apps to connect to the DB.  Right now, I have to construct it by hand either in code or script.

I moved away from Crunchy's operator, but they do publish a URI in their secret, very very handy.

Thanks,

**Comment by fr34kyn01535** [comment]
I love the idea, maybe some way of defining key name & value based on a template? Would allow for better integrations with helm charts that are not versatile to fetch username & password from secrets..

**Reply by jfmatth** [reply]
As a reference, I use the dj_database_url library in my Django projects.

https://github.com/jazzband/dj-database-url?tab=readme-ov-file

HTH

**Comment by SISheogorath** [comment]
You can construct your URL in the pod spec on your own: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config


Example:

```yaml
env:
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: example.example-postgres.credentials.postgresql.acid.zalan.do
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: example.example-postgres.credentials.postgresql.acid.zalan.do
        key: password
  - name: DB_HOSTNAME
    value: "example-postgres.example.svc"
  - name: DB_DATABASE_NAME
    value: "example"
  - name: PGSSLMODE
    value: prefer
  - name: DB_URL
    value: postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOSTNAME):5432/$(DB_DATABASE_NAME)?sslmode=$(PGSSLMODE)
```
