### DISCUSSION TITLE
Configuration Option to Set Service Type for Connection Pooler

### DISCUSSION THREAD

**Discussion by jonathon2nd** [zalando/postgres-operator#2583] [Ideas]
Hello,

I have a specific use case where I need to deploy the connection pooler without using a LoadBalancer service, primarily due to cost considerations of an additional LoadBalancer in our public cloud environment, when instead we could utilize Traefik for TCP routing and loadbalancing.

Currently, if `enableConnectionPooler` is set to true, the operator deploys the connection pooler service, defaulting to a LoadBalancer type.

Feature Request:
I propose adding a new configuration option within the postgresql resource definition that allows users to specify the desired service type for the connection pooler. Something along the lines of:

```
spec:
  connectionPooler:
    enable: true
    serviceType: ClusterIP  # New field allowing 'ClusterIP', 'NodePort', 'LoadBalancer', etc.
```
This addition would provide greater flexibility for users in different environments and with various networking setups, allowing for more cost-effective and secure deployments.
