### DISCUSSION TITLE
pg operator creates empty disk

### DISCUSSION THREAD

**Discussion by uk1988** [zalando/postgres-operator#2606] [Q&A]
Hej all

First of all, I have to say we are a happy user of the pg operator until recent upgrade it worked perfectly.
 
Ever since we have upgraded postgres-operator from 1.7.1 to 1.9.0 we are experiencing a funny issue. 
Let say for every 10-deployment operator fails to create a database.
By that I mean that pvc where database should be created is empty.

![image](https://github.com/zalando/postgres-operator/assets/66792788/a07fc3c8-1e5e-40d7-9d64-3e22c4dc0a06)

We are using https://github.com/rancher/local-path-provisioner as the default storage class for our pg clusters. 

Example of our reqeust to operator

```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: keycloak-postgresql
spec:
  teamId: keycloak
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 250m
      memory: 500Mi
  volume:
    size: {{ .Values.persistence.size }}
    storageClass: {{ .Values.persistence.storageClass }}
  numberOfInstances: 1
  users:
    keycloak: # database owner
      - login
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  allowedSourceRanges: # load balancers' source ranges for both master and replica services
    - 0.0.0.0/0
  databases:
    keycloak: keycloak # dbname: owner
  postgresql:
    version: "14"
    parameters:
      log_destination: stderr
      logging_collector: "off"
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
```

Logs from the pg pod and operator:
[keycloak-postgresql-0.log](https://github.com/zalando/postgres-operator/files/14960498/keycloak-postgresql-0.log)
[postgres-operator-667568dcc9-vwxt8.log](https://github.com/zalando/postgres-operator/files/14960497/postgres-operator-667568dcc9-vwxt8.log)

When we did upgrade of the operator, we have also finally updated our k8s clusters from 1.23.x to 1.26.x 
We are experiencing similar issue with  postgres-operator 1.10.1.

Any idea what is the issue?
