### DISCUSSION TITLE
How to update pg_hba.conf using Postgres operator for clusters

### DISCUSSION THREAD

**Discussion by bhanotjyoti** [zalando/postgres-operator#2612] [Q&A]
I am trying to look for a way to update the pg_hba.conf to 

```
        pg_hba:
        - local   all             all                                   trust
        - host    all             all                127.0.0.1/32       trust
        - host    all             all                ::1/128            trust
        - local   replication     standby                    trust
        - hostssl replication     standby all                md5
        - hostnossl all           all                all                trust
        - hostssl all             +zalandos    all                pam
        - hostssl all             all                all                md5
```
How can I update the values? There is a reject setting that is causing error in my app code.

I am using this chart 

```
apiVersion: v2
appVersion: 1.10.1
description: Postgres Operator creates and manages PostgreSQL clusters running in
  Kubernetes
home: https://github.com/zalando/postgres-operator
keywords:
- postgres
- operator
- cloud-native
- patroni
- spilo
maintainers:
- email: opensource@zalando.de
  name: Zalando
name: postgres-operator
sources:
- https://github.com/zalando/postgres-operator
version: 1.10.1

```

I was trying to do something like this but failed 

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
        - local   all             all                                   trust
        - host    all             all                127.0.0.1/32       trust
        - host    all             all                ::1/128            trust
        - local   replication     standby                    trust
        - hostssl replication     standby all                md5
        - hostnossl all           all                all                trust
        - hostssl all             +zalandos    all                pam
        - hostssl all             all                all                md5
  {{- with .Values.databases }}
```

Can someone pls help
