### DISCUSSION TITLE
PostgreSQL with TLS Certificate generate by certmanager - SSL error code 214748366

### DISCUSSION THREAD

**Discussion by lenglet-k** [zalando/postgres-operator#2616] [Q&A]
Hi,

I use certmanager for create my postgresql cluster. And on a from sractch install, i have this error:

`FATAL:  could not load server certificate file "/tls/tls.crt": SSL error code 2147483661`.  I don't understand the problem.

This is my config:

```yaml
....
spec:
  databases:
    database_a: abc
  numberOfInstances: 1
  postgresql:
    parameters:
      password_encryption: scram-sha-256
    version: "16"
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  teamId: userA
  tls:
    caSecretName: abc-pgsql-tls
    secretName: abc-pgsql-tls
  users:
    userA: []
    zalando:
    - superuser
    - createdb
  volume:
    size: 1Gi
```

My certificate:

```yaml
spec:
  commonName: abc-postgresql
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: abc-root-ca-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 360h0m0s
  secretName: abc-pgsql-tls
  subject:
    organizations:
    - pgsql
  usages:
  - digital signature
  - key encipherment
 ```
