### DISCUSSION TITLE
Create a user in a different namespace?

### DISCUSSION THREAD

**Discussion by IngwiePhoenix** [zalando/postgres-operator#2670] [Q&A] [answered]
Hello there!

I finished setting up a cluster via the Helm chart and it was pretty easy! With the CRD, I initialized my Postgres cluster and it works well - the `kubectl-pg` plugin can see it too just fine (although it complains about double-definition of `kubeconfig` but thats a different topic).

Now I want to start building deployments that take advantage of the cluster. And, most importantly, I need to add users and databases for them to use.

With the cluster created in the `postgres` namespace, I do see the secrets as expected. But... they are _there_ and I need them _here_ - as in, in the namespace of my app.

Take [shiori](https://github.com/go-shiori/shiori) for instance: It can use Postgres as a storage backend. Right now, I have it set to use sqlite, so I could test it out. But I like it, intend to keep it, and want to reconfigure it to use the cluster instead.

The question is... how?
How do I create a new user/database that would spawn the corresponding secret in the target `shiori` namespace?

Here is the entire postgres cluster configuration:
<details>

<summary>Manifest (YAML)</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-operator
  namespace: kube-system
spec:
  repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  chart: postgres-operator
  targetNamespace: postgres-operator
  valuesContent: |-
    configMajorVersionUpgrade:
      major_version_upgrade_mode: "full"
    configKubernetes:
      additional_pod_capabilities:
        - "SYS_NICE"
      cluster_domain: kube.birb.it
      enable_cross_namespace_secret: true
      enable_finalizers: true
      enable_readiness_probe: true
      # namespaced name of the secret containing infrastructure roles names and passwords
      # infrastructure_roles_secret_name: postgresql-infrastructure-roles
      # toggle if `spilo-role=master` selector should be added to the PDB (Pod Disruption Budget)
      #pdb_master_label_selector: false
      persistent_volume_claim_retention_policy:
        when_deleted: "delete"
        #when_scaled: "retain"
      #configLoadBalancer: {...}
    configDebug:
      debug_logging: false
      enable_database_access: true
    #configTeamsApi: {...}

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-operator-ui
  namespace: kube-system
spec:
  repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
  chart: postgres-operator-ui
  targetNamespace: postgres-operator
  valuesContent: |-
    envs:
      appUrl: "https://postgres.birb.it"
      targetNamespace: "*"
      teams:
        - my-default
    ingress:
      enabled: true
      hosts:
        - host: postgres.birb.it
          paths: ["/"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: default-cluster
  namespace: postgres
spec:
  teamId: my-default
  volume:
    size: 50Gi
    storageClass: nfs-bunker # network-local NFS storage
  numberOfInstances: 1
  users:
    baseline_user:  # database owner
    - superuser
    - createdb
    shiori: []
  databases:
    # TODO: figure out the right way...
    shiori: shiori
  #preparedDatabases:
  #  bar: {}
  postgresql:
    version: "16"
```

</details>

This uses [k3s' Helm controller](https://docs.k3s.io/helm) for the installation.

Meanwhile, there is the `shiori` namespace with a very basic deployment.

The question is: How do I create a user and database on my `default-cluster`, but have the related secrets pop up in the `shiori` namespace?

Thank you and kind regards,
Ingwie
