### DISCUSSION TITLE
Configure fixed IP for cluster service

### DISCUSSION THREAD

**Discussion by Hr46ph** [zalando/postgres-operator#2757] [Q&A]
I deploy a 3-node postgres cluster which works fine and it creates a service with external IP of type LoadBalancer. Perfect. Well, almost. I actually wish to configure my own fixed IP because I have other services that require a fixed IP. I tried setting it via the Postgres operator UI, edit yaml and add this below spec:
```yaml
spec:
  service:
    spec:
      type: LoadBalancer
      loadBalancerIP: 10.0.0.128
```
This addition is removed when validated or submitted. Maybe I got the format wrong?

Is there a way to fix an IP? If I deploy a second cluster I would prefer to be able to set it in the manifest upon deploying. 

Thanks!
