### DISCUSSION TITLE
Issues with syncing custom PostgreSQL Helm chart settings in ArgoCD

### DISCUSSION THREAD

**Discussion by angelosleebos** [zalando/postgres-operator#2834] [Q&A]
# Issues with syncing custom PostgreSQL Helm chart settings in ArgoCD

Hi there,

I’ve created a custom Helm chart to manage PostgreSQL resources for the Zalando Postgres Operator, but I’m running into issues where some settings don’t seem to sync properly in ArgoCD. It’s unclear if the issue is related to the customizations, ArgoCD, or the operator itself.

Here are the key components of my setup. Basically, only the `postgresql.yaml` is relevant to my question, but for completeness, I've included the other components as well in case there are any comments on those.

---

## PostgreSQL resource (`templates/postgresql.yaml`):
```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ .Release.Name }}-db
spec:
  {{- if .Values.connectionPooler }}
  connectionPooler:
    maxDBConnections: {{ .Values.connectionPooler.maxDBConnections }}
    mode: {{ .Values.connectionPooler.mode | default "transaction" }}
  {{- end }}
  databases:
  {{- range .Values.databases }}
    {{ . }}: admin
  {{- end }}
  {{- if .Values.nodeAffinity.lifecycle }}
  nodeAffinity: 
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: lifecycle
              operator: In
              values:
                - {{ .Values.nodeAffinity.lifecycle }}
  {{- end }}
  numberOfInstances: {{ .Values.numberOfInstances | default 2 }}
  postgresql:
    version: {{ .Values.version | quote }}
    {{- if .Values.parameters }}
    parameters: {{- toYaml .Values.parameters | nindent 6 }}
    {{- end }}
  resources: {{- toYaml .Values.resources | nindent 4 }}
  teamId: test
  users:
    admin:
      - superuser
      - createdb
    {{- if .Values.additionalUsers }}
    {{- range .Values.additionalUsers }}
    {{ . }}: []
    {{- end }}
    {{- end }}
  volume: {{- toYaml .Values.volume | nindent 4 }}

  {{- if .Values.walBackup.enabled }}
  enableLogicalBackup: true
  podEnvironmentConfigMap: "{{ .Release.Namespace }}/{{ .Release.Name }}-wal-config"
  serviceAccountName: {{ .Values.walBackup.serviceAccountName }}
  {{- end }}
```

---

## ConfigMap for WAL-G (`templates/wal-backup-configmap.yaml`):
```yaml
{{- if .Values.walBackup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wal-config
  namespace: {{ .Release.Namespace }}
data:
  WALG_S3_PREFIX: "s3://{{ .Values.walBackup.s3Bucket }}"
  AWS_REGION: "{{ .Values.walBackup.awsRegion }}"
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_SCHEDULE: "{{ .Values.walBackup.schedule }}"
  BACKUP_NUM_TO_RETAIN: "{{ .Values.walBackup.retention }}"
{{- end }}
```

---

## ServiceAccount for WAL-G (`templates/wal-backup-serviceaccount.yaml`):
```yaml
{{- if .Values.walBackup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.walBackup.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.walBackup.iamRoleArn }}"
{{- end }}
```

---

## Part of `values.yaml`:
```yaml
walBackup:
  enabled: true
  serviceAccountName: "wal-backup-sa"
  iamRoleArn: "arn:aws:iam::<account-id>:role/<iam-role-name>"
  s3Bucket: "<your-s3-bucket>"
  awsRegion: "eu-west-1"
  schedule: "30 00 * * *"
  retention: 7
```

---

## Observed Behavior
- Some settings (e.g., `podEnvironmentConfigMap`, `serviceAccountName`) don’t seem to apply as expected.

---

## Questions:
1. Are `podEnvironmentConfigMap` and `serviceAccountName` valid fields in the Postgresql CR spec? Are there known limitations for these fields?
2. Are there any operator-specific behaviors or configurations that could prevent these settings from applying correctly in ArgoCD?
