### DISCUSSION TITLE
Infrastructure roles and cluster pods restarts

### DISCUSSION THREAD

**Discussion by mirkomarchiori** [zalando/postgres-operator#2860] [Q&A]
Hi, we are using the ConfigMap and Secret `postgresql-infrastructure-roles` combo to define some postgres roles that will be created for every database we deploy.

Here is an example of such resources:

Secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-infrastructure-roles
  namespace: pg-admin
stringData:
  monitoruser: <PASSWORD>
```

ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-infrastructure-roles
  namespace: pg-admin
data:
  monitoruser: |
    inrole: [pg_read_all_stats]
    user_flags:
      - login
```

Then, those "global" users are allowed on the `pg_hba` configuration inside each cluster, in the `kind: postgresql` resource. 

The operator is deployed through its Helm Chart on a specific namespace and is able to manage postgres clusters on all other namespaces.

Now, my question is: what happens when I add a new infrastructure role on the Secret and ConfigMap?
- Do I need to restart the operator for it to add those users on each downstream cluster namespace?
- Will the pods of all my already deployed databases be restarted?
- Does the `enable_lazy_spilo_upgrade` flag of the operator help in avoiding pods restarts in this case? (I am asking because this is not really a kubernetes change, but more of a postgres configuration I guess)
