### DISCUSSION TITLE
Change log message or log level

### DISCUSSION THREAD

**Discussion by lenglet-k** [zalando/postgres-operator#2874] [Q&A]
Hello,

there is a possibility to change postgresql log ? Because with the default configuration we can't see much, apart from ‘no action; i am the leader’. Maybe log level or other configuration ?

**Comment by Eneeeergii** [comment]
Hi,

it depends on your configuration. Maybe in the configmap or OperatorConfiguration are some parameters to change the log level.

**Comment by uk1988** [comment]
@lenglet-k 
yes it can be done under `postgresql.parameters` section. There you can set all the postgresql settings.

```
postgresql:
    version: "14"
    parameters:
      log_destination: stderr
      logging_collector: "off"
      # set log on pg
      # log_statement: "none" : # options: none(off), ddl(default), mod, all
```

Please see a full example of the object here: 
https://github.com/zalando/postgres-operator/blob/master/manifests/complete-postgres-manifest.yaml
