### ISSUE TITLE
uploading WAL files to s3 compatible api

### ISSUE THREAD

**Issue by redscaresu** [zalando/postgres-operator#1006]
Hi, I am using a cloud provider that provides an S3 compatible api however it does not support virtual host-style access.

for example the below format is not supported.

bucketname.namespace.compat.objectstorage.region.oraclecloud.com

Doing some reading it looks like setting force_path_style option will solve my problems, is there an option to apply that here?

The error I receive is the following 

https://gist.github.com/redscaresu/bcdb3f214af79055b5011a9426ed88d0

Here are my config maps

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: postgres-cluster
data: 
  BACKUP_SCHEDULE: "0 */12 * * *"
  USE_WALG_BACKUP: "true"
  BACKUP_NUM_TO_RETAIN: "5"
  AWS_ACCESS_KEY_ID: xxxx
  AWS_SECRET_ACCESS_KEY: xxxx
  AWS_ENDPOINT: https://boo.compat.objectstorage.us-east-1.oraclecloud.com
  AWS_REGION: us-east-1
  WALG_DISABLE_S3_SSE: "true"
```

```
# Source: postgres-operator/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
  namespace: postgres-operator
....
data:
  docker_image: registry.opensource.zalan.do/acid/spilo-12:1.6-p3
  aws_region: us-east-1
  aws_endpoint: "https://boo.compat.objectstorage.us-east-1.oraclecloud.com"
  wal_s3_bucket: postgres-dev-wal-backup
```
