### ISSUE TITLE
Having trouble with persistent volume claim for minimal example

### ISSUE THREAD

**Issue by B45man** [zalando/postgres-operator#1011]
Hi, I'm following the [quickstart](https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md) for this operator. I have succesfully set up the operator itself, but the minimal-postgres-manifest.yaml is giving me trouble. It seems to run correctly, but the PVC that it creates can not connect to the NFS volume I have set up. See the below screenshot:

![image](https://user-images.githubusercontent.com/6691945/84025438-db1ed280-a98b-11ea-8623-95455044c619.png)

I have first tried to create a persistent volume manually using this simple file: 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-acid-minimal-cluster-0
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 123.456.789.10
    path: /the/correct/path 
```

And I tried setting up a storage class: 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-acid-minimal-cluster-0
  labels:
    name: nfs-persistentvolume 
spec:
  storageClassName: manual 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 123.456.789.10 
    path: "/the/correct/path" 
```

But both ways, I end up with a PVC that doesn't want to connect to my volume. What am I doing wrong?
