### ISSUE TITLE
How to set tolerations for backup job pod?

### ISSUE THREAD

**Issue by StephenLiuYa** [zalando/postgres-operator#1015]
```
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

I want to add more tolerations to the backup job pod, Can this be done by edit configmap?
