### ISSUE TITLE
Service for patronictl rest api

### ISSUE THREAD

**Issue by aditya1808** [zalando/postgres-operator#1024]
Hi,
my current cluster has following services created 
![image](https://user-images.githubusercontent.com/6763803/84862177-4f462e00-b090-11ea-8ec8-aac7bcef0dc4.png)

These images are created  by postgres-operator itself if im not wrong.

Is there a way to create service for rest api as well?
Currently, i can access rest api using pod IP address but are there any stesp to create a service for REST api? like **rdbms-pg-cluster-rest**

**Comment by CyberDem0n** [comment]
Patroni REST API is supposed to be accessed only directly.

**Comment by szelga** [comment]
one could do such a service manually, e.g.:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: DATABASE-patroni
  namespace: NAMESPACE
spec:
  ports:
  - name: http
    port: 8008
    targetPort: 8008
  selector:
    application: spilo
    cluster-name: DATABASE
    spilo-role: master
  type: ClusterIP
```
