### ISSUE TITLE
Operator runs, however it does not create any postgres pods

### ISSUE THREAD

**Issue by mabushey** [zalando/postgres-operator#1078]
```
✗  cat postgres.yaml 
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: cubejs
  namespace: postgres
spec:
  teamId: "devops"
  volume:
    size: 5Gi
  numberOfInstances: 1
  users:
    admin:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    cube: admin  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "12"
```

Kustomize creates the namespace postgres, but `kubectl get all -n postgres` shows `No resources found.` and nothing new appears in the logs for `kubectl -n postgres-operator logs -f postgres-operator-54b4d9ddbf-n49nv`. No errors, no containers, no database.
