### ISSUE TITLE
SecurityContext for Postgres Pods

### ISSUE THREAD

**Issue by BobyMCbobs** [zalando/postgres-operator#1120]
# Issue
Postgres shouldn't need to run as root in most cases and also doesn't need to have a writable filesystem.

What is the likelihood of running the Spilo and Pooler Pods with a Pod SecurityContext something like:
```yaml
podSecurityContext:
  readOnlyRootFilesystem: true
  runAsUser: 101
  runAsGroup: 103
  allowPrivilegeEscalation: false
```

This will minimize on various risks of the Pod's lifecycle
