### ISSUE TITLE
extension uuid-ossp installation in database cluster

### ISSUE THREAD

**Issue by kushwahashiv** [zalando/postgres-operator#1129]
Hi I tried to configure extension `uuid-ossp` in database yml https://github.com/zalando/postgres-operator/blob/master/manifests/minimal-postgres-manifest.yaml but when the cluster was created I don't see the extension installed in postgres default database

Is something missing below here or below one is the right way to configure this extension.

```yml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar:
      defaultUsers: true
      extensions:
        uuid-ossp: public
      schemas:
        data: {}
        history:
          defaultRoles: true
          defaultUsers: false
  postgresql:
    version: "12"

```

/shiv
