### ISSUE TITLE
Schema creation failed with permission error in preparedDatabases

### ISSUE THREAD

**Issue by neelasha-09** [zalando/postgres-operator#1130]
Hi team,

We are trying to create multiple databases using the 'preparedDatabases'.
**There is no issue while creating only 1 database and schema. But the issue occurs when we start adding the second database& schema and more.**

**With the below configuration, the first database & schema passed is created successfully,  but the second and other databases and schema  creates error.**

Below is the configuration of the "cluster values.yaml"

```
spec:
  additionalVolumes:
  - mountPath: /var/run/postgresql
    name: empty
    targetContainers:
    - all
    volumeSource:
      emptyDir: {}
  numberOfInstances: 1
  patroni:
    pg_hba:
    - hostssl a3s      a3s_a3s_owner_user      all md5
    - hostssl all      postgres                all md5
    - host    all      all                     all md5
  postgresql:
    version: "12"
  preparedDatabases:
    a3sdb:
      schemas:
        a3sschema:
          defaultRoles: true
          defaultUsers: true
    a3s:
      schemas:
        a3s:
          defaultRoles: true
          defaultUsers: true
    a3seb:
      schemas:
        a3seb:
          defaultRoles: true
          defaultUsers: true
```
The database is getting created but the schema creation failed with permission error:

```
time="2020-09-02T14:39:15Z" level=info msg="creating database schema \"a3s\" owner \"a3s_a3s_owner\"" cluster-name=pg-testing/postgres-test-interval pkg=cluster
time="2020-09-02T14:39:15Z" level=info msg="creating database schema \"a3sschema\" owner \"a3sdb_a3sschema_owner\"" cluster-name=pg-testing/postgres-test-interval pkg=cluster
time="2020-09-02T14:39:15Z" level=debug msg="closing database connection" cluster-name=pg-testing/postgres-test-interval pkg=cluster
time="2020-09-02T14:39:15Z" level=warning msg="attempted to close an empty db connection object" cluster-name=pg-testing/postgres-test-interval pkg=cluster
**time="2020-09-02T14:39:15Z" level=error msg="could not sync prepared databases: could not execute create database schema: pq: permission denied for database a3s" cluster-name=pg-testing/postgres-test-interval pkg=cluster**
time="2020-09-02T14:39:15Z" level=info msg="cluster has been updated" cluster-name=pg-testing/postgres-test-interval pkg=controller worker=1
```

**The above log  shows , the "a3s" schema is created successfully but the "a3sschema" schema creation failed with permission error.**

Could you please  suggest how do we  create multiple databases using "preparedDatabases"

Thanks
