### ISSUE TITLE
Enable using create_replica_methods - basebackup

### ISSUE THREAD

**Issue by asafo** [zalando/postgres-operator#1133]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Azure AKS & Google GKE
- **Are you running Postgres Operator in production?** [yes | no]
yes
- **Type of issue?** [Bug report, question, feature request, etc.]
feature request

It seems from the docs of the operator (https://postgres-operator.readthedocs.io/en/latest/user/#setting-up-a-standby-cluster)
That there is no option to choose _basebackup_ as create_replica_method.
But it is possible from patroni docs (https://github.com/zalando/patroni/blob/master/docs/replica_bootstrap.rst#standby-cluster)

This would be really useful to enable smooth migrations from clutsers not hosted in AWS.
BTW: Even if I try to use s3 compatible storage (e.g: minio), Still the operator is very AWS oriented. (no simple s3 path, but region,endpoint and bucket)

**Comment by Jan-M** [comment]
Maybe our docs need improvement:

This should work:
```
spec:
    # [...]
    clone:
        cluster: "acid-test-restore-source"
        uid: "<UID>"
        timestamp: "2019-04-26T10:46:57.000+00:00"
        s3_wal_path: "s3://<bucketname>/spilo-backups/<source_db_cluster>/<UID>/wal"
```
