### ISSUE TITLE
Default privileges not setup up for the <db>_owner_user role

### ISSUE THREAD

**Issue by mseiwald** [zalando/postgres-operator#1170]
Hi,

I'm using the default roles created by postgres-operator (reader/writer/owner) and I'm logging in to the DB with `<db>_owner_user` (which has the LOGIN privilege). However if we now create tables with this user (`<db>_owner_user` ), the default privileges for the other users (_reader/_writer) are not applied. I assume this is because the default privilegs are only applied for the owner of a schema which is `<db>_owner`. Is there a way to work around this or what is the recommended approach? (i.e. always running `SET ROLE <db>_owner` before creating tables?)

Thank you

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it - cloud or metal?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Feature Request/Guidance/Bug?

**Comment by FxKu** [comment]
Hey @mseiwald , yeah this was intentional to only have the default privileges for the NOLOGIN owner role because this one should be used to do schema changes. It requires `SET ROLE <db>_owner`, yes. But since the LOGIN owner role is inheriting all rights from the other owner role, maybe default roles should also be set for it.

**Comment by machine424** [comment]
We could do something like:
```
  users:
    # LOGIN by default: https://github.com/zalando/postgres-operator/blob/v1.6.1/pkg/cluster/util.go#L104
    foo_owner: []

  preparedDatabases:
    foo:
      defaultUsers: false
      schemas:
        bar:
          defaultUsers: false
          defaultRoles: false
```
to bypass the need for `foo_owner_user` Role as the doc says that "The roles described in the [previous paragraph](https://github.com/zalando/postgres-operator/blob/v1.6.1/docs/user.md#default-nologin-roles) can be granted to LOGIN roles from the users section in the manifest", but I don't think this is possible, as DefaultRoles (preparedDatabases') will always override RobotRoles (users'): [here](https://github.com/zalando/postgres-operator/blob/v1.6.1/pkg/cluster/cluster.go#L1060) or [here](https://github.com/zalando/postgres-operator/blob/v1.6.1/pkg/cluster/cluster.go#L1093) because its [RoleOrigin](https://github.com/zalando/postgres-operator/blob/v1.6.1/pkg/spec/types.go#L28) is greater. I hope I'm wrong.
If we can really give the LOGIN privilege to the DefaultRoles, this can be a workaround, otherwise, it may be tedious to make sure we change the role every time this is needed.
