### ISSUE TITLE
How to restore from logical Backup in Minio S3

### ISSUE THREAD

**Issue by damlub** [zalando/postgres-operator#1204]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Rancher 2.4.8 Kubernetes on premise.
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** question

I need to setup a backup for the database clusters managed by this postgres-operator. 
My setup is on Rancher Kubernetes Cluster running on-premise, and I have no access to AWS S3 or the like, instead I installed Minio on the same cluster and setup an accessible URL for it. The backup functionality is working well.

My issues are with the restore process. As far as I understand the documentation, you can clone new postgres clusters from a backup in S3.

The procedure I am doing is:
1) Create the postgres cluster, from which I want to have backups and which I want to clone later in step X
```apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: pg
  name: pg-primary
  namespace: default
spec:
  enableLogicalBackup: true
  logicalBackupSchedule: '*/5 * * * *'
  allowedSourceRanges: null
  databases:
    foobar: damian
  numberOfInstances: 2
  postgresql:
    version: "10"
  teamId: pg
  users:
    damian:
      - "superuser"
  volume:
    size: 1Gi
```
2) After this is created I add some table and values in schema `foobar`.
3) I wait until some backup tar.gz is written to minio. e.g., bucket/spilo/pg-primary/c850130b-1e0d-49dc-8e01-1c463c813b4e/logical_backups/1605010203.sql.gz
4) I figure out the UID of this postgres-cluster with `kubectl get postgresql pg-primary -o yaml | grep uid`
5) I create the clone-db-cluster as following (in the same namespace):
```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: pg
  name: pg-primary-2
  namespace: default
spec:
  postgresql:
    version: "12"
  clone:
    cluster: pg-primary
    s3_access_key_id: SecretAccessKey
    s3_endpoint: https://minio.mydomain.tld
    s3_force_path_style: true
    s3_secret_access_key: SecretValue
    timestamp: "2020-11-10T12:10:00+01:00"
    uid: "c850130b-1e0d-49dc-8e01-1c463c813b4e"
  databases:
    foobar: damian
  numberOfInstances: 2
  teamId: pg
  users:
    damian:
      - "superuser"
  volume:
    size: 1Gi
```

Now, when I connect to pg-primary-2 cluster I see foobar schema but not the tables that were created in step 2).
How precise should I specify the date? As far as I understood, the latest backup up to this date should be restored, right?
What do I wrong?

I also tried in different namespace and in different k8s cluster, nothing was successful so far.

Thanks for any hints!
Damian
