### ISSUE TITLE
Postgres-operator doesn't let to create sidecars anymore

### ISSUE THREAD

**Issue by yanchenko-igor** [zalando/postgres-operator#1206]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** v1.5.0-69-gb379db2-dirty
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

After upgrading to the latest image, I noticed that sidecars definition looks like this:
```
  sidecars:
  - env:
    - {}
    - {}
    - {}
    image: wrouesnel/postgres_exporter
    name: postgres-prometheus-exporter
    ports:
    - {}
    resources: {}
```
Even when I edit and insert proper values they get lost, I compared the crd definition with an older version and I see that `preserveUnknownFields: true` disappeared.
