### ISSUE TITLE
sidecar env is not working

### ISSUE THREAD

**Issue by debu99** [zalando/postgres-operator#1244]
if we remove the sidecar env, then the postgres pod can be created(even it is failed), otherwise nothing from kubectl get pod

**Comment by debu99** [comment]
```
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres.develop-postgresdb.credentials.postgresql.acid.zalan.do
        - name: ""
        image: xxxx/pgsidecar
        imagePullPolicy: IfNotPresent
        name: pgsidecar
```

**Comment by debu99** [comment]
- **Which image of the operator are you using?
registry.opensource.zalan.do/acid/postgres-operator:v1.3.0 to v.1.5.0
- **Where do you run it - cloud or metal? 
EKS
- **Are you running Postgres Operator in production?
NO
- **Type of issue?
Bug report


The customized environment variable for sidecar is not working from 1.3.0 to 1.5.0, the test case actually doesn't test customized variable for sidecar

**Comment by FxKu** [comment]
See my comment [here](https://github.com/zalando/postgres-operator/issues/1245#issuecomment-740787035). I think, this has to do with a newer K8s version where the CRD of v1.5 (and older) is automatically converted into the CRD v1 version and fields get pruned because we haven't defined preservation on the object level.

**Comment by debu99** [comment]
@FxKu i believe this is a new bug, as if you test with complete-postgres-manifest.yaml, it doesn't include customized env variable by default

$ kubectl describe crd -n pg postgresqls.acid.zalan.do
```
              Sidecars:
                Items:
                  Additional Properties:                         true
                  Type:                                          object
                  X - Kubernetes - Preserve - Unknown - Fields:  true
                Type:                                            array
```

$ kubectl describe statefulset devops-postgres
```
  Normal   SuccessfulCreate  39s                 statefulset-controller  create Claim pgdata-devops-postgres-0 Pod devops-postgres-0 in StatefulSet devops-postgres success
  Warning  FailedCreate      18s (x13 over 39s)  statefulset-controller  create Pod devops-postgres-0 in StatefulSet devops-postgres failed error: Pod "devops-postgres-0" is invalid: spec.containers[1].env[0].name: Required value
```

$ kubectl get statefulset devops-postgres -o yaml
```
      - env:
        - name: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres.devops-postgres.credentials.postgresql.acid.zalan.do
        image: debu99/pgsidecar
        imagePullPolicy: IfNotPresent
        name: pgsidecar
```
