### ISSUE TITLE
AttachVolume.Attach failed for Replicas

### ISSUE THREAD

**Issue by fjogeleit** [zalando/postgres-operator#1270]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**: registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal Hetzner Cloud (RKE)
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

Hey everyone, today I tried to update the postgres-operator to v1.6.0 and I have an Issue if I try to create a Cluster with more then 1 instance.

The first pod starts without any errors and works so far but the second pod failed in "CreateContainer" Step:

```yaml
Warning  FailedAttachVolume  9s (x6 over 25s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a6a7018e-f42a-4d22-bf30-3a6efb75601b" : rpc error: code = Internal desc = failed to publish volume: Volume assigning step has failed due to an unknown error. (unknown_error)
```

My cluster is running on HetznerCloud and using https://github.com/hetznercloud/csi-driver as StorageClass. The first Pod also using this storage class without errors. Also the older version 1.5.1 worked on the same cluster without this error. The Information I get from a `kubectl describe pod/postgres-cluster-1` is:

```yaml
Name:           postgres-cluster-1
Namespace:      postgres-cluster
Priority:       0
Node:           dev-node-1/10.0.0.3
Start Time:     Tue, 22 Dec 2020 15:14:26 +0100
Labels:         application=spilo
                cluster-name=postgres-cluster
                controller-revision-hash=postgres-cluster-78b48578b9
                statefulset.kubernetes.io/pod-name=postgres-cluster-1
                team=postgres
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/postgres-cluster
Containers:
  postgres:
    Container ID:   
    Image:          registry.opensource.zalan.do/acid/spilo-13:2.0-p2
    Image ID:       
    Ports:          8008/TCP, 5432/TCP, 8080/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  500Mi
    Requests:
      cpu:     100m
      memory:  100Mi
    Environment:
      SCOPE:                      postgres-cluster
      PGROOT:                     /home/postgres/pgdata/pgroot
      POD_IP:                      (v1:status.podIP)
      POD_NAMESPACE:              postgres-cluster (v1:metadata.namespace)
      PGUSER_SUPERUSER:           postgres
      KUBERNETES_SCOPE_LABEL:     cluster-name
      KUBERNETES_ROLE_LABEL:      spilo-role
      PGPASSWORD_SUPERUSER:       <set to the key 'password' in secret 'postgres.postgres-cluster.credentials.postgresql.acid.zalan.do'>  Optional: false
      PGUSER_STANDBY:             standby
      PGPASSWORD_STANDBY:         <set to the key 'password' in secret 'standby.postgres-cluster.credentials.postgresql.acid.zalan.do'>  Optional: false
      PAM_OAUTH2:                 https://info.example.com/oauth2/tokeninfo?access_token= uid realm=/employees
      HUMAN_ROLE:                 zalandos
      PGVERSION:                  13
      KUBERNETES_LABELS:          {"application":"spilo"}
      SPILO_CONFIGURATION:        {"postgresql":{},"bootstrap":{"initdb":[{"auth-host":"md5"},{"auth-local":"trust"}],"users":{"zalandos":{"password":"","options":["CREATEDB","NOLOGIN"]}},"dcs":{"postgresql":{"parameters":{"max_connections":"250"}}}}}
      DCS_ENABLE_KUBERNETES_API:  true
    Mounts:
      /dev/shm from dshm (rw)
      /home/postgres/pgdata from pgdata (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from postgres-pod-token-8kbwf (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  pgdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pgdata-postgres-cluster-1
    ReadOnly:   false
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  postgres-pod-token-8kbwf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  postgres-pod-token-8kbwf
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason              Age               From                     Message
  ----     ------              ----              ----                     -------
  Normal   Scheduled           29s               default-scheduler        Successfully assigned postgres-cluster/postgres-cluster-1 to dev-node-1
  Warning  FailedAttachVolume  9s (x6 over 25s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a6a7018e-f42a-4d22-bf30-3a6efb75601b" : rpc error: code = Internal desc = failed to publish volume: Volume assigning step has failed due to an unknown error. (unknown_error)
```

The Postgres Manifest:

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-cluster
  namespace: postgres-cluster
spec:
  teamId: "postgres"
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    postgres:
    - superuser
    - createdb
  postgresql:
    version: "13"
    parameters:
      max_connections: "250"
  enableShmVolume: true
  enableLogicalBackup: true
  logicalBackupSchedule: "00 05 * * *"
```
