### ISSUE TITLE
Additional volumes are not attached to the Sidecars

### ISSUE THREAD

**Issue by MohamedMSaeed** [zalando/postgres-operator#1273]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
registry.opensource.zalan.do/acid/postgres-operator:v1.5.0

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**  
GCP 

- **Are you running Postgres Operator in production?** 
yes

- **Type of issue?** 
Bug report

I'm trying to set up a `postgres-exporter` sidecar and it doesn't attach the additional volumes at all. 

This is postgresql
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: test-saeed
  namespace: saeed
  labels:
    app: postgres
  annotations: {}

spec:
  teamId: "test"
  numberOfInstances: 3
  users:  # Application/Robot users
    saeed:
      - inherit
      - login
  databases:
    testawy: postgres  # dbname: owner
  postgresql:
    version: "11"
    parameters: # Expert section
      max_connections: "250"
    use_pg_rewind: true  # to re-use master after failover

  podAnnotations:
    sidecar.istio.io/inject: "false"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"

  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  allowedSourceRanges:  # load balancers' source ranges for both master and replica services
  - 127.0.0.1/32
  volume:
    size: 6Gi

  resources:
    requests:
      cpu: 500m
      memory: 501Mi
    limits:
      cpu: "1"
      memory: 1Gi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
    - hostssl all all 0.0.0.0/0 md5
    - host    all all 0.0.0.0/0 md5

  sidecars:
    - name: pg-exporter-sidecar
      image: "wrouesnel/postgres_exporter:v0.8.0"
      args:
      - "--extend.query-path=/etc/config.yaml"
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 100Mi
      ports:
        - name: http
          containerPort: 9187
          protocol: TCP
      env:
        - name: "POD_NAME"
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: "DATA_SOURCE_URI"
          value: $(POD_NAME)/testawy?sslmode=disable
        - name: "DATA_SOURCE_USER"
          valueFrom:
            secretKeyRef:
              name: postgres.test-saeed.credentials
              key: username
        - name: "DATA_SOURCE_PASS"
          valueFrom:
            secretKeyRef:
              name: postgres.test-saeed.credentials
              key: password

  additionalVolumes:
    - name: queries
      mountPath: /etc/config.yaml
      subPath: config.yaml
      targetContainers:
        - pg-exporter-sidecar
      volumeSource:
        configMap:
          name: saeedtest-postgres-prometheus-exporter

```
The `additionalVolume` was attached only to the `postgres` container and not to all containers. 

I tried to use the following but it didn't work:
```
additionalVolumes.targetContainers = all
```

I tried to add `volumeMount` section to the `sidecar pod` but it didn't work too.
```
  sidecars:
    - name: pg-exporter-sidecar
      image: "wrouesnel/postgres_exporter:v0.8.0"
      ......
      volumeMounts:
        - name: queries
          mountPath: /etc/config.yaml
```
