### ISSUE TITLE
Typo in the operator chart

### ISSUE THREAD

**Issue by dsx** [zalando/postgres-operator#1296]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Digitalocean
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

There is a typo in the `values.yaml` of the operator chart:

```yaml
# configure K8s cron job managed by the operator
configLogicalBackup:
  # image for pods of the logical backup job (example runs pg_dumpall)
  logical_backup_docker_image: "registry.opensource.zalan.do/acid/logical-backup:v.1.6.0"
```
Note the extra dot after «v» in `registry.opensource.zalan.do/acid/logical-backup:v.1.6.0`. I believe it should be `registry.opensource.zalan.do/acid/logical-backup:v1.6.0`.
