### ISSUE TITLE
Option to clone only certain databases

### ISSUE THREAD

**Issue by Patralos** [zalando/postgres-operator#1303]
Hi,

It would be great if there would be an option to clone only a specific database (or some of them), either by limiting the clone to databases defined for the cluster. 

If **cluster-source** has databases stag and prod, only stag should be cloned, as prod is not defined:

```
spec:
  clone:
    uid: "xxxx-xxxx-xxx-xxxx-xxxxxx"
    cluster: "cluster-source"
  databases:
    stag: stag
```

Or by defining it explicitly:

```
spec:
  clone:
    uid: "xxxx-xxxx-xxx-xxxx-xxxxxx"
    cluster: "cluster-source"
    databases:
      - stag
```
