### ISSUE TITLE
Add custom volumes in OperatorConfiguration

### ISSUE THREAD

**Issue by aivanov-citc** [zalando/postgres-operator#1322]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal?** Kubernetes or OpenShift? metal Kubernetes
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** feature request

Is it possible to add custom volume mounts globally? We need to connect the sidecar with the config in OperatorConfiguration. If we add to "postgresql", then we have to copy the same records for each postgresql instance

```
apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-configuration
configuration:
...
  sidecars:
    - name: fluentbit
      image: grafana/fluent-bit-plugin-loki:2.1.0-amd64
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - name: fluent-config
          mountPath: /fluent-bit/etc
...
```
Desired feature:
```
apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-configuration
configuration:
...
  volumes:
    - name: fluent-config
      configMap:
        name: fluent-configmap
...
```
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-configmap
  namespace: default
data:
  fluent-bit.conf: |-
...
```
