### ISSUE TITLE
Add support for custom pod labels from postgresql crd

### ISSUE THREAD

**Issue by Starefossen** [zalando/postgres-operator#1382]
Similar to how you can set default pod labels in the `OperatorConfig` crd I suggest having the same possibility from the `Postgresql` crd like this: 

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-test-cluster
spec:
  kubernetes:
    cluster_labels: application:spilo,my-label:acid-test-cluster
```
