### ISSUE TITLE
Sidecar port default protocol are buggy

### ISSUE THREAD

**Issue by haf** [zalando/postgres-operator#1384]
This is a duplicate post of https://github.com/zalando/postgres-operator/issues/1291  — which was never fixed. The core problem after investigation is that the `protocol` in the ports declaration of side-cars isn't compared in a way that counts `protocol: null` === `protocol: TCP` despite TCP being the default if protocol in the Go k8s struct is nil.

This is a good first issue:

1. Create a unit test that validates the bug (by failing) when comparing the protocol property of a ports array (of a side-car or otherwise)
2. Special-case the defaults: this could potentially include other defaults if they exist for this record

Or alternatively; semantic comparison with defaults is probably already implemented in the k8s go SDK: call this SDK's comparison function instead.

---
After getting advice, this is a cross post with https://github.com/zalando/spilo/issues/536 — it would seem the fault is with the operator and not Spilo.

- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.6.0`
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** GCP
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** bug report

For me it's enough to define a sidecar like this, to trigger the behaviour:

```yaml

  sidecars:
  - name: exporter
    image: wrouesnel/postgres_exporter

    env:
    - name: "DATA_SOURCE_URI"
      value: app-analytics-db/analytics?sslmode=require

    - name: "DATA_SOURCE_USER"
      valueFrom:
        secretKeyRef:
          name: postgres.app-analytics-db.credentials
          key: username

    - name: "DATA_SOURCE_PASS"
      valueFrom:
        secretKeyRef:
          name: postgres.app-analytics-db.credentials
          key: password

    - name: PG_EXPORTER_WEB_LISTEN_ADDRESS
      value: ":9114"

    - name: PG_EXPORTER_CONSTANT_LABELS
      value: app=analytics-db,component=postgres

    ports:
    - name: http-prom
      containerPort: 9114

    resources:
      limits:
        cpu: 500m
        memory: 256M
      requests:
        cpu: 100m
        memory: 200M
```

Causes it to fail over every thirty minutes:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/193115/103801222-b8ea5180-504d-11eb-95d8-7dad558d293c.png">

Some logs:

```
time="2021-01-06T17:24:36Z" level=debug msg="metadata.annotation are different" cluster-name=app/app-analytics-db pkg=cluster worker=1
time="2021-01-06T17:24:36Z" level=debug msg="-  zalando-postgres-operator-rolling-update-required: false" cluster-name=app/app-analytics-db pkg=cluster worker=1
time="2021-01-06T17:24:36Z" level=debug msg="+  zalando-postgres-operator-rolling-update-required: true" cluster-name=app/app-analytics-db pkg=cluster worker=1
time="2021-01-06T17:24:36Z" level=info msg="reason: new statefulset containers's exporter (index 1) ports do not match the current one" cluster-name=app/app-analytics-db pkg=cluster worker=1
time="2021-01-06T17:24:36Z" level=debug msg="updating statefulset" cluster-name=app/app-analytics-db pkg=cluster worker=1
time="2021-01-06T17:24:36Z" level=debug msg="patching statefulset annotations" cluster-name=app/app-analytics-db pkg=cluster worker=1
time="2021-01-06T17:24:37Z" level=debug msg="patching statefulset annotations" cluster-name=app/app-analytics-db pkg=cluster worker=1
time="2021-01-06T17:24:37Z" level=debug msg="calling Patroni API on a pod app/app-analytics-db-0 to set the following Postgres options: map[wal_level:logical]" cluster-name=app/app-analytics-db pkg=cluster worker=1
time="2021-01-06T17:24:37Z" level=debug msg="making PATCH http request: http://10.4.7.76:8008/config" cluster-name=app/app-analytics-db pkg=cluster worker=1
```

**Comment by FxKu** [comment]
[This](https://github.com/zalando/postgres-operator/blob/636a9a8191787911dcc7731ab0754488a758872e/pkg/cluster/k8sres.go#L900) is the place where the sidecar ports are set. I don't know how enable internal K8s defaults here.

The comparison to the running statefulset is very [basic](https://github.com/zalando/postgres-operator/blob/636a9a8191787911dcc7731ab0754488a758872e/pkg/cluster/cluster.go#L496) atm. If somebody wants to add more logic there, PRs are welcome. Since we do not use sidecars ourselves there's no prio currently to fix this.

**Comment by jouve** [comment]
```
time="2021-03-29T14:17:21Z" level=debug msg="-              containerPort: 9187," cluster-name=nextcloud/acid-nextcloud pkg=cluster
time="2021-03-29T14:17:21Z" level=debug msg="-              protocol: TCP" cluster-name=nextcloud/acid-nextcloud pkg=cluster
time="2021-03-29T14:17:21Z" level=debug msg="+              containerPort: 9187" cluster-name=nextcloud/acid-nextcloud pkg=cluster
...
time="2021-03-29T14:17:21Z" level=info msg="reason: new statefulset containers's exporter (index 1) ports do not match the current one" cluster-name=nextcloud/acid-nextcloud pkg=cluster
```

**Comment by toabi** [comment]
I found this because I have the same issue.

My sidecars config looks like this: (sorry it's HCL and not YAML, but should tell the same story)

```hcl
sidecars = [{
        name : "exporter"
        image : "quay.io/prometheuscommunity/postgres-exporter:${var.pg_exporter_image_tag}"
        ports = [{
          name          = "exporter"
          containerPort = var.pg_exporter_port
          protocol      = "TCP"
        }]
        resources = var.pg_exporter_resources
        env = [
          {
            name = "DATA_SOURCE_URI"
            valueFrom = {
              fieldRef = {
                fieldPath = "metadata.name"
              }
            }
          },
          {
            name = "DATA_SOURCE_USER"
            valueFrom = {
              secretKeyRef = {
                name = "postgres.${each.key}.credentials.postgresql.acid.zalan.do"
                key  = "username"
              }
            }
          },
          {
            name = "DATA_SOURCE_PASS"
            valueFrom = {
              secretKeyRef = {
                name = "postgres.${each.key}.credentials.postgresql.acid.zalan.do"
                key  = "password"
              }
            }
          },
          {
            name  = "PG_EXPORTER_AUTO_DISCOVER_DATABASES"
            value = "true"
          },
        ]
      }]
```

But the whole set gets recreated every resync_period with this message:

```
time="2022-01-26T13:39:59Z" level=info msg="statefulset postgresql/core-shared is not in the desired state and needs to be updated" cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-          terminationMessagePath: /dev/termination-log," cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-          terminationMessagePolicy: File," cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-                  apiVersion: v1," cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-          terminationMessagePath: /dev/termination-log," cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-          terminationMessagePolicy: File," cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-      restartPolicy: Always," cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-      dnsPolicy: ClusterFirst," cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-      serviceAccount: postgres-pod," cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-      }," cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-      schedulerName: default-scheduler" cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="+      }" cluster-name=postgresql/core-shared pkg=cluster
time="2022-01-26T13:39:59Z" level=debug msg="-      kind: PersistentVolumeClaim," cluster-name=postgresql/core-shared pkg=cluster
```

It's not the ports in my case but the env… but I don't see what the difference could be. I also once added the default envs the operator adds to there but it didn't make a difference either.

**Comment by toabi** [comment]
Found out what the difference was for my issue: the `apiVersion: v1` in that fieldRef. With this I don't have restarts anymore!

```
    - name: DATA_SOURCE_URI
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
```
