### ISSUE TITLE
Clone (recovery) from wal in s3 bucket- is always "system ID mismatch, node stage-cabinet-1 belongs to a different cluster"

### ISSUE THREAD

**Issue by foxmeyson** [zalando/postgres-operator#1391]
Hello, tnx for operator, but I cannot recover from WAL S3 bucket. 
The original cluster is already deleted. 
I tried a lot of options, the current config is below. I always get the error
"system ID mismatch, node stage-DB belongs to a different cluster: 6935132276600397903! = 6932220706611593295"

How to throw off the cluster id, now where is it stored? And why is it not readable from the configmap?

IMAGES (postgres operator)
registry.opensource.zalan.do/acid/postgres-operator:v1.5.0

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-pod-configmap
  namespace: pg-stage-DB
data:
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_NUM_TO_RETAIN: "10"
  WALG_DISABLE_S3_SSE: "true"
  WALG_UPLOAD_CONCURRENCY: "10"
  WALG_DOWNLOAD_CONCURRENCY: "10"
  WALG_UPLOAD_DISK_CONCURRENCY: "2"
  WALG_DELTA_MAX_STEPS: "10"
  WALG_S3_PREFIX: "s3://wal_stage/1"
  WALG_COMPRESSION_METHOD: "brotli"
  AWS_ACCESS_KEY_ID: key
  AWS_SECRET_ACCESS_KEY: key
  AWS_ENDPOINT: endpoint
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_REGION: region

# ---------------------------------------------------
  # # # RESTORE FROM WAL PITR:

  CLONE_METHOD: CLONE_WITH_WALG
  CLONE_AWS_ACCESS_KEY_ID: key
  CLONE_AWS_SECRET_ACCESS_KEY: key
  CLONE_AWS_ENDPOINT: endpoint
  CLONE_AWS_REGION: region
  CLONE_WAL_S3_BUCKET: "s3://wal_stage/1"
  CLONE_WAL_BUCKET_SCOPE_SUFFIX: "/6932220706611593295"
  CLONE_TARGET_TIME: "2021-03-01T12:49:03+03:00" # time in the WAL archive that we want to restore
  CLONE_SCOPE:  name_old_cluster # name of the original cluster

```
any help would be very helpful

**Comment by foxmeyson** [comment]
I found that the cluster id is stored at the Kubernetes endpoint in the annotation ("initialize"). The endpoint is created when a new cluster is created, and there is already another ID. Now that the original cluster has already been deleted, I replace the cluster id in the endpoint, but it does not help.
I also tried this variant in POD exec (like hundreds of others):
```
pg_controldata -D "$PGDATA"
etcdctl get /service/name_old_cluster/initialize
error: misconfigured etcdctl
```
I understand that the ID is not contained in etcd, but how can I fix it I don't understand.
those. the cluster itself has already received an incorrect ID from somewhere at the start, and somewhere else it holds it, except in Kubernetes endpoint.

any help would be very helpful

**Comment by foxmeyson** [comment]
I described the solution we found with the team here:

https://github.com/zalando/postgres-operator/issues/1395

**Comment by Dador** [comment]
In case anyone want to change System ID (it's named `initialize`), which is helpful if you're moving database outside of patroni or postgres-operator.

You can change it in `Endpoint` named `[cluster-name]-pg-config`. If you use Rancher then you can find it in menu `Core` - `Endpoints`.

For example:
```
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    initialize: "[your new System ID]"
  name: [cluster-name]-pg-config
  namespace: [namespace]
```

Also you can just delete that `Endpoint` and seems like config will be regenerated automatically using System ID (`initialize`) from Postgres data directory (so error `system ID mismatch` will be resolved).
