### ISSUE TITLE
Global postgres parameters for all instances

### ISSUE THREAD

**Issue by aivanov-citc** [zalando/postgres-operator#1394]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** question, feature request

Is it possible to add global parameters for all Postgres instances? We have almost all instances with the same logging parameters.

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: db-name
  namespace: default
spec:
  ...
  postgresql:
    version: "13"
    parameters:
      logging_collector: "off"
      log_connections: "on"
      log_disconnections: "on"
      log_duration: "on"
      log_min_duration_statement: "1000"
  ...
```
You have to transfer these parameters from one instance to another. It would be nice to describe them at the operator configuration level, rather than at the instance configuration level.
```yaml
apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-configuration
configuration:
  ...
  parameters:
      logging_collector: "off"
      log_connections: "on"
      log_disconnections: "on"
      log_duration: "on"
      log_min_duration_statement: "1000"
  ...
```
