### ISSUE TITLE
Cluster that was created with kubeclt create not visible in PostgreSQL Operator UI

### ISSUE THREAD

**Issue by christian-2** [zalando/postgres-operator#1399]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.1, registry.opensource.zalan.do/acid/postgres-operator-ui:v1.6.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

I have created a simple/initial cluster with `kubectl create` from the following manifest. Its pods come up, but it does not show in the Postgres Operator UI. If I create a similar cluster in the UI, it will show up there. Is this a feature (i.e. does the UI only recognize clusters that it created) or a bug (perhaps in my manifest)?

```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: keycloak-cluster
  namespace: keycloak
spec:
  teamId: keycloak
  volume:
    size: 1Gi
  numberOfInstances: 2
  postgresql:
    version: "13"
  users: 
    foo_user: []
```
