### ISSUE TITLE
Error in Statefulset (sidecar env variables) while using CRD v1.6 (version apiextensions.k8s.io/v1 while apiextensions.k8s.io/v1beta1works fine)

### ISSUE THREAD

**Issue by neelasha-09** [zalando/postgres-operator#1404]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** OpenShift-4.5.7
- **Are you running Postgres Operator in production?** [yes | no] Not yet
- **Type of issue?** [Bug report, question, feature request, etc.] bug Report

We are using sidecar containers and we passed our own ENV variables to them  as seen below,

```
  sidecars:
    - name: "exporter"
      image: "wrouesnel/postgres_exporter:v0.8.0"
      resources:
        limits:
          cpu: 500m
          memory: 256M
        requests:
          cpu: 100m
          memory: 200M
      env:
       - name: DATA_SOURCE_NAME
         value: "user=postgres host=/var/run/postgresql/ sslmode=require"
```
When we move to  using the new CRD's as in version 1.6 which are` apiextensions.k8s.io/v1` version, we get the error while creating the cluster even the parameter `x-kubernetes-preserve-unknown-fields: true` is defined.

```             sidecars:
                type: array
                nullable: true
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
```
**Error in STS**

```sh
Warning FailedCreate 9s (x13 over 29s) statefulset-controller create Pod postgres-test-0 in StatefulSet postgres-test failed error: Pod "postgres-test-0" is invalid: spec.containers[1].env[4].name: Required value
```

oc edit sts shows the varaibale name as empty

```sh
env:
- name: ""
```
We created the CRD using v1beta1 version as attached, and the cluster works fine with no error in STS.
[CRD-1.6.1 in format of v1beta1.yaml.txt](https://github.com/zalando/postgres-operator/files/6130079/CRD-1.6.1.in.format.of.v1beta1.yaml.txt)

We investigated further and the reason is when kubernetes migrated from `v1beta1` to `v1`, it adds a field name `preserveUnknownFields: true`  which cannot be added directly in v1 version.
