### ISSUE TITLE
FATAL ERROR: requested WAL segment has already been removed

### ISSUE THREAD

**Issue by haslersn** [zalando/postgres-operator#1409]
- `image: registry.opensource.zalan.do/acid/postgres-operator:v1.6.1`
- Bare Metal K8s
- Production usage: yes
- Type of issue: Bug report

I have several postgres clusters (each with `numberOfInstances: 3`) that have problems like the following:

The master Pod is running fine, but one or two replica Pods fail to start PostgreSQL. The error seems to be related to WAL restoring: When I check the log of one of the affected Pods via

```bash
kubectl exec -it podname -- tail -f pgdata/pgroot/pg_log/*
```

then I see a fatal error like this one:

```
2021-03-17 15:30:49.708 UTC,,,13734,,605220a9.35a6,2,,2021-03-17 15:30:49 UTC,,0,FATAL,XX000,"could not receive data from WAL stream: ERROR:  requested WAL segment 0000000E0000001D000000D2 has already been removed",,,,,,,,,""
```

I configured WAL backup & restore using the `wal_s3_bucket` option in the `OperatorConfiguration` together with the following Pod environment:

```
configMapGenerator:
  - name: pod-env
    literals:
      - CLONE_USE_WALG_BACKUP=true
      - CLONE_USE_WALG_RESTORE=true
      - CLONE_AWS_ENDPOINT=https://<redacted>
      - CLONE_AWS_S3_FORCE_PATH_STYLE=true
      - CLONE_AWS_ACCESS_KEY_ID=<redacted>
      - CLONE_AWS_SECRET_ACCESS_KEY=<redacted>
      - USE_WALG_BACKUP=true
      - USE_WALG_RESTORE=true
      - AWS_ENDPOINT=https://<redacted>
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_ACCESS_KEY_ID=<redacted>
      - AWS_SECRET_ACCESS_KEY=<redacted>
      - WALG_COMPRESSION_METHOD=lzma
```

I created a [gist with my postgres-operator manifests](https://gist.github.com/haslersn/14e7aadb7c4786c30a598e4a68886def). There you can also find:

- [A more complete log](https://gist.github.com/haslersn/14e7aadb7c4786c30a598e4a68886def#file-log)
- [The postgresql manifest which that log belongs to](https://gist.github.com/haslersn/14e7aadb7c4786c30a598e4a68886def#file-postgres-cluster-yaml)
- [A listing of the wal_005 directory in the backup](https://gist.github.com/haslersn/14e7aadb7c4786c30a598e4a68886def#file-bucket-content)

_Note_ that the wal_005 directory is quite empty, because the path was changed by upgrading to postgres-operator v1.6.1. That upgrade can **not** the reason for the error, because I **already had the problem before the upgrade**. I upgraded to postgres-operator v1.6.1 to see whether that fixes the problem. It did not.
