### ISSUE TITLE
Dynamic configuration settings (ttl,loop_wait and retry_timeout)  are not updated

### ISSUE THREAD

**Issue by kirillka415** [zalando/postgres-operator#1417]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** AKS K8s
- **Are you running Postgres Operator in production?**  no
- **Type of issue?** Bug report

I was trying to change Dynamic configuration settings (ttl,loop_wait and retry_timeout) by specifying them in an yaml manifest of a postresql cluster. 
I used the following rule to calculate settings
```
ttl >= loop_wait + retry_timeout *2
``` 

As result, postgres-operator  was doing  rolling update for the the cluster after appling the manifest,
then  I checked patroni setting from master pod by command ``` curl -s localhost:8008/config | jq .```,
there are nothing was changed.

As workaround I changed it by the command below
```
curl -s -XPATCH -d \
        '{"loop_wait":20,"ttl":65,"retry_timeout":20}' \
        http://localhost:8008/config | jq .
```

Her is my manifest 
```
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-pg-dbcluster"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "12"
  numberOfInstances: 3 
  patroni:
    ttl: 65
    loop_wait: 20
    retry_timeout: 20
  volume:
    size: "2Gi"
  users:
    mydb_owner: [] 
  databases:
    mydb: mydb_owner 
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
```
