### ISSUE TITLE
Default privileges are not set in public schema

### ISSUE THREAD

**Issue by machine424** [zalando/postgres-operator#1420]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Kube on Cloud
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report?

When I deploy a postgresl manifest with:

```
  preparedDatabases:
    foo:
      defaultUsers: true
      schemas:
        public:
          defaultUsers: false
          defaultRoles: false
      extensions:
        pg_stat_statements: public
        btree_gist: public
```

The Global Default privileges are not created in the `public` schema, even though PG says that it applies the globalDefaultPrivilegesSQL statements in [here](https://github.com/zalando/postgres-operator/blob/v1.6.1/pkg/cluster/database.go#L42), we cannot fallback to schemaDefaultPrivilegesSQL because `public` schema  gets removed [here](https://github.com/zalando/postgres-operator/blob/v1.6.1/pkg/cluster/sync.go#L679) as already present. 

Of course, when I manually re-execute the globalDefaultPrivilegesSQL statements (that I get from PG logs), the default privileges get created in `public` schema.

When I try with another schema name, the operator creates the default privileges as expected.

Am I doing something wrong?
