### ISSUE TITLE
Pooler not created when using more than 1 Postgres instance

### ISSUE THREAD

**Issue by Martin-Hogge** [zalando/postgres-operator#1432]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** GCP
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

I have installed `postgres-operator` and `postgres-operator-ui` using the Helm chart.
The setup is classic except that I've configured a configMap with `WAL-G` enabled:

```yaml
pod_environment_configmap: "postgres-operator/postgres-pod-config"
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: postgres-operator
data:
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  AWS_ACCESS_KEY_ID: "xxx"
  AWS_SECRET_ACCESS_KEY: "xxx"
  WALG_S3_PREFIX: "s3://postgres-backup/"
  AWS_ENDPOINT: "https://minio.mydomain.com"
```

When I'm creating a cluster with a single instance and `connectionPooler` enabled this is working fine.
If I'm creating a cluster with 2 or more instances (and `connectionPooler` enabled), the pooler is never created and I have these logs in the `postgres-operator`pod:

```
Error
2021-03-30 14:26:10.598 CESTtime="2021-03-30T12:26:10Z" level=error msg="failed to create cluster: pod labels error: still failing after 200 retries" cluster-name=default/acid-test-zalando-postgresql-10 pkg=cluster worker=6
Error
2021-03-30 14:26:10.608 CESTtime="2021-03-30T12:26:10Z" level=error msg="could not create cluster: pod labels error: still failing after 200 retries" cluster-name=default/acid-test-zalando-postgresql-10 pkg=controller worker=6
```

I checked the labels and they are the same (except the name of the cluster) as in the cluster created with a single instance.

Here is the manifest of the cluster:
```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  creationTimestamp: '2021-03-30T12:22:51Z'
  generation: 1
  labels:
    team: acid
  name: acid-test-zalando-postgresql-12
  namespace: default
spec:
  allowedSourceRanges: null
  databases:
    adisoft: adisoft
  enableConnectionPooler: true
  numberOfInstances: 2
  postgresql:
    version: '13'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    adisoft: []
  volume:
    size: 10Gi
status:
  PostgresClusterStatus: SyncFailed
```
