### ISSUE TITLE
Adding/changing additionalVolumes does not trigger StatefulSet update

### ISSUE THREAD

**Issue by stephan2012** [zalando/postgres-operator#1458]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.6.2`
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s (`kubeadm`)
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

The Postgres Operator does not update the existing database StatefulSet when adding `additionalVolumes` like

```yaml
  additionalVolumes:
  - mountPath: /certs/minio
    name: minio-ca-cert
    targetContainers: []
    volumeSource:
      secret:
        secretName: minio-ca-cert
```

However, deleting the StatefulSet and the operator Pod leads to the desired change, i.e. the operator recreates the StatefulSet with the specified volumes added. The logs show that the operators notices the change, but that’s all.
