### ISSUE TITLE
Question about scaling in k8s cloud.

### ISSUE THREAD

**Issue by Menzorg** [zalando/postgres-operator#1469]
Hello. Thanks a lot for this pretty operator.

I could not find info about scaling pods with a postgres operator!
I have operator in my k8s cluster and CRD postgres, configured to be 3-instancies pg-cluster. So, if I want to enable autoscaling, what shall i do? Is it built in? I meen to auto-scale statefulset pod count. 

I know, that k8s have a HPA for example, but... postgres operator has some checking feature to "repare" pg-cluster and if i change statefulset pods count, then operator will "fix" to mainfest default value = 3. What do i need to do? Create pg-cluster with come other way that crd? Or maybe some patrony configuration? Mayby i will find answer soon and will close issue, but i think, it may be question that interests not only me.

best regards, Piter.

**Comment by Menzorg** [comment]
any advices?

**Comment by Sicaine** [comment]
What is your expectation on autoscaling though?

For a database setup, autoscaling up and down doesn't make much sense as  it takes time and resources from your existing databases due to your new instance syncing up.

For bigger databases, that can take hours or days.

**Comment by Menzorg** [comment]
> What is your expectation on autoscaling though? ... For bigger databases, that can take hours or days.

My expectation is using HPA. Our DB is small (about 300mb). We have configured in crd count of instances, but we want to increase the number not manually when we have highload. In our case, when we increase count manually - every new instance starts for minute. To my mind it is good solution to have autoscaling ability in this scenario.

**Comment by Menzorg** [comment]
I think, it may be good solution, if we could configure conffguration checker to check or not to check number of instancies, for example

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: test-pg-cluster
  namespace: test-namespace
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-13:2.0-p6
  teamId: "test"
  numberOfInstances: 3
  checkNumberOfInstances: true
```
