### ISSUE TITLE
Adding extensions to databases not only to preparedDatabases

### ISSUE THREAD

**Issue by memogarcia** [zalando/postgres-operator#1472]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/spilo-13:2.0-p6
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**  Bare Metal K8s - Charmed Kubernetes
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

Is it possible to allow the configuration of extensions in `databases`? At this moment I can only configure extensions on `preparedDatabases` because `preparedDatabases` doesn't allow to set users defined in `users` section to be the owners of that database (or at least the docs doesn't specify how to do this)

What I'm looking to do is one of the following:

```yaml
  users:
    gitlab:
      - superuser
      - createdb
  databases:
    gitlabhq_production:
      owner: gitlab
      extensions:
        pg_trgm: public
        btree_gist: public
```

Or

```yaml
  users:
    gitlab:
      - superuser
      - createdb
  preparedDatabases:
    gitlabhq_production:
      owner: gitlab
      extensions:
        pg_trgm: public
        btree_gist: public
```

Is this possible?
