### ISSUE TITLE
TLS certs not rotating

### ISSUE THREAD

**Issue by irishandyb** [zalando/postgres-operator#1551]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Kubernetes
- **Are you running Postgres Operator in production?** No
- **Type of issue?** Question

I am having difficulty with the auto rotation of TLS certificates.

I have a `Postgresql` instance with the following TLS configuration:

```
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  tls:
    secretName: "my-cert"
    certificateFile: "tls.crt"
    privateKeyFile: "tls.key"
    caFile: "ca.crt"
    caSecretName: ""
```

The cert-manager certificate is described as:
```
Spec:
  Dns Names:
    my-postgresql
  Duration:  1h0m0s
  Issuer Ref:
    Kind:        ClusterIssuer
    Name:        my-ca
  Renew Before:  10m0s
  Secret Name:   my-cert
Spec:
  Dns Names:
    my-postgresql
  Duration:  1h0m0s
  Issuer Ref:
    Kind:        ClusterIssuer
    Name:        my-ca
  Renew Before:  10m0s
  Secret Name:   my-cert
```

When I first deploy, I run an openssl test to identify the notAfter date for the endpoint:
```
openssl s_client -starttls postgres -connect localhost:5432 | openssl x509 -enddate -noout
```

However, even long after the 1 hour expiration of the certificates are not rotated.
I can confirm that the cert-manager secret is updated at the renew time.

The documentation states the following: https://github.com/zalando/postgres-operator/blob/master/docs/user.md
> Certificate rotation is handled in the Spilo image which checks every 5 minutes if the certificates have changed and reloads postgres accordingly.

I cannot find the component or process that is responsible for rotating the certs.

Any input is greatly appreciated.
