### ISSUE TITLE
Patroni Rest API authentication 

### ISSUE THREAD

**Issue by RejoOommen** [zalando/postgres-operator#1558]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.6.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Rancher k8
- **Are you running Postgres Operator in production?** [yes | no] Yes
- **Type of issue?** [Bug report, question, feature request, etc.] question

I would like to enable authentication for patroni rest API via the CR(as given below). Currently, I do not see an option via the CR or am I missing something?

```
restapi:
#  listen: 127.0.0.1:8008
#  connect_address: 127.0.0.1:8008
  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
  authentication:
    username: username
    password: password
```
