### ISSUE TITLE
Add declarative setting of parameters to new users

### ISSUE THREAD

**Issue by aivanov-citc** [zalando/postgres-operator#1560]
Please, answer some short questions which should help us to understand your problem / question better?

Which image of the operator are you using? registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
Where do you run it - cloud or metal? Kubernetes or OpenShift? metal Kubernetes
Are you running Postgres Operator in production? yes
Type of issue? feature request

Good day! When creating an instance of postgres, it is possible to create new users. Please add the ability to configure parameters for new users and default users (owner, writer, reader). For example, connlimit, now users are created with conlimit = -1. It is very important to be able to do this when deploying clusters declaratively. Already at the design level, it is possible to distribute the connections.

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-test-cluster
spec:
  users:
    zalando:
    - superuser
    - createdb
    simple_user:
    - login
  users_parameters:
    simple_user:
      connlimit: 2
    default-writer-user:
      connlimit: 10
```
