### ISSUE TITLE
clone never finishes and get stuck

### ISSUE THREAD

**Issue by yelhouti** [zalando/postgres-operator#1564]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

I start a clone with the following config:
```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: tailosoft-restore-test
spec:
  teamId: "tailosoft"
  volume:
    size: 1Gi
    storageClass: openebs-hostpath
  numberOfInstances: 1
  postgresql:
    version: "13"
  clone:
    cluster: tailosoft-cluster
    uid: 81258dab-f363-4ca6-9f5c-9917c9b8eb45
    timestamp: "2021-07-20T03:31:00+02:00"
```

It gets stuck after initializing the envDirs, and trying to clone with the following logs
```
2021-07-20 03:29:35,178 INFO: Running custom bootstrap script: envdir "/run/etc/wal-e.d/env-clone-tailosoft-cluster" python3 /scripts/clone_with_wale.py --recovery-target-time="2021-07-20T03:31:00+02:00"
2021-07-20 03:29:35,291 INFO: Trying s3://postgres-wal/spilo/tailosoft-cluster/81258dab-f363-4ca6-9f5c-9917c9b8eb45/wal/13/ for clone
2021-07-20 03:29:45,573 INFO: Lock owner: None; I am tailosoft-restore-test-0
2021-07-20 03:29:45,573 INFO: not healthy enough for leader race
2021-07-20 03:29:45,595 INFO: bootstrap in progress
```
and keeps repeating the last three lines indefinitely.

why I think this is an issue with the operator? :

When I patch the statefullset to infinite loop:
```
kubectl -n tailosoft-restore-test patch statefulsets.apps tailosoft-restore-test -p '{"spec": {"template": {"spec": {"containers": [{"name": "postgres", "command": ["/bin/sh"], "args": ["-c", "while true; do echo hello; sleep 10;done"]}] }}}}'
```
and delete the pod so it is recreated, I exec into it and run:
```
su postgres
/launch.sh init # to init env variables..., it fails with: Error creating replica using method wal_e... 
# ctrl+c to leave launch script

envdir "/run/etc/wal-e.d/env-clone-tailosoft-cluster" python3 /scripts/clone_with_wale.py --recovery-target-time="$CLONE_TARGET_TIME" --datadir=$PGDATA  --scope=$CLONE_SCOPE
```
now this works great and I am able to find my data. (maybe running the launch is not required, since env should already have everything...)

This suggests that the command that was run was by the startup script is broken somehow.

Here my envvars (except from the AWS credentials)
```bash
  BACKUP_SCHEDULE: "00 01 * * *" # Every day at 1AM
  BACKUP_NUM_TO_RETAIN: "14" # 14 days
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  AWS_ENDPOINT: "https://<MINIO_URL>"
  AWS_ACCESS_KEY_ID: ...
  AWS_SECRET_ACCESS_KEY: ...
  AWS_S3_FORCE_PATH_STYLE: "true"
```
