### ISSUE TITLE
Change backup path s3

### ISSUE THREAD

**Issue by mrszop** [zalando/postgres-operator#1588]
Hello,

is there a way to change to backup path to s3? Currently I'm getting always a backup created like `s3://$s3-bucket-name/spilo/`. I'd like to have something like this: `s3://$s3-bucket-name/szop/`. My config looks like this:

```yaml
---
configAwsOrGcp:
  aws_region: "eu-central-1"
  aws_endpoint: "https://s3.eu-central-1.amazonaws.com"
  wal_s3_bucket: "$s3-bucket-name"

configLogicalBackup:
  logical_backup_provider: "s3"
  logical_backup_s3_access_key_id: "ACCESS_KEY_ID"
  logical_backup_s3_secret_access_key: "SECRET_KEY"
  logical_backup_s3_bucket: "$s3-bucket-name"
  logical_backup_s3_region: "eu-central-1"
  logical_backup_s3_endpoint: "https://s3.eu-central-1.amazonaws.com"
  logical_backup_schedule: "00 05 * * *"
```

Any chance to set a specific path?

Cheers
