### ISSUE TITLE
operator installation thruoght helm does not work

### ISSUE THREAD

**Issue by houshym** [zalando/postgres-operator#1597]
Hi 
I did:
1- git clone https://github.com/zalando/postgres-operator.git
2- helm install postgres-operator ./charts/postgres-operator

I got following error
```
helm install postgres-operator ./charts/postgres-operator
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(OperatorConfiguration.configuration.kubernetes): unknown field "enable_cross_namespace_secret" in do.zalan.acid.v1.OperatorConfiguration.configuration.kubernete
```

**Comment by thedv91** [comment]
Hi @houshym 
You should delete the old CustomResourceDefinitions

**Comment by houshym** [comment]
it is brand new cluster

**Comment by taxilian** [comment]
helm upgrade should update any custom CRDs, but:

```
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(OperatorConfiguration.configuration.kubernetes): unknown field "enable_cross_namespace_secret" in do.zalan.acid.v1.OperatorConfiguration.configuration.kubernetes, ValidationError(OperatorConfiguration.configuration.teams_api): unknown field "enable_team_member_deprecation" in do.zalan.acid.v1.OperatorConfiguration.configuration.teams_api, ValidationError(OperatorConfiguration.configuration.teams_api): unknown field "role_deletion_suffix" in do.zalan.acid.v1.OperatorConfiguration.configuration.teams_api]
```

**Comment by wlritchi** [comment]
In general [Helm does not yet have a recommended way to upgrade CRDs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations). In my case, after verifying that the new CRDs were compatible with my existing resources (no fields renamed, for example), I was able to simply `kubectl apply -f path/to/new/crd.yaml` each of the CRDs to update them. Requiring manual intervention via `kubectl` isn't ideal, especially if you're using some kind of GitOps-based workflow, but since Helm doesn't yet have a solution this may be your best option.

**Comment by manuel-koch** [comment]
I have the same issue, trying to install helm chart for the first time into k8s cluster, i.e. there are no CRDs yet:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(OperatorConfiguration.configuration.load_balancer): unknown field "enable_master_pooler_load_balancer" in do.zalan.acid.v1.OperatorConfiguration.configuration.load_balancer, ValidationError(OperatorConfiguration.configuration.load_balancer): unknown field "enable_replica_pooler_load_balancer" in do.zalan.acid.v1.OperatorConfiguration.configuration.load_balancer]
```

Using latest helm repo

```sh
$ helm repo add postgres-operator https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
$ helm repo update postgres-operator

$ helm show chart postgres-operator/postgres-operator
apiVersion: v1
appVersion: 1.7.1
version: 1.7.1
.....
```

Using custom helm values ( postgres-operator-helm-values.yaml ):
```yaml
configLoadBalancer:
  # DNS zone for cluster DNS name when load balancer is configured for cluster
  #db_hosted_zone: db.example.com
  # toggles service type load balancer pointing to the master pod of the cluster
  enable_master_load_balancer: true
  # toggles service type load balancer pointing to the master pooler pod of the cluster
  enable_master_pooler_load_balancer: true
  # toggles service type load balancer pointing to the replica pod of the cluster
  enable_replica_load_balancer: true
  # toggles service type load balancer pointing to the replica pooler pod of the cluster
  enable_replica_pooler_load_balancer: true
```

Installing with
```sh
helm upgrade --wait --install --namespace postgres-operator \
             --values postgres-operator-helm-values.yaml \
             postgres-operator postgres-operator/postgres-operator
```
