### ISSUE TITLE
Removing cluster with helm delete

### ISSUE THREAD

**Issue by eskornev** [zalando/postgres-operator#1605]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** minikube
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

When I remove cluster install via "helm delete ..." it destroys operator itself and one pod of 3 replica cluster.
How can I configure removing of remaining cluster pods?
Cluster removed by job with pre-delete helm hook.
Here is command from job:

```
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    args:
    - 'curl -tlsv1 -ik -X DELETE -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
      https://kubernetes.default.svc.cluster.local/apis/acid.zalan.do/v1/namespaces/test/postgresqls/pg-cluster1-12
      -vv'
```

and logs from job:

```
HTTP/2 200 
100   250  100   250    0     0   6817      0 --:--:-- --:--:-- --:--:--  6944
* Connection #0 to host kubernetes.default.svc.cluster.local left intact
cache-control: no-cache, private
content-type: application/json
x-kubernetes-pf-flowschema-uid: 7c46e6b0-327f-4523-af2a-5be83f209875
x-kubernetes-pf-prioritylevel-uid: d240ffc8-9249-47a8-9ee8-9ea8a6620f1f
content-length: 250
date: Wed, 01 Sep 2021 12:16:59 GMT

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Success",
  "details": {
    "name": "pg-cluster1-12",
    "group": "acid.zalan.do",
    "kind": "postgresqls",
    "uid": "96fbbf8d-6df7-42bc-882a-685047d266e7"
  }

```
