### ISSUE TITLE
Initialising standby cluster and failing to find backup

### ISSUE THREAD

**Issue by davedc** [zalando/postgres-operator#1610]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.7.0
registry.opensource.zalan.do/acid/logical-backup:v1.7.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
Running in Kubernetes with Oracle Cloud 
- **Are you running Postgres Operator in production?**
Noppe
- **Type of issue?** [Bug report, question, feature request, etc.]
Bug report

While attempting to bring up a standby cluster from the [S3 Compatability layer in Oracle Cloud Buckets](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm), the bootstrap process is failing when looking for backups:

Postgres logs:
```
2021-09-06 06:04:23,734 INFO: trying to bootstrap a new standby leader
Can not find any backups
2021-09-06 06:04:26,440 ERROR: Error creating replica using method bootstrap_standby_with_wale: envdir "/run/etc/wal-e.d/env-standby" bash /scripts/wale_restore.sh exited with code=1
2021-09-06 06:04:26,440 ERROR: failed to bootstrap clone from remote master None
```

Weirdly enough, running the backup-list command manually finds the backups correctly. At least I knew that my `s3_wal_path` was set correctly and is accessible.
```
kubectl exec -it --namespace=pg-test-1 acid-pg-test-clone-1-0 -- envdir "/run/etc/wal-e.d/env-standby" wal-g backup-list            
name                          modified             wal_segment_backup_start
base_000000010000000000000002 2021-09-05T23:54:56Z 000000010000000000000002
base_000000010000000000000040 2021-09-06T01:00:20Z 000000010000000000000040
base_00000002000000000000004E 2021-09-06T01:14:31Z 00000002000000000000004E
```

Expectedly, running the same command with `envdir "/run/etc/wal-e.d/env" wal-g backup-list ` finds no backups.
```
root@acid-pg-test-clone-1-0:/home/postgres# envdir "/run/etc/wal-e.d/env" wal-g backup-list
INFO: 2021/09/06 06:38:31.243341 No backups found
```

For context, here is my ConfigMap.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: postgres-operator
data:
  AWS_ENDPOINT: https://qweqweqwe.compat.objectstorage.ap-sydney-1.oraclecloud.com:443
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_REGION: ap-sydney-1
  WALG_DISABLE_S3_SSE: "true"
  USE_WALG_BACKUP: "true"
  USE_WALG: "true"
  USE_WALG_RESTORE: "true"
  STANDBY_USE_WALG_RESTORE: "true"
  STANDBY_WALG_DISABLE_S3_SSE: "true"
  STANDBY_AWS_S3_FORCE_PATH_STYLE: "true"
  STANDBY_WALE_ENV_DIR: /run/etc/wal-e.d/env-standby
  STANDBY_AWS_ENDPOINT: https://qweqweqwe.compat.objectstorage.ap-sydney-1.oraclecloud.com:443
  STANDBY_AWS_REGION: ap-sydney-1
  STANDBY_AWS_ACCESS_KEY_ID: xxxx
  STANDBY_AWS_SECRET_ACCESS_KEY: xxxx
```

Is there any configuration that I could be missing here? Is there another place that I can take a look to dig in a bit deeper?
