### ISSUE TITLE
[question] Why there is lag between replicas when leader node is powered off [DB is Idle]

### ISSUE THREAD

**Issue by venkat-jaligama** [zalando/postgres-operator#1632]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.7.0
v1.6.3

- ** Spilo Version
spilo-13:2.0-p7 

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
bare-metal

- **Are you running Postgres Operator in production?** [yes | no]
Yes
- **Type of issue?** [Bug report, question, feature request, etc.]
Question
We have a three node cluster with sync replication enabled. maximum_lag_on_failover was set to  339999
Leader election was failing while testing power off nodes.
Fixed it by bumping maximum_lag_on_failover to 349175808 (333MB)

Was seeing this error message
```
2021-10-01 00:18:02,740 INFO: My wal position exceeds maximum replication lag
2021-10-01 00:18:02,767 INFO: following a different leader because i am not the healthiest node
```
We were constantly seeing lag when leader node was powered off
```
patronictl list
+ Cluster: dcc-postgres-database (7013751324104368196) ----+----+-----------+
| Member                  | Host       | Role    | State   | TL | Lag in MB |
+-------------------------+------------+---------+---------+----+-----------+
| dcc-postgres-database-0 | 10.32.0.5  | Replica | running |  3 |        11 |
| dcc-postgres-database-1 | 10.47.0.12 | Replica | running |  3 |        11 |
| dcc-postgres-database-2 | 10.44.0.9  | Leader  | running |  4 |           |
+-------------------------+------------+---------+---------+----+-----------+
```
I am trying to Understand the following scenarios 
[1]Why is there lag when   DB is idle and nothing is being written to the DB
[2]And with the Sync Replication strict. It is assumed that all the data is replicated to at least one node.
[3]  With Sync Replication already in place, what is the use of the flag maximum_lag_on_failover
[4] Why low value of maximum_lag_on_failover caused leader election issue when Sync Replication is already enabled
[5] Is there a downside in using maximum_lag_on_failover to 349175808 (333MB) the example manifest has 33MB

Patroni Config
-**
```
patronictl show-config
loop_wait: 10
maximum_lag_on_failover: 335544320
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_statement: ddl
    log_temp_files: 0
    max_connections: '100'
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: true
ttl: 30

```
