### ISSUE TITLE
Issue creating Postgresql 14 cluster on minikube using repo example manifest

### ISSUE THREAD

**Issue by kbrady-servian** [zalando/postgres-operator#1658]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.7.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** metal. minikube
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

Hi,

I am following the quickstart guide here - https://postgres-operator.readthedocs.io/en/latest/quickstart/ - and using the `helm install postgres-operator ./charts/postgres-operator` install method. 
I have cloned this repo and am using a manifest stored within as a basis for testing - https://github.com/zalando/postgres-operator/blob/master/manifests/minimal-postgres-manifest.yaml

When using `spec.postgresql.version` with value `14` I get the following error:

```
The postgresql "my-minimal-cluster" is invalid: spec.postgresql.version: Unsupported value: "14": supported values: "9.3", "9.4", "9.5", "9.6", "10", "11", "12", "13"
```

Checking the logs of the operator, nothing looks to be generated by this event.

Using the UI to create the cluster, the page section `New cluster configuration` disappears, leaving a white blank space - no cluster is created.

This is the manifest I am using for testing:

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: my-minimal-cluster
  namespace: default
spec:
  teamId: "my_team"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    my_team_zalando:  # database owner
    - superuser
    - createdb
    my_team_user: []  # role for application foo
  databases:
    test: my_team_zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "14"
```

I am using minikube version v1.21.0 with the following start up command if it makes a difference 
`minikube start -p primary --memory 5Gi --vm=true`, running on on macOS 11.6 build 20G165.

A `spec.postgresql.version` value of `13` works and the cluster starts - am I missing some configuration?
With version `13` I cannot get it to back up to a local minikube hosted minio instance however - is S3 compatible support tied to the Postgresql version?

Thanks
