### ISSUE TITLE
How to stdout postgres logs?

### ISSUE THREAD

**Issue by sanketg86** [zalando/postgres-operator#1661]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.5.0
- **Where do you run it - cloud or metal?** Kubernetes  [GCP]
- **Are you running Postgres Operator in production?** yes 
- **Type of issue?** question

Could you please guide me how do I stdout postgres log from postgres container?
When Pod get restart all logs vanished. I want to stdout and see in google console logging instead of store on file-system path in csv file.

**Comment by FxKu** [comment]
Can be done with a sidecar, I think. We once used [scalyr](https://www.scalyr.com/) for this.

**Comment by skaffille** [comment]
Hi, what about logging to stderr instead of stdout with help of this in the cluster CRD?

```yaml
spec:
  postgresql:
    parameters:
      log_destination: stderr
      logging_collector: "off"
```

No sidecar needed ...
