### ISSUE TITLE
Documented link for Helm repo doesn't work

### ISSUE THREAD

**Issue by david-l-riley** [zalando/postgres-operator#1671]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** Any version
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Anything with Helm
- **Are you running Postgres Operator in production?** Not yet
- **Type of issue?** Docs/bug report

The published link for the Helm chart repository (https://opensource.zalando.com/postgres-operator/charts, which is published [here](https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#helm-chart)) gets a 404, perhaps due to a bug in the GH Pages export (I didn't dig into the Pages setup yet).  If I set up a Helm chart to pull from the published URL:

```yaml
  - name: postgres-operator
    version: ~v1.7.0
    repository: https://opensource.zalando.com/postgres-operator/charts
```

It cannot load `index.yaml` with `helm dep up`.  If, however, I specify the raw GH file location:

```yaml
  - name: postgres-operator
    version: ~v1.7.0
    repository: https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator
```

It works fine.
