### ISSUE TITLE
Question about creating secrets with credentials in other namespaces

### ISSUE THREAD

**Issue by juanmbellini** [zalando/postgres-operator#1684]
Hi!

This is sort of a question, and maybe a bug. I'm not quite sure. I'm trying the operator in Minikube (in an Intel Macbook Pro, using Hyperkit as hypervisor). The operator's version is 1.7.1

My question is about defining users in a different namespace than the one in which the cluster is created. When you define the user, you must add it in the manifest as the following:

```yaml
spec:
  users:
  #users with secret in dfferent namespace
   appspace.db_user:
    - createdb
```

What I'm seeing is that the created username is `appspace.db_user` instead of `db_user`. Is this the expected behavior? If yes, let me tell you that maybe you should include the following information when using this. When defining databases, the owner of it should also include the namespace, if not the operator will log that the user does not exists.

Thank you very much!
