### ISSUE TITLE
Cloning cluster from backup fails. No backups found

### ISSUE THREAD

**Issue by munjalpatel** [zalando/postgres-operator#1690]
- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.7.1`
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** `EKS`
- **Are you running Postgres Operator in production?** `no`
- **Type of issue?** `Bug report`

Hello, I am trying to `clone` a cluster from a `backup`. However, the clone cluster creation fails with these logs:
```
2021-11-16 04:37:43,277 - bootstrapping - INFO - Configuring crontab
2021-11-16 04:37:43,277 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2021-11-16 04:37:43,318 - bootstrapping - INFO - Configuring pgbouncer
2021-11-16 04:37:43,318 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2021-11-16 04:37:43,318 - bootstrapping - INFO - Configuring certificate
2021-11-16 04:37:43,318 - bootstrapping - INFO - Generating ssl self-signed certificate
2021-11-16 04:37:45,469 WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
2021-11-16 04:37:45,519 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-11-16 04:37:45,522 INFO: Lock owner: None; I am k-ct2-0
2021-11-16 04:37:45,700 INFO: trying to bootstrap a new cluster
2021-11-16 04:37:45,704 INFO: Running custom bootstrap script: envdir "/run/etc/wal-e.d/env-clone-k-test" python3 /scripts/clone_with_wale.py --recovery-target-time="2021-11-16T01:00:08.000+00:00"
2021-11-16 04:37:46,091 INFO: Trying s3://k-dev-zpo-wal-backups/spilo/k-test/8062378d-b4b1-4491-8bf3-a3289c93655a/wal/14/ for clone
INFO: 2021/11/16 04:37:46.357451 No backups found
```

I verified in `S3` that backups do exist. Also, they show up fine on the `UI`.
I clicked "Clone" button from the UI.

![image](https://user-images.githubusercontent.com/2717686/141922532-0a8da49f-9b25-464b-be33-76322e7f9a08.png)

**Comment by FxKu** [comment]
"No backups found" does not sound like a bug.

1. How is the operator [configured](No backups found)? 
2. How does the clone section in the manifest look like?

**Comment by munjalpatel** [comment]
@FxKu here are the details you have requested.

**Operator Configuration**
```yaml
apiVersion: acid.zalan.do/v1
kind: OperatorConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: zpo
    app.kubernetes.io/managed-by: pulumi
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-1.7.1
  name: zpo-postgres-operator
  namespace: zpo
configuration:
  aws_or_gcp:
    additional_secret_mount_path: /meta/credentials
    aws_region: us-west-2
    enable_ebs_gp3_migration: false
    enable_ebs_gp3_migration_max_size: 1000
    log_s3_bucket: k-dev-zpo-logs
    wal_s3_bucket: k-dev-zpo-wal-backups
  connection_pooler:
    connection_pooler_default_cpu_limit: '1'
    connection_pooler_default_cpu_request: 500m
    connection_pooler_default_memory_limit: 100Mi
    connection_pooler_default_memory_request: 100Mi
    connection_pooler_image: 'registry.opensource.zalan.do/acid/pgbouncer:master-19'
    connection_pooler_max_db_connections: 60
    connection_pooler_mode: transaction
    connection_pooler_number_of_instances: 2
    connection_pooler_schema: pooler
    connection_pooler_user: pooler
  debug:
    debug_logging: true
    enable_database_access: true
  docker_image: 'registry.opensource.zalan.do/acid/spilo-14:2.1-p3'
  enable_crd_validation: true
  enable_lazy_spilo_upgrade: false
  enable_pgversion_env_var: true
  enable_shm_volume: true
  enable_spilo_wal_path_compat: false
  etcd_host: ''
  kubernetes:
    cluster_domain: cluster.local
    cluster_labels:
      app: spilo
      application: spilo
    cluster_name_label: kdb
    enable_cross_namespace_secret: false
    enable_init_containers: true
    enable_pod_antiaffinity: true
    enable_pod_disruption_budget: true
    enable_sidecars: true
    master_pod_move_timeout: 20m
    oauth_token_secret_name: zpo-postgres-operator
    pdb_name_format: 'postgres-{cluster}-pdb'
    pod_antiaffinity_topology_key: kubernetes.io/hostname
    pod_environment_secret: k-db-pod-secrets
    pod_management_policy: ordered_ready
    pod_role_label: spilo-role
    pod_service_account_definition: ''
    pod_service_account_name: postgres-pod
    pod_service_account_role_binding_definition: ''
    pod_terminate_grace_period: 5m
    secret_name_template: '{username}.{cluster}.credentials.{tprkind}.{tprgroup}'
    spilo_allow_privilege_escalation: true
    spilo_privileged: false
    storage_resize_mode: pvc
    toleration:
      effect: NoSchedule
      key: k-db
      operator: Exists
    watched_namespace: k-db
  kubernetes_use_configmaps: false
  load_balancer:
    db_hosted_zone: db.example.com
    enable_master_load_balancer: false
    enable_replica_load_balancer: false
    external_traffic_policy: Cluster
    master_dns_name_format: '{cluster}.{team}.{hostedzone}'
    replica_dns_name_format: '{cluster}-repl.{team}.{hostedzone}'
  logging_rest_api:
    api_port: 8080
    cluster_history_entries: 1000
    ring_log_lines: 100
  logical_backup:
    logical_backup_docker_image: 'registry.opensource.zalan.do/acid/logical-backup:v1.7.1'
    logical_backup_job_prefix: logical-backup-
    logical_backup_provider: s3
    logical_backup_s3_access_key_id: ''
    logical_backup_s3_bucket: my-bucket-url
    logical_backup_s3_endpoint: ''
    logical_backup_s3_region: ''
    logical_backup_s3_secret_access_key: ''
    logical_backup_s3_sse: AES256
    logical_backup_schedule: 30 00 * * *
  major_version_upgrade:
    major_version_upgrade_mode: manual
    minimal_major_version: '9.6'
    target_major_version: '14'
  max_instances: -1
  min_instances: -1
  postgres_pod_resources:
    default_cpu_limit: '1'
    default_cpu_request: 100m
    default_memory_limit: 500Mi
    default_memory_request: 100Mi
    min_cpu_limit: 250m
    min_memory_limit: 250Mi
  repair_period: 5m
  resync_period: 30m
  set_memory_request_to_limit: false
  teams_api:
    enable_admin_role_for_users: true
    enable_postgres_team_crd: false
    enable_postgres_team_crd_superusers: false
    enable_team_member_deprecation: false
    enable_team_superuser: false
    enable_teams_api: false
    pam_configuration: >-
      https://info.example.com/oauth2/tokeninfo?access_token= uid
      realm=/employees
    pam_role_name: zalandos
    postgres_superuser_teams:
      - postgres_superusers
    protected_role_names:
      - admin
    role_deletion_suffix: _deleted
    team_admin_role: admin
    team_api_role_configuration:
      log_statement: all
    teams_api_url: 'https://teams.example.com/api/'
  timeouts:
    pod_deletion_wait_timeout: 10m
    pod_label_wait_timeout: 10m
    ready_wait_interval: 3s
    ready_wait_timeout: 30s
    resource_check_interval: 3s
    resource_check_timeout: 10m
  users:
    replication_username: standby
    super_username: postgres
  workers: 8
```

**Clone Cluster Configuration**
```
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "k-clone-test"
  namespace: "k-db"
  labels:
    team: k

spec:
  teamId: "k"
  postgresql:
    version: "14"
  numberOfInstances: 1
  volume:
    size: "10Gi"


  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi

  clone:
    cluster: "k-test"
    uid: "8062378d-b4b1-4491-8bf3-a3289c93655a"
    timestamp: "2021-11-16T13:14:09.000+00:00"
```
