### ISSUE TITLE
In Openshift, endpoints is forbidden

### ISSUE THREAD

**Issue by Samusername** [zalando/postgres-operator#1702]
Hi!

I tested with older versions of postgres-operator and spilo,
and also with latest published versions:
https://github.com/zalando/postgres-operator/releases/tag/v1.7.1
and --> registry.opensource.zalan.do/acid/spilo-14:2.1-p3

Following kinds of errors are shown in logs of acid-upgrade-test-0 pod:

patroni.dcs.kubernetes.K8sClient.rest.ApiException: (403)
Reason: Forbidden

**endpoints** "acid-upgrade-test" is forbidden: endpoint address ... is not allowed",
"reason":"Forbidden","details":{"name":\\"acid-upgrade-test\\","kind":"endpoints"},"code":403}
...
2021-11-23 14:40:39,183 ERROR: failed to update leader lock
2021-11-23 14:40:39,184 INFO: not promoting because failed to update leader lock in DCS

I have seen e.g. following discussion chain:
https://github.com/zalando/postgres-operator/issues/985
I tried to compare and add any permissions which were mentioned there.
Same error happened still.

What kinds of permissions should be given? In ClusterRole?

Btw., is config map needed to be enabled separately nowadays in these installations to Openshift? I did not set it anywhere.

Files:

I used following minimal manifest yaml:

<details>
  <summary>Click to expand!</summary>
  
  ## minimal manifest yaml
  ```
  apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-upgrade-test
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "13"
```
</details>

I will need to make one scratch installation test again from a "clean table".

**Comment by CyberDem0n** [comment]
For openshift you have to use configmaps instead of endpoints.

**Comment by FxKu** [comment]
@Samusername have a look at the [RBAC template](https://github.com/zalando/postgres-operator/blob/a6d4f23f90fe12822a19e758ff400233c9212e00/charts/postgres-operator/templates/clusterrole-postgres-pod.yaml#L13) of the helm chart to understand how the cluster role should look like

**Comment by Samusername** [comment]
> @Samusername have a look at the [RBAC template](https://github.com/zalando/postgres-operator/blob/a6d4f23f90fe12822a19e758ff400233c9212e00/charts/postgres-operator/templates/clusterrole-postgres-pod.yaml#L13) of the helm chart to understand how the cluster role should look like

Yes, I have used the same ClusterRole definitions (and the whole helm chart) from there, in this latest test.

(I did not bind it, if it does not get bound automatically in the installation of the helm chart.)

**Comment by Samusername** [comment]
I am trying to avoid "ConfigMap configuration": 
including kubernetes_use_configmaps: true and configTarget: "ConfigMap". 
( Which is becoming deprecated. )
When I refer to "ConfigMap" configuration, I refer to those.

So, following was kept in comments, in values.yaml:

\# kubernetes_use_configmaps: false

With configTarget: "OperatorConfigurationCRD",
Following kind of request is problematic in Openshift, when DB cluster starts up:

```
PATCH   https://<x.y.z.w:port>/api/v1/namespaces/default/endpoints/acid-upgrade-test
add /subnets addresses: ip: "x1.y1.z1.v1"
--> endpoints "acid-upgrade-test" is forbidden: endpoint address ... is not allowed
```

**If we manage to get enough permissions** to get such executed in Openshift:

> Are there some other reasons (problems) why "ConfigMap configuration" should be used instead of CRDs?
> 
> Or are we "free" to go with the CRD ("OperatorConfigurationCRD") configuration, in Openshift, then otherwise?

**Comment by FxKu** [comment]
It was fixed now with #1760 and #1825 and will be included in the next release this week.

**Comment by davtex** [comment]
As this is this the first result for searching "endpoint address is not allowed", I will add one other possible solution that may help people dealing with same issue on other operators such as k8ssandra-operator:

You need to modify Role/Clusterrole and use resource "endpoints/restricted" instead of "endpoints", like this:
```
- apiGroups:
  - ""
  resources:
  - endpoints
  - endpoints/restricted
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
 ```

This quirk is only documented in legacy Openshift 3.X documentation here:
https://docs.openshift.com/container-platform/3.3/architecture/core_concepts/pods_and_services.html#endpoints

Verified to work on Openshift 4.11

**Comment by schedin** [comment]
Thank you @davtex for your helpful comment! I had the same problem in OpenShift 4.17, but for an EndpointSlice. I'm posting my corresponding Role that solved my case:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-endpointslices-restricted-role
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices", "endpointslices/restricted"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

```
