### ISSUE TITLE
Default privileges failed on cluster create for postgresql 9.*

### ISSUE THREAD

**Issue by halvaborsch** [zalando/postgres-operator#1714]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Where do you run it - Kubernetes or OpenShift?** k8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

Deploing manifest with:

```
  postgresql:
    parameters:
    version: "9.6"
  preparedDatabases:
    user_database:
      extensions:
        amcheck_next: public
        pg_repack: public
        pgcrypto: public
      schemas:
        public:
          defaultRoles: false
```

The Global Default privileges are not created in the public schema with error message:
```
level=error msg="could not create cluster: could not sync databases: could not alter default privileges for database user_database: pq: syntax error at or near \"SCHEMAS\"" cluster-name=io/user_databse_name_db9 pkg=controller worker=0
```
https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/database.go#L43 

Seems like postgresql before 10 major release cannot use `GRANT <something> ON SCHEMAS` command.

Any thoughts?
