### ISSUE TITLE
With storage_resize_mode: pvc, updated StatefulSet has wrong PVC name

### ISSUE THREAD

**Issue by blakebarnett** [zalando/postgres-operator#1719]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
v1.7.1

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
k8s kind cluster with rancher local-path-storage

- **Are you running Postgres Operator in production?** [yes | no]
yes

- **Type of issue?** [Bug report, question, feature request, etc.]
Bug

When attempting a PVC resize with the `storage_mode_resize: pvc` set in the operator configuration, I see the updates happen, but the updated statefulSet ends up with a volumeClaimTemplate stuck like this:

```
   volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          volume.alpha.kubernetes.io/storage-class: default
        creationTimestamp: null
        name: pgdata
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        volumeMode: Filesystem
      status:
        phase: Pending
```

I believe the `name` should be `pgdata-<CLUSTER NAME>-[0..n]`? That is what the current PVC is named.
