### ISSUE TITLE
Feature Request: Non-Privilege-Escalation Support for Certificate Rotation & Backups

### ISSUE THREAD

**Issue by haslersn** [zalando/postgres-operator#1730]
Feature request: Support certificate rotation & backups without privilege escalation.

According to [this documentation](https://github.com/zalando/postgres-operator/blob/3e275d122a54fbf17c40db9564f762ea0754b61c/docs/reference/operator_parameters.md#kubernetes-resources), enabling `spilo_allow_privilege_escalation` is required for certificate rotation & backups to work. However, this breaks those features when running under the Restricted policy of [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) where privilege escalation must not be enabled. Therefore I request those features to work without privilege escalation.

**Workaround**

Currently the following (**more insecure**) workaround is required in every namespace where a PostgreSQL cluster is deployed (the non-namespaced `ClusterRole` is of course only needed once).

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-baseline
rules:
  - apiGroups: [policy]
    resources: [podsecuritypolicies]
    verbs: [use]
    resourceNames: [baseline]

---
# Workaround for https://github.com/zalando/postgres-operator/issues/1730
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-baseline
roleRef:
  kind: ClusterRole
  name: psp-baseline
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    # Match all ServiceAccounts in this namespace. ServiceAccounts in other
    # namespaces are not affected, because this is a (namespaced) RoleBinding.
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
```
