### ISSUE TITLE
SIGSEGV - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mdavidsen** [zalando/postgres-operator#1732]
Running operator 1.6.3, the operator crashed when I added a badly named Postgresql resource.

It does not end up in a restart loop so it's "Just" a restart of the pod. I'm not sure if I'm able to reproduce, but hopefully someone are able to pinpoint the location of this bug. 

```
time="2022-01-05T14:23:19Z" level=debug msg="skipping \"ADD\" event for the invalid cluster: name must match {TEAM}-{NAME} format" cluster-name=team-pgsupport-<customer>/<customer>-pgsupport-reactor-db pkg=controller
time="2022-01-05T14:23:19Z" level=error msg="could not get reference for Postgresql CR reactor-pgsupport-<customer>/<customer>-pgsupport-reactor-db: no kind is registered for the type v1.Postgresql in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:72\"" pkg=controller
E0105 14:23:19.878040       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 26 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1bdf240, 0x2e0a220)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1bdf240, 0x2e0a220)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/client-go/tools/record.(*recorderImpl).makeEvent(0xc00009e000, 0x0, 0x0, 0x1e79577, 0x7, 0x1e778d9, 0x6, 0xc001276660, 0x24, 0xc033be4ade)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:362 +0x51
k8s.io/client-go/tools/record.(*recorderImpl).generateEvent(0xc00009e000, 0x21589e0, 0x0, 0x0, 0xc06d8855f3be4ade, 0x719706e034fad, 0x2e2e8c0, 0x1e79577, 0x7, 0x1e778d9, ...)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:338 +0x359
k8s.io/client-go/tools/record.(*recorderImpl).Event(0xc00009e000, 0x21589e0, 0x0, 0x1e79577, 0x7, 0x1e778d9, 0x6, 0xc001276660, 0x24)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:349 +0xc5
k8s.io/client-go/tools/record.(*recorderImpl).Eventf(0xc00009e000, 0x21589e0, 0x0, 0x1e79577, 0x7, 0x1e778d9, 0x6, 0x1e74eae, 0x2, 0xc000698a60, ...)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:353 +0xca
github.com/zalando/postgres-operator/pkg/controller.(*Controller).queueClusterEvent(0xc0000ea380, 0x0, 0xc000e70c00, 0x1e752ca, 0x3)
	/workspace/pkg/controller/postgresql.go:446 +0x70a
github.com/zalando/postgres-operator/pkg/controller.(*Controller).postgresqlAdd(0xc0000ea380, 0x1e38600, 0xc000e70c00)
	/workspace/pkg/controller/postgresql.go:506 +0x85
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/workspace/vendor/k8s.io/client-go/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000297760)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000607f60, 0x2148560, 0xc00062c2a0, 0x1b8c201, 0xc0006320c0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000297760, 0x3b9aca00, 0x0, 0x1, 0xc0006320c0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000166000)
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000222060, 0xc00062e2d0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18c0711]

goroutine 26 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1bdf240, 0x2e0a220)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/client-go/tools/record.(*recorderImpl).makeEvent(0xc00009e000, 0x0, 0x0, 0x1e79577, 0x7, 0x1e778d9, 0x6, 0xc001276660, 0x24, 0xc033be4ade)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:362 +0x51
k8s.io/client-go/tools/record.(*recorderImpl).generateEvent(0xc00009e000, 0x21589e0, 0x0, 0x0, 0xc06d8855f3be4ade, 0x719706e034fad, 0x2e2e8c0, 0x1e79577, 0x7, 0x1e778d9, ...)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:338 +0x359
k8s.io/client-go/tools/record.(*recorderImpl).Event(0xc00009e000, 0x21589e0, 0x0, 0x1e79577, 0x7, 0x1e778d9, 0x6, 0xc001276660, 0x24)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:349 +0xc5
k8s.io/client-go/tools/record.(*recorderImpl).Eventf(0xc00009e000, 0x21589e0, 0x0, 0x1e79577, 0x7, 0x1e778d9, 0x6, 0x1e74eae, 0x2, 0xc000698a60, ...)
	/workspace/vendor/k8s.io/client-go/tools/record/event.go:353 +0xca
github.com/zalando/postgres-operator/pkg/controller.(*Controller).queueClusterEvent(0xc0000ea380, 0x0, 0xc000e70c00, 0x1e752ca, 0x3)
	/workspace/pkg/controller/postgresql.go:446 +0x70a
github.com/zalando/postgres-operator/pkg/controller.(*Controller).postgresqlAdd(0xc0000ea380, 0x1e38600, 0xc000e70c00)
	/workspace/pkg/controller/postgresql.go:506 +0x85
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/workspace/vendor/k8s.io/client-go/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000297760)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000607f60, 0x2148560, 0xc00062c2a0, 0x1b8c201, 0xc0006320c0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000297760, 0x3b9aca00, 0x0, 0x1, 0xc0006320c0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000166000)
	/workspace/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000222060, 0xc00062e2d0)
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x65
``` 

Postgresql manifest:
```
# Source: reactor/templates/database.yml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: customer-pgsupport-reactor-db
  labels:
    helm.sh/chart: reactor-0.1.0
    app.kubernetes.io/name: reactor
    app.kubernetes.io/instance: customer-pgsupport
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    reactor.dev/model: sandbox
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
spec:
  teamId: "reactor"
  podAnnotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    reactor: []
  databases:
    reactor: reactor
  postgresql:
    version: "13"
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 1Gi
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: workload
          operator: In
          values:
          - storage
  sidecars:
    - name: "postgres-exporter"
      image: "quay.io/prometheuscommunity/postgres-exporter:v0.10.0"
      env:
        - name: DATA_SOURCE_USER
          value: postgres
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres.customer-pgsupport-reactor-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: DATA_SOURCE_URI
          value: "127.0.0.1:5432/postgres?sslmode=require"
```

**Comment by FxKu** [comment]
Do you also want to share your badly named resource / postgres manifest to allow us to reproduce?

**Comment by mdavidsen** [comment]
Hi,

Yes, sorry about that. Had about a 100 other things, and just needed to create this so i would remember. Here's the manifest used to create the badly named resource. 

`time="2022-01-05T14:23:19Z" level=debug msg="skipping \"ADD\" event for the invalid cluster: name must match {TEAM}-{NAME} format" cluster-name=team-pgsupport-<customer>/<customer>-pgsupport-reactor-db pkg=controller` is the validation error that's outputed by the controller. 

```
# Source: reactor/templates/database.yml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: customer-pgsupport-reactor-db
  labels:
    helm.sh/chart: reactor-0.1.0
    app.kubernetes.io/name: reactor
    app.kubernetes.io/instance: customer-pgsupport
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    reactor.dev/model: sandbox
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
spec:
  teamId: "reactor"
  podAnnotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    reactor: []
  databases:
    reactor: reactor
  postgresql:
    version: "13"
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 1Gi
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: workload
          operator: In
          values:
          - storage
  sidecars:
    - name: "postgres-exporter"
      image: "quay.io/prometheuscommunity/postgres-exporter:v0.10.0"
      env:
        - name: DATA_SOURCE_USER
          value: postgres
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres.customer-pgsupport-reactor-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: DATA_SOURCE_URI
          value: "127.0.0.1:5432/postgres?sslmode=require"
```
