### ISSUE TITLE
syntax error at or near "-"

### ISSUE THREAD

**Issue by Mercbot7** [zalando/postgres-operator#1741]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**
--  registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
-- AWS k8s, helm chart
- **Are you running Postgres Operator in production?**
-- yes
- **Type of issue?** [Bug report, question, feature request, etc.]
-- bug report

We are trying to upgrade from operator 1.6.0 --> 1.7.1. It is failing to  update the poolers with this error:

```
could not execute after retries

        CREATE SCHEMA IF NOT EXISTS pooler;
        
        CREATE OR REPLACE FUNCTION pooler.user_lookup(
        in i_username text, out uname text, out phash text)
        RETURNS record AS $$
        BEGIN
        SELECT usename, passwd FROM pg_catalog.pg_shadow
        WHERE usename = i_username INTO uname, phash;
            RETURN;
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER;
        
        REVOKE ALL ON FUNCTION pooler.user_lookup(text)
            FROM public, gitlab-user;
        GRANT EXECUTE ON FUNCTION pooler.user_lookup(text)
            TO gitlab-user;
        GRANT USAGE ON SCHEMA pooler TO gitlab-user;
    
    : pq: syntax error at or near \"-\"" cluster-name=gitlab/gitlab-postgres-cluster pkg=clustertime="2022-01-11T21:21:10Z" level=info msg="install pooler lookup function into database 'gitlab'" cluster-name=gitlab/gitlab-postgres-cluster pkg=cluster
```

our DB manifest looks like this:

```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: gitlab-postgres-cluster
  namespace: gitlab
spec:
  teamId: gitlab
  volume:
    size: 10Gi
  numberOfInstances: 3
  users:
    gitlab-user:
      - superuser
      - createdb
  databases:
    gitlab: gitlab-user
  enableLogicalBackup: true
  postgresql:
    version: "13"
  connectionPooler:
    user: "gitlab-user"
```
it looks like the dash in the user name may be the culprit and perhaps quoting the username in the call would resolve this issue?

https://github.com/zalando/postgres-operator/blob/b4155bc8fb468590677fb1e808708884d744d694/pkg/cluster/database.go#L59-L76

IF the username cannot have a "-" is there a way to migrate away from that user and create a new one? This user is the DBOwner.
