### ISSUE TITLE
inherited_annotations not passed to PVC

### ISSUE THREAD

**Issue by bchrobot** [zalando/postgres-operator#1754]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.7.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** GKE
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

We are trying to use [`pvc-autoresizer`](https://github.com/topolvm/pvc-autoresizer/) and need to pass the following types of annotations to the data PVCs:

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-mypostgres-cluster
  annotations:
    "resize.topolvm.io/storage_limit": "100Gi"
    "resize.topolvm.io/threshold": "20%"
    "resize.topolvm.io/increase": "10Gi"
```

However, the only annotation that gets set for data PVCs, regardless of `inherited_annotations`, is the storage class. See:

https://github.com/zalando/postgres-operator/blob/def9e1d6884ba6d60d511c1b913a5bed7a0ef1d2/pkg/cluster/k8sres.go#L1534-L1544

It looks like [`annotationsSet()`](https://github.com/zalando/postgres-operator/blob/07fd4ec00bad302864330958a6fa691d9e12eed4/pkg/cluster/util.go#L290) could be used to add the desired annotations to the volume claim template.

I'm happy to open a PR for this but hoped to get some guidance on which approach is preferred:
1. Modify [`generatePersistentVolumeClaimTemplate()`](https://github.com/zalando/postgres-operator/blob/def9e1d6884ba6d60d511c1b913a5bed7a0ef1d2/pkg/cluster/k8sres.go#L1529) to take a `Cluster` receiver and remodel after [`generatePodTemplate()`](https://github.com/zalando/postgres-operator/blob/def9e1d6884ba6d60d511c1b913a5bed7a0ef1d2/pkg/cluster/k8sres.go#L580), or
2. Modify/overwrite the annotations property of [the returned `volumeClaimTemplate`](https://github.com/zalando/postgres-operator/blob/def9e1d6884ba6d60d511c1b913a5bed7a0ef1d2/pkg/cluster/k8sres.go#L1280-L1283), leaving `generatePersistentVolumeClaimTemplate()` untouched
