### ISSUE TITLE
How to get get the pvc to pick the desired storageclass 

### ISSUE THREAD

**Issue by Leke-Ariyo** [zalando/postgres-operator#1761]
Relevant information to better answer the questions
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- registry.opensource.zalan.do/acid/postgres-operator:v1.7.1

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
- I am not running it on ther cloud and I use Kubernetes

- **Are you running Postgres Operator in production?** [yes | no]
- Not on production currently

- **Type of issue?** [Bug report, question, feature request, etc.]
- It is a question.

pvc is pending with the same ```storageclass.storage.k8s.io "encryptedgp2" not found``` status 
meanwhile yaml has been updated to use default ```rook-ceph-block```

I did overide the storage class to be used in my postgres.yaml as was suggested here https://github.com/zalando/postgres-operator/issues/1487#issuecomment-855370660 but it seemed to have not picked the desired storageclass 

**Question is How do I get the pvc created to pick the desired sc**

This is how my postgres.yaml looks:

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: posgresql
  namespace: sonarqube
spec:
  teamId: example
  volume:
    storageClass: rook-ceph-block
    size: 2Gi
  numberOfInstances: 1
  users:
    owner:  
    - superuser
    postgres:
    - login
    sonarqube:
    - login
  databases:
    postgresql: owner  
  postgresql:
    version: "12"
  enableMasterLoadBalancer: false
```

The pvc provisioned still picks the storageclass ```encryptedgp2``` instead of ```rook-ceph-block``` - which is the default storage class confirmed in the annotation
