### ISSUE TITLE
Infrastructure roles via zalando/postgres-operator do not create the required roles as per the documentation.

### ISSUE THREAD

**Issue by Sudeepta92** [zalando/postgres-operator#1764]
Firstly, is there is anyone who can provide a working step by step instruction for this topic?

I have tried creating infrastructure roles in both ways mentioned in the document and none seem to ahve worked.

1. With the infrastructure roles secret only
2. With both the the secret and the infrastructure role ConfigMap.

Method 1-The manifests used:

Secret:
`apiVersion: v1
kind: Secret
metadata:
  name: postgresbackup-infrastructure-roles
  namespace: zalando
data:
  user1: YmFja3VwX3VzZXI=
  # backup_user
  password1: c2VjcmV0
  # secret
  inrole1: b3BlcmF0b3I=
  # operator`

Operatorconfiguration:
`apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-configuration
  namespace: zalando
configuration:
  kubernetes:
    infrastructure_roles_secrets:
    - secretname: "postgresbackup-infrastructure-roles"
      userkey: "user1"
      passwordkey: "password1"
      rolekey: "inrole1"`

Method 2-The manifests used:
Secret:
`apiVersion: v1
data:
  # required format (w/o quotes): 'propertyNumber: value'
  # allowed properties: 'user', 'password', 'inrole'
  # numbers >= 1 are mandatory
  # alternatively, supply the user: password pairs and
  # provide other options in the configmap.
  # robot_zmon_acid_monitoring
  user1: cm9ib3Rfem1vbl9hY2lkX21vbml0b3Jpbmc=
  # foobar
  password1: Zm9vYmFy
  # robot_zmon
  inrole1: cm9ib3Rfem1vbg==
  # testuser
  user2: dGVzdHVzZXI=
  # testpassword
  password2: dGVzdHBhc3N3b3Jk
  # user batman with the password justice
  # look for other fields in the infrastructure roles configmap
  batman: anVzdGljZQ==
kind: Secret
metadata:
  name: postgresql-infrastructure-roles
  namespace: default
type: Opaque`

Configmap:
`apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-infrastructure-roles
data:
  batman: |
    inrole: [admin]  # following roles will be assigned to the new user
    user_flags:
      - createdb
    db_parameters:  # db parameters, applied for this particular user
      log_statement: all`

I also created pacthes for both methods- for operatorconfiguration and configmap so as to set the pod envrionment, like:
`apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
data:
  pod_environment_configmap: "zalando/postgresql-infrastructure-roles"`

**Comment by JuanRamino** [comment]
Could you please provide a valid example on how to create an infrastructure role with the combination of Secret, ConfigMap and OperatorConfiguration?

Thanks

**Comment by FactorT** [comment]
I had same problem.
And this works for me only in old style like:
CRD:
```
apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-default-configuration
configuration:
...
    infrastructure_roles_secret_name: "postgresql-infrastructure-roles"
...
```
Secret:
```
apiVersion: v1
stringData:
  user1: monuser
  password1: pass
  inrole1: pg_monitor
kind: Secret
metadata:
  name: postgresql-infrastructure-roles
  namespace: test
type: Opaque
```

**Comment by tolikkostin** [comment]
I have the same issue. For me only old method works - specifying infrastructure role through CRD config by **`infrastructure_roles_secret_name`** parameter. 
``` yaml
apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-configuration
configuration:
  kubernetes:
    infrastructure_roles_secret_name: "postgresql-infrastructure-roles"
...
```
