### ISSUE TITLE
archive_command set to `/bin/true` instead of expected `wal-g`

### ISSUE THREAD

**Issue by ibotty** [zalando/postgres-operator#1772]
- **Which image of the operator are you using?**
registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
 
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** 
OpenShift

- **Are you running Postgres Operator in production?**
yes

- **Type of issue?**
Bug Report

The `archive_command` is set to `/bin/true` even though `envdir /meta/credentials /scripts/postgres_backup.sh /home/postgres/pgdata/pgroot/data/` runs correctly.

The `OperatorConfiguration` includes the following settings:
```
  aws_or_gcp:
    additional_secret_mount: s3-bucket-env
    additional_secret_mount_path: /meta/credentials
    aws_region: de
  kubernetes:
    pod_environment_secret: s3-bucket-env
  kubernetes_use_configmaps: true
```

The `s3-bucket-env` secret in the right namespace looks like
```
==> AWS_ACCESS_KEY_ID <==
[redacted]
==> AWS_ENDPOINT <==
https://[redacted]
==> AWS_REGION <==
de
==> AWS_S3_FORCE_PATH_STYLE <==
true
==> AWS_SECRET_ACCESS_KEY <==
[redacted]
==> BACKUP_NUM_TO_RETAIN <==
30
==> BACKUP_SCHEDULE <==
0 */12 * * *
==> USE_WALG_BACKUP <==
true
==> USE_WALG_RESTORE <==
true
==> WAL_BUCKET_SCOPE_PREFIX <==

==> WALG_COMPRESSION_METHOD <==
brotli
==> WALG_LIBSODIUM_KEY <==
[redacted]
==> WALG_LIBSODIUM_KEY_TRANSFORM <==
hex
==> WALG_S3_PREFIX <==
s3://[redacted]/[redacted]
==> WAL_S3_BUCKET <==
[redacted]
```

The `postgresql` instance is as follows:
```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: [redacted]
  name: [redacted]-[redacted]
spec:
  numberOfInstances: 2
  dockerImage: image-registry.openshift-image-registry.svc:5000/db/spilo-citus@sha256:71608859830861078692af5120e2d2aaad53f8543aecb1820b00f2493a41e825
  numberOfInstances: 2
  postgresql:
    parameters:
      shared_preload_libraries: citus,pg_stat_statements
    version: "14"
  preparedDatabases:
    [redacted]-[redacted]:
      defaultUsers: true
      extensions:
        citus: pg_catalog
        first_last_agg: public
        pg_stat_statements: public
        pgcrypto: public
  teamId: [redacted]
  volume:
    size: 100Gi
    storageClass: local-nvme-fs
status:
  PostgresClusterStatus: Running
```

Am I missing anything?  The environment-secret was added to the operatorconfig after creating the cluster.
