### ISSUE TITLE
Supporting HPA for Zalando postgres

### ISSUE THREAD

**Issue by kannanvr** [zalando/postgres-operator#1790]
Hi,
   We can eaily support the HPA by adding few parameters on CRD.

```
subresources:
  status: {}
  scale:
    labelSelectorPath: .status.selector
    specReplicasPath: .spec.numberOfInstances
    statusReplicasPath: .status.replicas
```

- **Which image of the operator are you using?** -  registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** K8s
- **Are you running Postgres Operator in production?** yes 
- **Type of issue?** feature request

we can scale Up the postgres CRD based on the number of Read Request and so on...

Thanks,
Kannan V
