### ISSUE TITLE
Listing backups using environment variable fails.

### ISSUE THREAD

**Issue by Sudeepta92** [zalando/postgres-operator#1800]
On using the aws endpoint the backups can be listed out. But the backups can't be listed at the moment using the env command: **"envdir /run/etc/wal-e.d/env" wal-g backup-list**  

The configmap used:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
  namespace: zalando-postgres-operator
data: 
  AWS_ACCESS_KEY_ID: "8SCXHY2RNGWIF0KOI3TI"
  AWS_SECRET_ACCESS_KEY: "ZerxO/CuV4zsSlMaAqHMW/D9GrRF+xFKVpJj4WGu"
  AWS_ENDPOINT: "https://postgresql-dev.object.storage.eu01.onstackit.cloud"
  AWS_REGION: "eu01"
  AWS_S3_FORCE_PATH_STYLE: "true"
  pod_environment_secret: "scheduler-secret"
  pod_environment_configmap: "zalando-postgres-operator/postgres-operator"
  WALG_DISABLE_S3_SSE: "true"
  WAL_S3_BUCKET: "postgresql-dev"
  resync_period: 30s
  USE_WALG_BACKUP: "true"
  BACKUP_SCHEDULE: "0 1 * * *"  
  BACKUP_NUM_TO_RETAIN: "5"
```

**Comment by FxKu** [comment]
You need two config maps. Read the docs again:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
  namespace: zalando-postgres-operator
data:
  pod_environment_configmap: "zalando-postgres-operator/extra-config"
  ...

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-config
  namespace: zalando-postgres-operator
data:
  AWS_ACCESS_KEY_ID: "8SCXHY2RNGWIF0KOI3TI"
  AWS_SECRET_ACCESS_KEY: "ZerxO/CuV4zsSlMaAqHMW/D9GrRF+xFKVpJj4WGu"
  AWS_ENDPOINT: "https://postgresql-dev.object.storage.eu01.onstackit.cloud"
  AWS_REGION: "eu01"
  AWS_S3_FORCE_PATH_STYLE: "true"
  WALG_DISABLE_S3_SSE: "true"
  WAL_S3_BUCKET: "postgresql-dev"
  USE_WALG_BACKUP: "true"
  BACKUP_SCHEDULE: "0 1 * * *"  
  BACKUP_NUM_TO_RETAIN: "5"
```

Same for pod_environment_secret. Would also say that `resync_period: 30s` is too frequent.
