### ISSUE TITLE
Postgres operator doesn't place the user secrets in the defined namespace

### ISSUE THREAD

**Issue by caniko** [zalando/postgres-operator#1827]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | **Bare Metal K8s**]
- **Are you running Postgres Operator in production?** [yes | **no**]
- **Type of issue?** [**Bug** report, question, feature request, etc.]

`fastapi.fastapi-postgres.core-postgres-cluster.credentials.postgresql.acid.zalan.do` has to be in `fastapi`. `enable_cross_namespace_secret` is set to true. Please see below.

My `postgres-operator` config:
```yaml
configKubernetes:
  custom_pod_annotations:
    enable_cross_namespace_secret: "true"
    consul.hashicorp.com/connect-inject: "true"
```
My manifest:
```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: core-postgres-cluster
  namespace: ${var.cluster_namespace}
  labels:
    app: postgres
spec:
  teamId: core
  volume:
    size: ${var.postgres_size}
    storageClass: ${var.storage_class_name}
  numberOfInstances: ${var.postgres_workers}
  users:
    admin:  # database owner
      - superuser
      - createdb
    fastapi.fastapi_postgres:
      - createdb
    hashi:
      - createdb
  databases:
    syndb_users: fastapi.fastapi_postgres
    hashi-vault: hashi
  postgresql:
    version: "14"
```

`kubectl -n postgres get secrets`:
```shell
NAME                                                                                  TYPE                                  DATA   AGE
default-token-8rfvg                                                                   kubernetes.io/service-account-token   3      2m15s
fastapi.fastapi-postgres.core-postgres-cluster.credentials.postgresql.acid.zalan.do   Opaque                                2      69s
hashi.core-postgres-cluster.credentials.postgresql.acid.zalan.do                      Opaque                                2      69s
postgres-operator-token-b6jpd                                                         kubernetes.io/service-account-token   3      2m3s
postgres-operator-ui-token-b9f6z                                                      kubernetes.io/service-account-token   3      76s
postgres-pod-token-8whsm                                                              kubernetes.io/service-account-token   3      69s
postgres.core-postgres-cluster.credentials.postgresql.acid.zalan.do                   Opaque                                2      69s
sh.helm.release.v1.postgres-operator-ui.v1                                            helm.sh/release.v1                    1      76s
sh.helm.release.v1.postgres-operator.v1                                               helm.sh/release.v1                    1      2m3s
standby.core-postgres-cluster.credentials.postgresql.acid.zalan.do                    Opaque                                2      69s
```
`kubectl -n fastapi get secrets`:
```shell
NAME                  TYPE                                  DATA   AGE
default-token-l5bt2   kubernetes.io/service-account-token   3      16m
```
