### ISSUE TITLE
S3 backup fails due to missing region

### ISSUE THREAD

**Issue by ClaudiuLSH** [zalando/postgres-operator#1840]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.7.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug

Helm custom values:
```
configAwsOrGcp:
  aws_region: us-east-1
  wal_s3_bucket: postgres-backup
configKubernetes:
  pod_environment_configmap: postgresql-pod-environment
```
`postgresql-pod-environment` config map:
```
data:
  AWS_ACCESS_KEY_ID: ***
  AWS_ENDPOINT: http://***
  AWS_REGION: us-east-1
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_SECRET_ACCESS_KEY: ***
  BACKUP_NUM_TO_RETAIN: "30"
  BACKUP_SCHEDULE: 0 02 * * *
  USE_WAL_BACKUP: "true"
  WAL_S3_BUCKET: postgres-backup
  WALG_DISABLE_S3_SSE: "true"
```

Backup fails with:
```
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
        <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidRequest</Code><BucketName>postgres-backup</BucketName><RequestId>tx0000000000000000c50a1-00624ea23a-3873de6-s3store</RequestId><HostId>3873de6-s3store-s3store</HostId></Error>
```

What I can't find in `/run/etc/wal-e.d/env` is any reference to aws region, there is supposed to be a file called AWS_REGION containing us-east-1 but for some reason it is missing.

Any idea on what I am missing? Or is this an actual bug?
