### ISSUE TITLE
After creating new nodes: "could not sync cluster: could not sync prepared database: could not execute create database schema: pq: permission denied for database xyz"

### ISSUE THREAD

**Issue by marcellodesales** [zalando/postgres-operator#1855]
> Please, answer some short questions which should help us to understand your problem / question better?

# What happened?

1. Needed to change the node groups, added new tags, for a new group of servers
2. Didn't stop the DB before, kept running
3. Postgres pods came back again, but couldn't setup the database

After that, I delete the project to start a new fresh database... However, it didn't come back up and the error message is as follows:

```
could not sync cluster: could not sync prepared database: could not execute create database
 schema: pq: permission denied for database xyz
```

Full logs link in the `gist` below...

thank you for anyone who can help!

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.7.1

registry.opensource.zalan.do/acid/postgres-operator:v1.7.1

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]

AWS EKS

- **Are you running Postgres Operator in production?** [yes | no]

yes

- **Type of issue?** [Bug report, question, feature request, etc.]

Bug? Question?

Some general remarks when posting a bug report:

- Please, check the operator, pod (Patroni) and postgresql logs first. When copy-pasting many log lines please do it in a separate GitHub gist together with your Postgres CRD and configuration manifest.

# 🔊 Full logs while creating the instance by `Patroni`

https://gist.github.com/marcellodesales/12460954d3d22910a3ad0ba8b32897bb

- If you feel this issue might be more related to the [Spilo](https://github.com/zalando/spilo/issues) docker image or [Patroni](https://github.com/zalando/patroni/issues), consider opening issues in the respective repos.

# 🔧 Config

> `kubectl kustomize env/aws-sae1-prdt-ppd-dev`

```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: supercash-postgres-server-aws-sae1-prdt-ppd-dev
  namespace: supercash-aws-sae1-prdt-ppd-dev
spec:
  databases:
    supercash: supercash
  enableMasterLoadBalancer: true
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: super.cash-worker_group-name
          operator: In
          values:
          - datappd
  numberOfInstances: 2
  postgresql:
    parameters:
      max_connections: "250"
    version: "14"
  preparedDatabases:
    supercash: {}
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  teamId: supercash
  users:
    supercash:
    - superuser
    - createdb
  volume:
    size: 10Gi
```

# 🔋 Volumes were created properly

* Deleting and creating a new does it

<img width="1556" alt="Screen Shot 2022-04-16 at 1 08 50 PM" src="https://user-images.githubusercontent.com/131457/163689944-3530e266-e559-43fe-a736-0c4d64e0a30a.png">

**Comment by marcellodesales** [comment]
# Minimum setup works

> Ref: https://github.com/zalando/postgres-operator/blob/master/manifests/minimal-postgres-manifest.yaml

* `$ kubectl describe postgresql acid-minimal-cluster`

```yaml
Name:         acid-minimal-cluster
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  acid.zalan.do/v1
Kind:         postgresql
Metadata:
Spec:
  Databases:
    Foo:                zalando
  Number Of Instances:  2
  Postgresql:
    Version:  14
  Prepared Databases:
    Bar:
  Team Id:  acid
  Users:
    foo_user:
    Zalando:
      superuser
      createdb
  Volume:
    Size:  1Gi
Status:
  Postgres Cluster Status:  Creating
Events:
  Type    Reason       Age   From               Message
  ----    ------       ----  ----               -------
  Normal  Create       22s   postgres-operator  Started creation of new cluster resources
  Normal  Endpoints    22s   postgres-operator  Endpoint "default/acid-minimal-cluster" has been successfully created
  Normal  Services     22s   postgres-operator  The service "default/acid-minimal-cluster" for role master has been successfully created
  Normal  Services     22s   postgres-operator  The service "default/acid-minimal-cluster-repl" for role replica has been successfully created
  Normal  Secrets      21s   postgres-operator  The secrets have been successfully created
  Normal  StatefulSet  21s   postgres-operator  Statefulset "default/acid-minimal-cluster" has been successfully created

```

**Comment by FxKu** [comment]
It's because you have you database `supercash` defined twice under `databases` and `preparedDatabases`:
```yaml
  databases:
    supercash: supercash
  preparedDatabases:
    supercash: {}
```

The prepared database should use its pre-defined owner role `supercash_owner` as the owner. But under `databases` you chose a different owner - `supercash`. The operator tries to create a schema `data` for the prepared DB (since no schema is specified) with what it expects to be the database owner (`supercash_owner`). And this is what is failing because `supercash` is the actual owner and `supercash_owner` is not allowed to create schemas inside this database.

```bash
time="2022-04-16T15:46:51Z" level=info msg="creating database schema \"data\" owner \"supercash_data_owner\"" cluster-name=supercash-aws-sae1-prdt-ppd-dev/supercash-postgres-server-aws-sae1-prdt-ppd-dev pkg=cluster worker=0
time="2022-04-16T15:46:51Z" level=warning msg="error while syncing cluster state: could not sync prepared database: could not execute create database schema: pq: permission denied for database supercash" cluster-name=supercash-aws-sae1-prdt-ppd-dev/supercash-postgres-server-aws-sae1-prdt-ppd-dev pkg=cluster worker=0
time="2022-04-16T15:46:51Z" level=error msg="could not sync cluster: could not sync prepared database: could not execute create database schema: pq: permission denied for database supercash" cluster-name=supercash-aws-sae1-prdt-ppd-dev/supercash-postgres-server-aws-sae1-prdt-ppd-dev pkg=controller worker=0
```
