### ISSUE TITLE
Error while syncing cluster state: could not sync statefulsets

### ISSUE THREAD

**Issue by jeremie-seguin** [zalando/postgres-operator#1883]
- **Which image of the operator are you using?** 
`registry.opensource.zalan.do/acid/postgres-operator:v1.7.1`
- **Where do you run it** 
GCP Kubernetes engine
- **Are you running Postgres Operator in production?** 
not yet
- **Type of issue?** 
question / feature request

Hello,

We tried the operator in our test environnement and after setting up the operator and a test cluster we wanted to add some labels to the cluster pods 

We changed `inherited_labels` in the operator configmap from undefined to `tags.datadoghq.com/service,tags.datadoghq.com/env,application,environment`

and `labels` in the cluster manifest to include
`tags.datadoghq.com/service: postgres`
`tags.datadoghq.com/env: integration`

But the operator can't update the cluster statefulset: 

```level=warning msg="new statefulset introduces extra labels in the label selector, cannot continue" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=info msg="statefulset postgres-operator/test-postgresql is not in the desired state and needs to be updated" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      application: spilo," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      cluster-name: test-postgresql" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="+      cluster-name: test-postgresql," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="+      tags.datadoghq.com/service: postgres" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-        application: spilo," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="+        tags.datadoghq.com/service: postgres," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-            name: pg-ident," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-            defaultMode: 420" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="+            name: pg-ident" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-              value: {\\application\\:\\spilo\\}" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="+              value: {\\tags.datadoghq.com/service\\:\\postgres\\}" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-          terminationMessagePath: /dev/termination-log," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-          terminationMessagePolicy: File," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-          terminationMessagePath: /dev/termination-log," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-          terminationMessagePolicy: File," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      restartPolicy: Always," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      dnsPolicy: ClusterFirst," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      serviceAccount: postgres-pod," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-                  application: spilo," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="+                  tags.datadoghq.com/service: postgres," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      schedulerName: default-scheduler," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      kind: PersistentVolumeClaim," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      apiVersion: v1," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      status: {" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-        phase: Pending" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-      }" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="+      status: {}" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-  }," cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="-  revisionHistoryLimit: 10" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="+  }" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=debug msg="updating statefulset" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=warning msg="error while syncing cluster state: could not sync statefulsets: could not update statefulset: could not patch statefulset spec \"postgres-operator/test-postgresql\": StatefulSet.apps \"test-postgresql\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden" cluster-name=postgres-operator/test-postgresql pkg=cluster
level=error msg="could not sync cluster: could not sync statefulsets: could not update statefulset: could not patch statefulset spec \"postgres-operator/test-postgresql\": StatefulSet.apps \"test-postgresql\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden" cluster-name=postgres-operator/test-postgresql pkg=controller worker=0
```

Is there a way to apply this new configuration after the cluster creation or do we have to delete the statefulset entirely, witch would induce a downtime ? 

Maybe consider adding the equivalent of `podAnnotations` for additional labels ?  

Thanks

**Comment by FxKu** [comment]
You configured `tags.datadoghq.com/service` and used `datadoghq.com/service`? What happened to `tags`?

**Comment by jeremie-seguin** [comment]
That was a copy-paste mistake, Thanks. But we never got to the stage of applying the cluster manifest changes anyway.

**Comment by FxKu** [comment]
Ok. Hm strange, I see that we choose to [replace the stateful set](https://github.com/zalando/postgres-operator/blob/2fcfac7ed4e85b3be208285d0056986cd8f5e006/pkg/cluster/cluster.go#L389) when annotations differ. For labels we only check the [labels of the template](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/cluster.go#L426). But either way, when you start adding inherited_labels to the manifest - it should trigger a replacement of the stateful set with rolling update. Not a patch like in your case. I could only image that `needsRollUpdate` is set to true [while comparing the containers](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/cluster.go#L393) and `needsReplace` remains nil. Can you share your stateful set manifest?

**Comment by jeremie-seguin** [comment]
I see from the code you've linked that we are hitting [this case](https://github.com/zalando/postgres-operator/blob/2fcfac7ed4e85b3be208285d0056986cd8f5e006/pkg/cluster/cluster.go#L436) And that the warning log is indeed present in our log. I'm not entirely sure why the operator still try to update the stateful set after detecting this but it look like a legitimate limitation.

I think the annotations are more appropriate to achieve what I want to do here since the don't involve dealing with the selector mechanics of the stateful set. 

Here is my cluster manifest for reference (pg-hba edited) : 

```
---
# Source: postgres-cluster/templates/postgres-manifest.yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: test-postgresql
  namespace: postgres-operator
spec:
  dockerImage: "registry.opensource.zalan.do/acid/spilo-14:2.1-p3"
  teamId: "test"
  numberOfInstances: 3
  sidecars:
    - name: "log-exporter"
      image: "fluent/fluentd:v1.14.5-debian-1.0"
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 100Mi
  podAnnotations:
    ad.datadoghq.com/postgres.check_names: '["process", "postgres"]'
    ad.datadoghq.com/postgres.init_configs: '[{},{}]'
    ad.datadoghq.com/postgres.logs: '[{"source": "patroni"}]'
    ad.datadoghq.com/log-exporter.logs: '[{"source": "postgres"}]'
    ad.datadoghq.com/postgres.instances: |
      [
        [{
          "name": "postgres",
          "search_string": ["postgres"]
        }]
      ]

  tolerations:
    - key: "postgres"
      operator: "Equal"
      value: "true"
      effect: NoSchedule
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: postgres
              operator: In
              values:
                - 'true'
  users:  # Application/Robot users
    testowner:
      - superuser
      - createdb
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  enableConnectionPooler: true # enable/disable connection pooler deployment
  enableReplicaConnectionPooler: true # set to enable connectionPooler for replica service
  allowedSourceRanges: [] # load balancers' source ranges for both master and replica services
  databases:
    test: testowner
  postgresql:
    version: "14"
    parameters:  # Expert section
      shared_buffers: "1024MB" # 7541 prod
      max_connections: "2000"
      log_statement: "none"
      log_min_duration_statement: 100ms
      log_line_prefix: '%t [%p]: [%l-%x] db=%d,user=%u,client=%h'
      ident_file: /pg_ident/pg_ident.conf
      password_encryption: scram-sha-256

  volume:
    size: 16Gi
    storageClass: pd-ssd
  additionalVolumes:
    - name: pg-ident
      mountPath: /pg_ident
      targetContainers:
        - all
      volumeSource:
        name: pg-ident
        configMap:
          name: pg-ident

  enableShmVolume: true
  spiloFSGroup: 103
  resources:
    requests:
      cpu: 1500m
      memory: 4000Mi
    limits:
      cpu: 1500m
      memory: 4000Mi
  patroni:
    pg_hba:
      - local   all             all                                   trust
      - hostssl all             +zalandos    127.0.0.1/32       pam
      - hostssl all             +zalandos    ::1/128            pam
      - local   replication     standby                    trust
      - hostssl replication     standby all                md5
      - hostnossl all           all                all                reject
      - hostssl all             +zalandos    all                pam
      - host    all             all                127.0.0.1/32       md5
      - host    all             all                ::1/128            md5
      - hostssl all             all                all                md5
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: false
    synchronous_mode_strict: false
#    synchronous_node_count: 1
    maximum_lag_on_failover: 33554432

  # overwrite custom properties for connection pooler deployments
  connectionPooler:
    numberOfInstances: 2
    mode: "transaction"
    schema: "pooler"
    user: "pooler"
    resources:
      requests:
        cpu: 300m
        memory: 100Mi
      limits:
        cpu: "1"
        memory: 100Mi

  # Custom TLS certificate. Disabled unless tls.secretName has a value.
  tls:
    secretName: test-postgresql-certificate  # should correspond to a Kubernetes Secret resource to load
    certificateFile: "tls.crt"
    privateKeyFile: "tls.key"
    caFile: "ca.crt"  # optionally configure Postgres with a CA certificate
```
