### ISSUE TITLE
Why after setting env, it will become uppercase

### ISSUE THREAD

**Issue by jicki** [zalando/postgres-operator#1892]
## Why after setting env, it will become uppercase

- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.8.0
- **Where do you run it - cloud or metal? Kubernetes  
- **Are you running Postgres Operator in production?**  yes
- **Type of issue?** question

* resource yaml

```bash
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgresql-cluster
  labels:
    app: postgresql
spec:
   .....
  env:
  ## Set  Log System  Env
   - name: k8s_logs_gitlab-server-postgresql
     value: "stdout"
   ....
```

* describe statefulsets.apps  postgresql-cluster

```
Pod Template:
  .....
    Environment:
     .....
      K8S_LOGS_GITLAB-SERVER-POSTGRESQL:  stdout     

     ......
```

* get statefulsets postgresql-cluster -o yaml

```
    spec:
      containers:
      - env:
         ......
        - name: K8S_LOGS_GITLAB-SERVER-POSTGRESQL
          value: stdout         
         .......
```
