### ISSUE TITLE
Port forward is working, but not able to access the port from other PODs

### ISSUE THREAD

**Issue by JaviOverflow** [zalando/postgres-operator#1907]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
registry.opensource.zalan.do/acid/postgres-operator:v1.8.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
AWS EKS deployed using terraform
- **Are you running Postgres Operator in production?** 
yes
- **Type of issue?** [Bug report, question, feature request, etc.] 
Question

Some general remarks when posting a bug report:
- Please, check the operator, pod (Patroni) and postgresql logs first. When copy-pasting many log lines please do it in a separate GitHub gist together with your Postgres CRD and configuration manifest.
- If you feel this issue might be more related to the [Spilo](https://github.com/zalando/spilo/issues) docker image or [Patroni](https://github.com/zalando/patroni/issues), consider opening issues in the respective repos.

Having the operator and operator-ui deployed, I deployed a new cluster by using the following YAML.

```
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "core-analytics"
  namespace: "default"
  labels:
    team: core

spec:
  teamId: "core"
  postgresql:
    version: "14"
  numberOfInstances: 1
  volume:
    storageClass: gp3
    size: "10Gi"

  allowedSourceRanges:
    - 0.0.0.0/0
 
  patroni:
    pg_hba:
      - local     all  all  trust
      - host      all  all  0.0.0.0/0   md5
      - host      all  all  ::1/128     md5
  users:
    analytics-rw:
      - superuser
      - createdb
    metabase:
      - superuser
  databases:
    analytics: analytics-rw
    metabase: metabase
```

Now my problem comes when I try to connect from another pod, it always times out. I've tried multiple different configurations for the pg_hba and allowedSourceRanges, but without any success. I went through the documentation multiple times and it is still not clear to me how can I enable the cluster to listen on those connections.

Few notes:
- I can connect by using port-forwarding on the master pod from my machine
- Within the pod, it properly resolves the DNS to the right cluster ip.
- I've tried from a pod running metabase, and from my custom quarkus java-based pod. Same TimeoutException on both.
- I've also tried from the postgres user, and from those metabase and analytics-rw users.

I really don't know what else to do.
