### ISSUE TITLE
unknown field "env" in do.zalan.acid.v1.postgresql.spec

### ISSUE THREAD

**Issue by jeubis** [zalando/postgres-operator#1914]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.8.1
1.71

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Managed K8s
K8s hosted via rancher 

- **Are you running Postgres Operator in production?** No

- **Type of issue?** Bug / question
I'm generally confused with the documentation and I'm not sure if I'm doing the incorrect thing due to misinterpretation of what is happening.

I'm trying to configure my wal backups and logical backups via AWS s3 but I'd only like to do this for my staging cluster as the last time I tried to do it with an incorrect config it ended up putting my pre-prod cluster in an unhealthy state.

The main issue I have found is that in the [documentation here](https://postgres-operator.readthedocs.io/en/latest/administrator/#via-postgres-cluster-manifest) it specifies that I'm able to provide environment variables from secrets directly to the pod as specified in the manifest.

I've provided my own manifest here:
```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: test-team-staging-cluster
  namespace: staging
spec:
  env:
    - name: wal_s3_bucket
      value: my-custom-bucket
  teamId: "test-team
  volume:
    size: 8Gi
  numberOfInstances: 3
  users:
    my_test_cluster
      - superuser
      - createdb
```

When I run this, I get the following error:
 
```
error: error validating "staging-deployment.yaml": error validating data: ValidationError(postgresql.spec): unknown field "env" in do.zalan.acid.v1.postgresql.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

Am I doing something incorrect or is this a genuine issue? The yaml runs perfectly and my database is up and running without a hitch otherwise.

I'm also happy to open a PR to amend documentation as I've had quite a few issues fully understanding everything for this operator.

Thanks for your time
