### ISSUE TITLE
[kustomize] use configMapGenerator instead of ConfigMap resource

### ISSUE THREAD

**Issue by NickLarsenNZ** [zalando/postgres-operator#1937]
When making changes to the `postgres-operator` ConfigMap, the operator doesn't appear to detect the changes (at least judging by the logs).

If `configMapGenerator` was used instead, the ConfigMap name would be given a suffix of the hash of the contents (so as the contents change, the hash changes, and so do the references used in Deployments/StatefulSets for example, which in-turn are reconciled (likely restarting the pods).

I haven't taken a close look, so perhaps the operator is constantly watching for changes via the k8s API.

**Comment by NickLarsenNZ** [comment]
Ok, on closer inspection, I can see that the ConfigMap in an environment variable by name. That means it's up to the controller to watch for changes. Perhaps those changes are happening and it just isn't logging it.

```yml
      containers:
        - env:
            - name: CONFIG_MAP_NAME
              value: postgres-operator
```

I'll leave this open in case someone can clarify, but feel free to close whenever.
