### ISSUE TITLE
Helm chart storage_resize_mode mixed does not work

### ISSUE THREAD

**Issue by tomsozolins** [zalando/postgres-operator#1946]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** AWS K8s 
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** question

Hi! I wanted to tune gp3 persistent volume iops and throughput.

Documentation at https://postgres-operator.readthedocs.io/en/latest/reference/operator_parameters/#kubernetes-resources
states that there is:
storage_resize_mode parameter - mixed :operator uses AWS API to adjust size, throughput, and IOPS, and calls pvc change for file system resize Default is "pvc".

When i add this parameter in postgres-operator 1.8.2 helm chart values i get error that such parameter is unsupported. 

Checked 1.8.2 helm chart crd manifest and such option "mixed" is missing - https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator/crds/operatorconfigurations.yaml#L320

Is iops/throughput tuning feature supported or not?

**Comment by tomsozolins** [comment]
Thank you!

**Comment by tomsozolins** [comment]
@FxKu I am using ArgoCD - can't edit manually - it overwrites it back. 
Do you mean OperatorCRD config or ConfigMap - noticed documentation says configmap is legacy way.

**Comment by FxKu** [comment]
Yes, it's ether or with ConfigMap and CRD. We still use the first one, so it won't go away anytime soon. Should remove the deprecated tag from our docs. Given there's a workaround I won't do a release. Only if other more serious bugs pop up.

**Comment by tomsozolins** [comment]
@FxKu Tried manual switch, but operator shows errors on sync volume:
time="2022-07-04T12:59:03Z" level=debug msg="syncing volumes using \"mixed\" storage resize mode" cluster-name=zabbix-stage/zabbix-psql-stage pkg=cluster
18
time="2022-07-04T12:59:03Z" level=info msg="starting reading ebs meta data" cluster-name=zabbix-stage/zabbix-psql-stage pkg=cluster
17
time="2022-07-04T12:59:03Z" level=debug msg="found 1 persistent volumes, size of known volumes 0" cluster-name=argo-watcher/argo-watcher-psql pkg=cluster
16
panic: runtime error: invalid memory address or nil pointer dereference
15
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17df3fe]
14
13
goroutine 54 [running]:
12
github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).populateVolumeMetaData(0xc000766000)
11
	/workspace/pkg/cluster/volumes.go:160 +0x25e
10
github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).syncVolumes(0xc000766000)
9
	/workspace/pkg/cluster/volumes.go:36 +0x135
8
github.com/zalando/postgres-operator/pkg/cluster.(*Cluster).Sync(0xc000766000, 0xc0007e0480)
7
	/workspace/pkg/cluster/sync.go:68 +0x3f2
6
github.com/zalando/postgres-operator/pkg/controller.(*Controller).processEvent(0xc0001d2380, {{0xc0a8d6e11819f1b4, 0x1021712e3, 0x30b9b20}, {0xc000498c90, 0x24}, {0x1d107b8, 0x4}, 0x0, 0xc0007e0480, ...})
5
	/workspace/pkg/controller/postgresql.go:310 +0xe90
4
github.com/zalando/postgres-operator/pkg/controller.(*Controller).processClusterEventsQueue(0xc0001d2380, 0x5, 0xc000114f00, 0x0)
3
	/workspace/pkg/controller/postgresql.go:344 +0x2c5
2
created by github.com/zalando/postgres-operator/pkg/controller.(*Controller).Run
1
	/workspace/pkg/controller/controller.go:446 +0x51

**Comment by FxKu** [comment]
That on [this](https://github.com/zalando/postgres-operator/blob/5e4badd99ce0adf9e6d436979d36f8addd56cb5f/pkg/cluster/volumes.go#L160) line. How do you persistent volumes look like? It expects the persistent volume resources to have fields `AWSElasticBlockStore.VolumeID`. Nevertheless, the operator should error out properly and not fail like this.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-...
  uid: ...
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://eu-central-1c/vol-...
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pgdata-acid-minimal-cluster-0
    namespace: default
    uid: ...
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound
```
