### ISSUE TITLE
Default user for schema have no access to preparedDatabase

### ISSUE THREAD

**Issue by baznikin** [zalando/postgres-operator#1949]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** DigitalOcean K8S
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

Prepared database defined like this:

```
spec:
  preparedDatabases:
    test:
      defaultUsers: true
      schemas:
        public:
          defaultRoles: true
          defaultUsers: true
```

test_reader_user have access to database, but test_public_reader_user do not have.

```
# psql -U test_owner_user test
test=> create table test (id int);
CREATE TABLE
test=> insert into test values (1);
INSERT 0 1
test=> insert into test values (2);
INSERT 0 1
test=> select * from test ;
 id 
----
  1
  2
(2 rows)

test=> \q

# psql -U test_reader_user test
test=> select * from test ;
 id 
----
  1
  2
(2 rows)

test=> \q

# psql -U test_public_reader_user test
test=> select * from test ;
ERROR:  permission denied for table test
```
