### ISSUE TITLE
Install ltree extension in postgres 

### ISSUE THREAD

**Issue by ravirajshankarl** [zalando/postgres-operator#1966]
Hi Colleagues,

  I have tried to install ltree extention following [link](https://github.com/zalando/postgres-operator/issues/938#issuecomment-1167390700), after deploy still **installed_version** value is empty. Please guide me on how to install
  
 select * from pg_available_extensions where name='ltree';
 name  | default_version | installed_version |                     comment
-------+-----------------+-------------------+-------------------------------------------------
 ltree | 1.2             |                   | data type for hierarchical tree-like structures

I have added my configuration settings as below

```
users: {}

databases:
  aorsdb: aorsdbuser

preparedDatabases:
  aorsdb:
    extensions:
      ltree: "public"

```
