### ISSUE TITLE
Recreation of DB clusters due changing nodeAffinity term order

### ISSUE THREAD

**Issue by ljcesca** [zalando/postgres-operator#1996]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** AWS EKS
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

We experienced an issue similar to [#924](https://github.com/zalando/postgres-operator/issues/924) due to changes in ordering of `nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions` across syncs of clusters.

Our operator configuration was setting two `node_readiness_labels` via:
```yaml
node_readiness_label:
  kubernetes.io/arch: amd64
  postgres-cluster: "1"
```
And an additional label via the `Cluster` spec:
```yaml
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: postgres-plan-small
        operator: In
        values:
        - "1"
```

We've worked around this for now by removing the `node_readiness_label` configuration, but would like to be able to use this again the future.

We were able to capture the `StatefulSet` before and after and confirmed that the order of `nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions` was [changing](https://gist.github.com/ljcesca/093b626132f1232f6712ab54f76bc54c). Which caused the cluster to be re-synced due to [`Cluster.compareStatefulSetWith`](https://github.com/zalando/postgres-operator/blob/master/pkg/cluster/cluster.go#L414).

I'm happy to work on a PR that fixes this if you agree that changes to `Cluster.compareStatefulSetWith` is the appropriate approach. Thanks!
