### ISSUE TITLE
set password for dbuser 

### ISSUE THREAD

**Issue by willzhang** [zalando/postgres-operator#1998]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
```
registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
```

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
```
Bare Metal K8s
```

- **Are you running Postgres Operator in production?** [yes | no]
```
no
```
- **Type of issue?** [Bug report, question, feature request, etc.]
```
question & feature reques
```

## question 

i want install Automatic installation harbor ，when i install harbor helm with external database , i need  database.password， the default one is Randomly generated， can i define password by myself in operator?

the [harbor helm charts](https://github.com/goharbor/harbor-helm/blob/v1.9.3/values.yaml#L772)
```
database:
  external:
    host: "192.168.0.1"
    port: "5432"
    username: "user"
    password: "password"
    coreDatabase: "registry"
    notaryServerDatabase: "notary_server"
    notarySignerDatabase: "notary_signer"
    # "disable" - No SSL
    # "require" - Always SSL (skip verification)
    # "verify-ca" - Always SSL (verify that the certificate presented by the
    # server was signed by a trusted CA)
    # "verify-full" - Always SSL (verify that the certification presented by the
    # server was signed by a trusted CA and the server host name matches the one
    # in the certificate)
    sslmode: "disable"
```

the feather i want
```

apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: postgres
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    harbor:  # database owner
    - superuser
    - createdb
  password:
        harbor: password123
  databases:
	registry: harbor
	notary_server: harbor
	notary_signer: harbor
  preparedDatabases:
    registry: {}
    notary_server: {}
    notary_signer: {}
  postgresql:
    version: "14"
```
