### ISSUE TITLE
hot_standby:'off' not propagated to postgres in standby cluster

### ISSUE THREAD

**Issue by ErikLundJensen** [zalando/postgres-operator#2058]
- Which image of the operator are you using?  **registry.opensource.zalan.do/acid/postgres-operator:v1.8.0**
- Where do you run it ? **Kubernetes 1.23.7 installed with Kubespray**
- Are you running Postgres Operator in production? **yes**
- Type of issue? **question**

We are running a standby cluster that uses streaming for replication from another cluster. They run in two destinct Kubernetes clusters.
However, the standby cluster runs in hot_standby mode even though we have specified "off" in the Postgresql manifest:

```
spec:
  postgresql:
    parameters:
      hot_standby: "off"
```

The value of hot_standby is 'off' in postgres.yml in the standby cluster's pod:

```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        ..
        hot_standby: 'off'
        ...
        wal_compression: 'on'
        wal_level: hot_standby
        wal_log_hints: 'on'
```

However, the database accepts connections and runs in read-only mode.
The state is:
```
SHOW in_hot_standby;
 in_hot_standby 
----------------
 on
(1 row)
```
and the postgres process does have`--hot_standby=on` as seen at the end of this line:
```
postgres    95     1  0 15:29 ?        00:00:00 /usr/lib/postgresql/14/bin/postgres -D /home/postgres/pgdata/pgroot/data --config-file=/home/postgres/pgdata/pgroot/data/postgresql.conf --listen_addresses=* --port=5432 --cluster_name=acid-standby-cluster --wal_level=replica --hot_standby=on ...
```

We have not changed the `wal_level`

Our applications uses addresses of the primary and standby clusters in the connect string. The applications get read-only connections from the standby cluster and fails when trying to do updates. We did not expect the applications to get read-only connections as `hot_standby = 'off' `

We prefer the applications have addresses for both clusters and thereby avoid reconfiguration of applications when primary cluster is unavailable and standby cluster is promoted to primary cluster.

Any comments on why the hot_standby is not propagated? Or comments the configuration of the application connection string having both database endpoints.
