### ISSUE TITLE
Can't override image repositories of sidecars within operators helm values.yaml

### ISSUE THREAD

**Issue by alfsch** [zalando/postgres-operator#2114]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Bare Metal K8s
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** feature requestSome general remarks when posting a bug report:
- Related to postgres-operator helm charts

Currently we define some default sidecars in values.yaml like this:

```
  configGeneral:
    docker_image: registry.opensource.zalan.do/acid/spilo-14:2.1-p5
    sidecars:
      - image: quay.io/prometheuscommunity/postgres-exporter-linux-amd64:v0.10.1
        imagePullPolicy: IfNotPresent
        name: postgres-exporter
      - image: busybox:1.31
        imagePullPolicy: IfNotPresent
```

Due to different stages we wan't ot override the images used by the sidecars.

This is currently not possible since helm can't override values in arrays with --set :-(

Now we're patching the tarball like in [pull request](https://github.com/zalando/postgres-operator/pull/1986) to make the change of images possible. This manual patching is error prone and breaks our gitops.

Plz. implement the above pull request
