### ISSUE TITLE
WAL bucket scope prefix/suffix missing when configuring WAL_S3_BUCKET locally

### ISSUE THREAD

**Issue by haslersn** [zalando/postgres-operator#2116]
When configuring `WAL_S3_BUCKET` via ConfigMap, Secret, or `spec.env` (per PostgreSQL cluster) instead of globally in the operator config, then the operator doesn't configure `WAL_BUCKET_SCOPE_SUFFIX` and `WAL_BUCKET_SCOPE_PREFIX`.
This is due to the following check: https://github.com/zalando/postgres-operator/blob/640581fb4661dbab852dfc0995b5e9f6140fd8f8/pkg/cluster/k8sres.go#L939

This hit us unexpectedly when we wanted to migrate our setup to use a distinct bucket per PostgreSQL cluster. Furthermore, even when using a distinct bucket per PostgreSQL cluster, it's still a good idea to have the cluster UID in the `WAL_BUCKET_SCOPE_SUFFIX`, so that a cluster that gets recreated has a clean state and doesn't conflict with existing WAL backups.

Possible solution: Maybe the operator can unconditionally inject `WAL_BUCKET_SCOPE_SUFFIX` and `WAL_BUCKET_SCOPE_PREFIX`, no matter if `c.OpConfig.WALES3Bucket` is non-empty.

Workaround: In the OperatorConfiguration, set `configuration.aws_or_gcp.wal_s3_bucket: dummy` and overwrite it on a per-PostgreSQL-cluster basis by setting the environment variable `WAL_S3_BUCKET` via ConfigMap, Secret, or `spec.env`.  I only tested it with `spec.env` and that seems to have precedence over the environment variable injected by the operator.

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2

**Comment by kevinvalk** [comment]
NOTE: When using this strategy you cannot restore from clone anymore. No matter what you do, the `dummy` bucket will take precedence over all your configurations efforts of the CLONE_* bucket. The only way I could get this to work was by directly setting the s3_* keys inside `spec.clone`.

```yaml
```yaml
spec:
  clone:
    uid: "efd12e58-5786-11e8-b5a7-06148230260c"
    cluster: "cluster-name"
    timestamp: "2023-12-19T12:40:33+01:00"

    s3_wal_path: "s3://${s3_backup_bucket}/spilo/cluster-name/efd12e58-5786-11e8-b5a7-06148230260c/wal/${pg_version}/"
    s3_endpoint: https://s3.${s3_backup_region}.${s3_cloud}:443

    s3_force_path_style: true # Prevents the bucket to become a subdomain
    s3_access_key_id: ${s3_backup_access_key_id}
    s3_secret_access_key: ${s3_backup_secret_access_key}
  env:
    - name: CLONE_AWS_REGION
      value: ${s3_backup_region}
```
```

**Comment by Lxrdknows77** [comment]
@kevinvalk btw, to change default backup path it's required to specify `WAL_BUCKET_SCOPE_SUFFIX`, but what is variable define UID of cluster?

**Comment by Lxrdknows77** [comment]
@kevinvalk but how to get cluster UID to write it in `WAL_BUCKET_SCOPE_SUFFIX` variable in cluster manifest env part to use UID as a part of backup path?

**Comment by Lxrdknows77** [comment]
Spilo backup path template is defined in spilo code as ```/spilo/{WAL_BUCKET_SCOPE_PREFIX}{SCOPE}{WAL_BUCKET_SCOPE_SUFFIX}/wal/{PGVERSION}``` [here](https://github.com/zalando/spilo/blob/849313c8e6be874c8f7193657fa78f25d7e2086a/postgres-appliance/scripts/configure_spilo.py#L763)

Where:

1. `WAL_BUCKET_SCOPE_PREFIX` is defined in spilo code as `namespace-clustername` for non-default namespace. [codeline](https://github.com/zalando/spilo/blob/849313c8e6be874c8f7193657fa78f25d7e2086a/postgres-appliance/scripts/configure_spilo.py#L502)
2. `WAL_BUCKET_SCOPE_SUFFIX` is not defined in spilo.
3. `SCOPE` - cluster name

{`WAL_BUCKET_SCOPE_PREFIX`} and {`WAL_BUCKET_SCOPE_SUFFIX`} are defined by zalando operator code during cluster creation: [link](https://github.com/zalando/postgres-operator/blob/29cec0ceda6dba6e761c217137f8fa9c1c90cb8c/pkg/cluster/k8sres.go#L1013)

```
// global variables derived from operator configuration
	opConfigEnvVars := make([]v1.EnvVar, 0)
	if c.OpConfig.WALES3Bucket != "" {
		opConfigEnvVars = append(opConfigEnvVars, v1.EnvVar{Name: "WAL_S3_BUCKET", Value: c.OpConfig.WALES3Bucket})
		opConfigEnvVars = append(opConfigEnvVars, v1.EnvVar{Name: "WAL_BUCKET_SCOPE_SUFFIX", Value: getBucketScopeSuffix(string(uid))})
		opConfigEnvVars = append(opConfigEnvVars, v1.EnvVar{Name: "WAL_BUCKET_SCOPE_PREFIX", Value: ""})
	}
```

But this block will be executed only if `WALES3Bucket` is defined in operator configuration (`c.OpConfig.WALES3Bucket`). But global operator configuration approach is not suitable for us and we want to use only env definition directly in
manifests. 

As I mention in the prev msg, what I can suppose that after creation of cluster, we can get its UID and then put it in to cluster env as `WAL_BUCKET_SCOPE_SUFFIX`. Once spilo container will run and start up, backup path will include  that `WAL_BUCKET_SCOPE_SUFFIX` ( because we add it as UID before) and at the end path will be: `/spilo/namespace-cluster-nam/UID/wal/{PGVERSION}`

Is it correct way to do it?

**Comment by baznikin** [comment]
That's right, tere is inconsistent behavior in UID usage in backup/restore. According to current documentation I thought it is OK to set variables via ConfigMap. My setup

```
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: postgres-pod-config
      namespace: ${var.env}
    data:
      # WAL archiving and physical basebackups for PITR
      WAL_S3_BUCKET: "${var.cluster_tag}-db-wal"
      AWS_ENDPOINT: "https://${var.bucket_region}.digitaloceanspaces.com"
      AWS_SECRET_ACCESS_KEY: ${var.spaces_secret_key}
      AWS_ACCESS_KEY_ID: ${var.spaces_access_id}
      # default values for cloning a cluster (same as above)
      CLONE_WAL_S3_BUCKET: "${var.cluster_tag}-db-wal"
      CLONE_AWS_ENDPOINT: "https://${var.bucket_region}.digitaloceanspaces.com"
      CLONE_AWS_SECRET_ACCESS_KEY: ${var.spaces_secret_key}
      CLONE_AWS_ACCESS_KEY_ID: ${var.spaces_access_id}
```

My cluster started to stream backups to S3. Now I try to clone it with (minimal manifest based on docs)
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: pg-clone
  namespace: sandbox
spec:
  clone:
    uid: "9e284c3e-8257-4ea9-b952-a88f9bc1772d"   # source cluster UID
    cluster: "develop-postgresql" # source cluster name
    timestamp: "2017-12-19T12:40:33+01:00" # desired point in time
  numberOfInstances: 1
  teamId: "clone"
  postgresql:
    version: "15"
  volume:
    size: 50Gi
```

Clone failed because of missing S3 path.
Backup use `/spilo/sandbox-develop-postgresql/wal/15` (i.e. with prefix and no uid)
Restore wants `/spilo/develop-postgresql/9e284c3e-8257-4ea9-b952-a88f9bc1772d/wal/15` (no prefix and uid)

**Comment by baznikin** [comment]
I found minimal working config for my usecase (one bucket for WAL backups). I move bucket name config to operator config, it is enough for consistence backup/restore:

```
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: postgres-pod-config
      namespace: ${var.env}
    data:
      # WAL_S3_BUCKET: "${var.cluster_tag}-db-wal"
      AWS_ENDPOINT: "https://${var.bucket_region}.digitaloceanspaces.com"
      AWS_SECRET_ACCESS_KEY: ${var.spaces_secret_key}
      AWS_ACCESS_KEY_ID: ${var.spaces_access_id}
      # CLONE_WAL_S3_BUCKET: "${var.cluster_tag}-db-wal"
      CLONE_AWS_ENDPOINT: "https://${var.bucket_region}.digitaloceanspaces.com"
      CLONE_AWS_SECRET_ACCESS_KEY: ${var.spaces_secret_key}
      CLONE_AWS_ACCESS_KEY_ID: ${var.spaces_access_id}
```
```
apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-configuration
configuration:
  aws_or_gcp:
    wal_s3_bucket: "${var.cluster_tag}-db-wal"
```
