### ISSUE TITLE
Mounting a thesaurus in two locations for a mayor version upgrade does not work.

### ISSUE THREAD

**Issue by EraYaN** [zalando/postgres-operator#2118]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Azure Kubernetes Service
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Question/Feature Request

So the original (working) config was:

```yaml
  additionalVolumes:
  - name: thesaurus
    mountPath: /usr/share/postgresql/13/tsearch_data/extra.ths
    subPath: "legacy/Search/extra.ths"
    targetContainers:
      - postgres
    volumeSource:
      PersistentVolumeClaim:
        claimName: production-data
        readyOnly: true
```
Tried an upgrade and of course that will complain about the missing file, so tried to mount it twice.

So for example this will not deploy.
```yaml
  additionalVolumes:
  - name: thesaurus-v13
    mountPath: /usr/share/postgresql/13/tsearch_data/extra.ths
    subPath: "legacy/Search/extra.ths"
    targetContainers:
      - postgres
    volumeSource:
      PersistentVolumeClaim:
        claimName: production-data
        readyOnly: true
  - name: thesaurus-v14
    mountPath: /usr/share/postgresql/14/tsearch_data/extra.ths
    subPath: "legacy/Search/extra.ths"
    targetContainers:
      - postgres
    volumeSource:
      PersistentVolumeClaim:
        claimName: production-data
        readyOnly: true
```
And them you get FailedMount errors. `production-data` points to a ReadWriteMany volume (azurefiles).

But this is required to make the pg_upgrade work that inplace_upgrade.py uses. Since none of these locations can be adjusted `/usr/share/postgresql/14/tsearch_data` is a hard requirement from postgres' side. It would be helpful to have some way of say having "mountPath" also be an array or something. Or maybe I'm overlooking the correct way to deploy custom thesaurus files and the like.

I get that this is maybe a bit of an esoteric issue. But I was wondering of anyone has dealt with this before.
