### ISSUE TITLE
Is it possible to grant default role to custom user?

### ISSUE THREAD

**Issue by Tri0L** [zalando/postgres-operator#2126]
I have for example cluster like this:
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: dev-pg
  namespace: test-pg
spec:
  teamId: "dev"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    testuser: []
  preparedDatabases:
    mydb:
      schemas:
        myschema: {}
  postgresql:
    version: "12"
```

Operator will create default NOLOGIN roles. For example `mydb_myschema_owner`.

Is it possible to grant `mydb_myschema_owner` role to user `testuser` throughth yaml?

If I trying to do something like this:
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: dev-pg
  namespace: test-pg
spec:
  teamId: "dev"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    testuser:
      - mydb_myschema_owner
  preparedDatabases:
    mydb:
      schemas:
        myschema: {}
  postgresql:
    version: "12"
```

I have error:
```
The postgresql "dev-pg" is invalid: spec.users.testuser: Unsupported value: "mydb_myschema_owner": supported values: "bypassrls", "BYPASSRLS", "nobypassrls", "NOBYPASSRLS", "createdb", "CREATEDB", "nocreatedb", "NOCREATEDB", "createrole", "CREATEROLE", "nocreaterole", "NOCREATEROLE", "inherit", "INHERIT", "noinherit", "NOINHERIT", "login", "LOGIN", "nologin", "NOLOGIN", "replication", "REPLICATION", "noreplication", "NOREPLICATION", "superuser", "SUPERUSER", "nosuperuser", "NOSUPERUSER"
```

**Comment by dmvolod** [comment]
Hi @Tri0L 
please have a look at this documentation part, to get a answer your question
https://postgres-operator.readthedocs.io/en/latest/user/#prepared-databases-with-roles-and-default-privileges

**Comment by Tri0L** [comment]
Yep, sure, I saw it.

<img width="768" alt="Снимок экрана 2022-12-06 в 11 44 04" src="https://user-images.githubusercontent.com/1208486/205862805-48a0c343-8e85-47e5-ae28-4ba74faa8652.png">

But when I try to grant role to user I have error that value is not supported.

**Comment by dmvolod** [comment]
Yes, but this is a part of the **Prepared databases with roles and default privileges** section and not part of the `users` CR config.

`users` section is allows to specify predefined values only
```yaml
              users:
                type: object
                additionalProperties:
                  type: array
                  nullable: true
                  items:
                    type: string
                    enum:
                    - bypassrls
                    - BYPASSRLS
                    - nobypassrls
                    - NOBYPASSRLS
                    - createdb
                    - CREATEDB
                    - nocreatedb
                    - NOCREATEDB
                    - createrole
                    - CREATEROLE
                    - nocreaterole
                    - NOCREATEROLE
                    - inherit
                    - INHERIT
                    - noinherit
                    - NOINHERIT
                    - login
                    - LOGIN
                    - nologin
                    - NOLOGIN
                    - replication
                    - REPLICATION
                    - noreplication
                    - NOREPLICATION
                    - superuser
                    - SUPERUSER
                    - nosuperuser
                    - NOSUPERUSER
```

**Comment by Tri0L** [comment]
Can't understand. 
Could you please provide example? How I can grant `mydb_myschema_owner`, to `testuser`?

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: dev-pg
  namespace: test-pg
spec:
  teamId: "dev"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    testuser: []
  preparedDatabases:
    mydb:
      schemas:
        myschema: {}
  postgresql:
    version: "12"
```

**Comment by dmvolod** [comment]
Seem to can't be assigned `mydb_myschema_owner` to the `testuser`. Only predefined users and roles are available for this option

**Comment by Tri0L** [comment]
In my case I have one database `mydb`. And few app users with different rights. 

For example:
```
  preparedDatabases:
    mydb:
      schemas:
        myschema: {}
```

**Needed roles:**
svc_app1 - mydb_owner
svc_app2 - mydb_myschema_reader

Do I understand correctly that the operator cannot assign roles to these users and it must be done manually?

**Comment by dmvolod** [comment]
> Do I understand correctly that the operator cannot assign roles to these users and it must be done manually?

If you can't to change/map and utilize a predefined user names, seems to this must be done manually. But it's better to use an "out-of-box" solutions, to get, for example, user passwords from the generated secrets.

**Comment by Tri0L** [comment]
I can't utilise default users because I need few users with same or similar rights.

For example:
```
  preparedDatabases:
    mydb:
      schemas:
        myschema: {}
        myschema2: {}
        myschema3: {}
```        

**Needed users like this:**
svc_app1 - mydb_owner
svc_app2 - mydb_myschema_reader
svc_app3 - mydb_myschema_reader, mydb_myschema2_writer
svc_app4 - mydb_myschema_reader, mydb_myschema_reader3_owner
something like this for real users too. Some of them can access all database tables/schemas, but some of them only few schemas.

I need different usernames so that I can distinguish their requests in the pg_stat_statements/pg_stat_activity, etc.

**Comment by dmvolod** [comment]
> I need different usernames so that I can distinguish their requests in the pg_stat_statements/pg_stat_activity, etc.

Oh, seems to infrastructure roles definition for the entire operator instance (OperatorConfiguration CR) can help you in advance to the predefined roles

https://postgres-operator.readthedocs.io/en/latest/user/#infrastructure-roles

```yaml
apiVersion: v1
data:
  svc_app1: anVzdGljZQ==
  svc_app3: anVzdGljZQ==
kind: Secret
metadata:
  name: postgresql-infrastructure-roles
type: Opaque
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-infrastructure-roles
data:
  svc_app1: |
    inrole: [mydb_owner]  # following roles will be assigned to the new user
  svc_app3: |
    inrole: [mydb_myschema_reader, mydb_myschema2_writer]  # following roles will be assigned to the new user
```

```yaml
kubernetes:
  infrastructure_roles_secret_name: "postgresql-infrastructure-roles"
```

But need to be validated
