### ISSUE TITLE
Unable to WAL-e clone from custom S3 bucket

### ISSUE THREAD

**Issue by mayzyo** [zalando/postgres-operator#2162]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**
- registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
- Kubernetes, Bare Metal K8s
- **Are you running Postgres Operator in production?**
- no
- **Type of issue?**
- question

I'm trying to wal-e clone a cluster after I deleted it, I've been backing it up over a month and can't figure out the right spec to write.
I backup to a local custom s3 bucket (Rook Ceph), I can see there is 310 objects inside and I've accessed the bucket manually and everything is there.

My problem is, for the spec s3_endpoint, if I write:
- **s3_endpoint: http+path://rook-ceph-rgw-main-store.rook-ceph.svc:80**
- I get: 
```
ERROR: 2023/01/08 04:55:43.858236 failed to list s3 folder: 'basebackups_005/': RequestError: send request failed
caused by: Get "http+path://rook-ceph-rgw-main-store.rook-ceph.svc:80/zalando-bkt-f3bbb545-feef-4913-a56a-2db954ba9571?delimiter=%2F&list-type=2&prefix=basebackups_005%2F": unsupported protocol scheme "http+path"
```
- **s3_endpoint: http://rook-ceph-rgw-main-store.rook-ceph.svc:80**
- I get:
```
WARNING - Invalid WALE_S3_ENDPOINT, the format is protocol+convention://hostname:port, but got http://rook-ceph-rgw-main-store.rook-ceph.svc:80
```

I tried several other combinations and it always return one or the other error. Please tell me what's the correct way to write this.
The full clone spec is:
```
  clone:
    cluster: "production-db-server"
    timestamp: "2023-01-01T12:00:00+10:00"
    s3_wal_path: "s3://zalando-bkt-f3bbb545-feef-4913-a56a-2db954ba9571"
    s3_endpoint: http+path://rook-ceph-rgw-main-store.rook-ceph.svc:80
    s3_access_key_id: 
    s3_secret_access_key: 
    s3_force_path_style: false
```

**Comment by mayzyo** [comment]
For posterity, I eventually tried enough combination and had the cloning process working with the following:
```
  clone:
    cluster: "production-db-server" 
    timestamp: "2023-01-03T12:00:00+10:00"
    s3_wal_path: "s3://zalando-bkt-f3bbb545-feef-4913-a56a-2db954ba9571/spilo/production-db-server/wal/14"
    s3_endpoint: http://rook-ceph-rgw-main-store.rook-ceph.svc:80
    s3_access_key_id:
    s3_secret_access_key:
    s3_force_path_style: true
```
Note it didn't seem to need the uid at all and you are suppose to ignore the WARNING regarding invalid WALE_S3_ENDPOINT, as well as the path needing to be the exact folder where the wal_backup folder is in and not "the bucket name" as was describe in the documentation. I didn't change the structure of the bucket or anything, it's all setup by postgres-operator itself this way.

Unfortunately I still wasn't able to clone the cluster in the end because I had a "Point-in-time recovery failed" exception which seems to be a separate issue. I'm just going to accept my losses and clear all the backups and start from scratch.
