### ISSUE TITLE
Clone from S3

### ISSUE THREAD

**Issue by strowi** [zalando/postgres-operator#2169]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** HCloud + K3s
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

Hi,

i recently started testing this operator. So far i was able to use the quickstart including the `minimal-postgresql-manifest.yaml` to get 2 replicas working, replicating, failover and restore from the other master.
Now i am looking into backups + clone to and from AWS S3. Streaming WALs to S3 seems to be working, but i can't figure out how to clone a new cluster from that backup.

So after running the minimal-manifest with streaming backups i deleted the whole cluster including PVs and added the `spec.clone`-part - but without the mentioned mandatory UID. 

How do i get that UID from the backup in case the whole cluster is gone (including applied manifests)?

This is the manifest:

```yaml
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  clone:
    cluster: "acid-minimal-cluster"
    s3_wal_path: "s3://bucketname/spilo/acid-minimal-cluster/wal/14"
    s3_access_key_id: "XXXAWSKEYXXX"
    s3_secret_access_key: "XXXAWSSECRETXXX"
  teamId: "acid"
  volume:
    size: 5Gi
    storageClass: "hcloud-volumes"
  numberOfInstances: 2
  users:
    postgres:  # database owner
      - superuser
      - createdb
    admin:
      - superuser
      - createdb
  databases:
    mgmt_v2: admin  # dbname: owner
  preparedDatabases:
    keycloak:
      extensions:
        ltree: public
  postgresql:
    version: "14"
  env:
    - name: WAL_S3_BUCKET
      value: bucketname
    - name: WAL_BUCKET_SCOPE_PREFIX
      value: ""
    - name: AWS_ACCESS_KEY_ID
      value: XXXAWSKEYXXX
    - name: AWS_REGION
      value: eu-central-1
    - name: AWS_SECRET_ACCESS_KEY
      value: XXXAWSSECRETXXX
```

Postgres still seems to try restoring from a master (which is non-existent).

```bash
...
[acid-minimal-cluster-0] 2023-01-12 15:19:59,080 INFO: No PostgreSQL configuration items changed, nothing to reload.
[acid-minimal-cluster-0] 2023-01-12 15:19:59,088 INFO: Lock owner: None; I am acid-minimal-cluster-0
[acid-minimal-cluster-0] 2023-01-12 15:19:59,258 INFO: trying to bootstrap a new cluster
[acid-minimal-cluster-0] 2023-01-12 15:19:59,259 INFO: Running custom bootstrap script: python3 /scripts/clone_with_basebackup.py --pgpass=/home/postgres/.pgpass_acid-minimal-cluster --host=acid-minimal-cluster --port=5432 --user="standby"
[acid-minimal-cluster-0] 2023-01-12 15:19:59,320 INFO: cloning cluster acid-minimal-cluster from "host=acid-minimal-cluster port=5432 user=standby dbname=postgres"
[acid-minimal-cluster-0] 2023-01-12 15:20:09,587 INFO: Lock owner: None; I am acid-minimal-cluster-0
[acid-minimal-cluster-0] 2023-01-12 15:20:09,588 INFO: not healthy enough for leader race
[acid-minimal-cluster-0] 2023-01-12 15:20:09,653 INFO: bootstrap in progress
```

**Comment by mmoscher** [comment]
As mentioned in the docs, if no timestamp is provided, a direct clone is done.

https://postgres-operator.readthedocs.io/en/latest/user/#clone-directly

Thus, IMHO, no issue at all.

**Comment by strowi** [comment]
Turns out additionally removing the s3_wal_path also adds the uid to the path. Got it working.

**Comment by KlavsKlavsen** [comment]
Could you share how the object should look exactly for restore to work?
We're trying to get restore from our postgres-operator backups to work and failing :(

**Comment by strowi** [comment]
@KlavsKlavsen my issue was related to #2116 which meant the uid was not in the s3-bucket path when storing the wal so cloning was pointless as the uid is required. But then i really only had to specify uid, cluster and timestamp under clone.

```yaml
spec:
  clone:
    uid: "26491ed4-6f2e-4788-bd47-xyxXXXXX5"
    cluster: "acid-minimal-cluster"
    timestamp: "2023-01-18T12:23:15+01:00"
```

All other variables like credentials were in the postgres-pod-secret

**Comment by KlavsKlavsen** [comment]
ahh. We set WAL_BUCKET_SCOPE_PREFIX and WAL_BUCKET_SCOPE_SUFFIX both to null - which should make it unnecessary to set UID on restore.. testing that now :)

**Comment by maxkamalov** [comment]
@strowi Do you resolved task restore postgres DB  from S3?

**Comment by matrix-spec** [comment]
@maxkamalov I came late to answer on time, but I'll leave my research on how to do it. I've been doing this for a long time, but successfully, something could have changed since then:
https://matrix-spec.github.io/kubernetes/2023/03/05/recovery-DBs-in-Zalando-postgres-operator.html
The page also has a link to the ISSUE in github.

**Comment by Ahmad-Faizan** [comment]
@KlavsKlavsen @maxkamalov I managed to get this working with this spec

```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: keycloakx-pgsql
  namespace: keycloakx
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  databases:
    keycloak: keycloak
  preparedDatabases:
    keycloak: {}
  enableMasterLoadBalancer: false
  numberOfInstances: 1
  postgresql:
    version: "16"
  teamId: keycloakx
  users:
    keycloak:
    - superuser
  clone:
    cluster: "keycloakx-pgsql" 
    timestamp: "2025-09-10T03:00:00+00:00"
    s3_wal_path: "s3://postgres-backup-s3-bucket/spilo/keycloakx-pgsql/92129239-92b9-4df8-a0d8-88fb8c77d90d/wal/12"
  volume:
    size: 4Gi
```

This was used to bring back a pgsql 12 (note the wal path) to a fresh instance of pgsql 16.
Also remember to add the uid in the `s3 wal path`.
