### ISSUE TITLE
Predefined PersistentVolumeClaims

### ISSUE THREAD

**Issue by kkrasnov1** [zalando/postgres-operator#2179]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

Is it legal to pre-create a PersistentVolumeClaims with different storage classes for a postgresql cluster?

**Comment by dmvolod** [comment]
Seems to you are trying to hack a system :grinning: but it's not possible

If you are talking about `spec.volume.selector` field in the PostgreSQL CR, based on this field, a `PersistentVolumeClaimTemplate` field of the StatefulSet will be filled with provided size, storageClass (default if not provided) and selector.
This allows to map the cluster to already created Persistent Volumes (PVs)

**Comment by dmvolod** [comment]
```bash
19:16 $ kubectl get pv
NAME   CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                STORAGECLASS   REASON   AGE
pv01   1Gi        RWO            Delete           Bound       test/pgdata-acid-minimal-cluster-0   standard                10m
pv02   1Gi        RWO            Delete           Available                                        new                     10m

19:22 $ kubectl get pvc -n test
NAME                            STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pgdata-acid-minimal-cluster-0   Bound     pv01     1Gi        RWO            standard       10m
pgdata-acid-minimal-cluster-1   Pending                                      standard       10m

19:23 $ kubectl get pods,statefulset,pg -n test
NAME                         READY   STATUS    RESTARTS   AGE
pod/acid-minimal-cluster-0   1/1     Running   0          12m
pod/acid-minimal-cluster-1   0/1     Pending   0          12m

NAME                                    READY   AGE
statefulset.apps/acid-minimal-cluster   1/2     12m

NAME                                            TEAM   VERSION   PODS   VOLUME   CPU-REQUEST   MEMORY-REQUEST   AGE   STATUS
postgresql.acid.zalan.do/acid-minimal-cluster   acid   14        2      1Gi                                     12m   Running
```

Cluster prints that it's in the Running state, but replicas pods were not bound to the PV. Seems to this is bug

**Comment by kkrasnov1** [comment]
I'm learning how it works :)

# Example

* Predefined PVC:

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-acid-test14-0
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-acid-test14-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc2
```

* Create PostgreSQL cluster:

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-test14
spec:
  teamId: "acid"
  spiloFSGroup: 103
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi  
  allowedSourceRanges:
    - 0.0.0.0/0
  volume:
    size: 10Gi

  numberOfInstances: 2
  users:
    # database owner
    zalando:
    - superuser
    - createdb

  tls:
    caFile: ca.crt
    caSecretName: pg-tls-ca
    secretName: pg-tls

  postgresql:
    version: "14"
```

Cluster work fine.

```
$ kubectl get pods,statefulset,pg
NAME                                                           READY   STATUS    RESTARTS       AGE
pod/acid-test14-0                                              2/2     Running   0              50m
pod/acid-test14-1                                              2/2     Running   0              49m

NAME                                                               READY   AGE
statefulset.apps/acid-test14                                       2/2     50m

NAME                                   TEAM   VERSION   PODS   VOLUME   CPU-REQUEST   MEMORY-REQUEST   AGE   STATUS
postgresql.acid.zalan.do/acid-test14   acid   14        2      10Gi     100m          100Mi            50m   Running
```

Is it legal to do this?

P.S. It works well with static volumes, but I wanted to understand the option with PVC.
