### ISSUE TITLE
restore backups are missing vital information

### ISSUE THREAD

**Issue by KlavsKlavsen** [zalando/postgres-operator#2197]
Using 1.8.2 with non-aws s3 for backup.

We tried to follow: https://postgres-operator.readthedocs.io/en/latest/user/#clone-directly
setting:
```
 apiVersion: acid.zalan.do/v1
 kind: postgresql
 metadata:
   name: mattermost-pgsql
 spec:
   env:
   - name: AWS_SECRET_ACCESS_KEY
     valueFrom:
       secretKeyRef:
         name: mattermost-pgsql-postgres-pod-env
         key: AWS_SECRET_ACCESS_KEY
   databases:
     mattermost: mattermost
   preparedDatabases:
     mattermost: {}
   enableMasterLoadBalancer: false
   numberOfInstances: 1
   postgresql:
     version: "12"
   teamId: mattermost
   users:
     mattermost:
     - superuser
   clone:
     cluster: "mattermost-pgsql"  # Inplace restore when having the same cluster name as the source
     timestamp: "2022-05-03T19:50:00+00:00"  # timezone required (offset relative to UTC, see RFC 3339 section 5.6)
   volume:
     size: 8Gi
  ```
But that fails with:
2023-01-30 10:51:02,543 - bootstrapping - WARNING - Cloning with WAL-E is only possible when CLONE_WALE_*_PREFIX or CLONE_WALG_*_PREFIX or CLONE_WAL_*_BUCKET and CLONE_SCOPE are set.
and does onthing

Turns out we NEED to also set some CLONE_WALG_.. settings (since postgres-operator uses walg for backups it seems ?)
