### ISSUE TITLE
How to set synchronous communication between primary and read-replica

### ISSUE THREAD

**Issue by arjunavinfra** [zalando/postgres-operator#2206]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g.  quay.io/anuta/postgres-operator:v1.8.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?**  yes 
- **Type of issue?** question

 I have a requirement to set up disaster recovery on postgresql running as a operator, I have used patroni CRD for the same for setting this up.
 I need to setup asynchronous communication between the primary cluster and the standby cluster , which has been done using the below attribute .

```
 patroni:
   synchronous_mode: false 
```

 Also, I  need the replication between the master and read-replica synchronously like in the below diagram, What are the modifications that I need to do in configuration files to set the primary replica communication as synchronous?

![anuta-dr drawio (4)](https://user-images.githubusercontent.com/118735091/217154339-07e5520e-040d-44be-875a-d12d498a86d7.png)

**Comment by arjunavinfra** [comment]
posgres-cluster.yaml
```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  annotations:
    meta.helm.sh/release-name: infra-postgres
  generation: 3
  labels:
    app: infra-postgres-db
    app.kubernetes.io/managed-by: Helm
    infra: "true"
    k8s-app: infra-postgres-db
  name: infra-postgres-db
spec:
  additionalVolumes:
  - mountPath: /config
    name: postgres-exporter-config
    targetContainers:
    - postgres-exporter
    volumeSource:
      configMap:
        name: postgres-exporter-config
  allowedSourceRanges:
  - 0.0.0.0/0
  databases:
    netseva: netseva
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  numberOfInstances: 2
  patroni:
    synchronous_mode: false
  podAnnotations:
    prometheus: infra-postgres-db
    prometheus.io/path: /metrics
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  podPriorityClassName: high-priority
  postgresql:
    parameters:
      checkpoint_completion_target: "0.9"
      default_statistics_target: "100"
      effective_cache_size: 1536MB
      effective_io_concurrency: "200"
      log_connections: "off"
      log_destination: stderr
      log_disconnections: "off"
      log_statement: none
      logging_collector: "off"
      maintenance_work_mem: 128MB
      max_connections: "150"
      max_parallel_maintenance_workers: "1"
      max_parallel_workers: "2"
      max_parallel_workers_per_gather: "1"
      max_wal_size: 4GB
      max_worker_processes: "2"
      min_wal_size: 1GB
      random_page_cost: "1.1"
      shared_buffers: 512MB
      tcp_keepalives_count: "0"
      tcp_keepalives_idle: "0"
      tcp_keepalives_interval: "0"
      wal_buffers: 16MB
      work_mem: 3495kB
    version: "11"
  resources:
    limits:
      cpu: "2"
      memory: 16Gi
    requests:
      cpu: 200m
      memory: 4Gi
  sidecars:
  - env:
    - name: DATA_SOURCE_URI
      value: localhost/netseva?sslmode=disable
    - name: DATA_SOURCE_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: postgres.infra-postgres-db.credentials
    - name: DATA_SOURCE_PASS
      valueFrom:
        secretKeyRef:
          key: password
          name: postgres.infra-postgres-db.credentials
    - name: PG_EXPORTER_EXTEND_QUERY_PATH
      value: /config/queries.yaml
    image: quay.io/anuta/postgres_exporter:v0.8.0
    name: postgres-exporter
    ports:
    - containerPort: 9187
      name: pg-metrics
      protocol: TCP
  teamId: infra
  users:
    netseva:
    - login
  volume:
    size: 100Gi
    storageClass: postgres-storage

```
