### ISSUE TITLE
[pooler] cant get pgbouncer/pooler metrics

### ISSUE THREAD

**Issue by haroonb** [zalando/postgres-operator#2336]
- **Which image of the operator are you using?** ghcr.io/zalando/spilo-15:3.0-p1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [Bare Metal K8s]
- **Are you running Postgres Operator in production?** [no]
- **Type of issue?** [question]

Hello I'm having trouble getting the https://github.com/spreaker/prometheus-pgbouncer-exporter to work with the pooler deployed by the `postgres-operator`. I previously used the https://github.com/edoburu/docker-pgbouncer in conjunction with the above mentioned exporter successfully.

Tahnks for any help or suggestions provided.

error from pooler pod
```
ops-postgres-cluster-pooler-5b4b989497-zvhl5 connection-pooler 2023-05-23 12:02:41.512 UTC [1] WARNING C-0x7f95e78a6190: pgbouncer/postgres@10.244.7.10:33976 pooler error: not allowed
```
error from pgbouncer-exporter pod
```
pgbouncer-exporter-7b5b4bc57c-nsqcq pgbouncer-exporter {"asctime": "2023-05-23 12:02:41", "levelname": "ERROR", "message": "Unable fetch metrics from postgresql://postgres:***@ops-postgres-cluster-pooler:5432/pgbouncer", "exception": "FATAL:  not allowed\n"}
```
I installed the cluster with the following ansible playbook.
```yaml
---
- hosts: "k8s-master"
  gather_facts: no
  tasks:

    - name: install postgres-operator
      # browsable at https://github.com/zalando/postgres-operator/blob/v1.9.0/charts/postgres-operator/values.yaml
      kubernetes.core.helm:
        state: present
        wait: yes
        atomic: yes
        create_namespace: yes
        release_name: postgres-operator
        release_namespace: postgres
        chart_ref: postgres-operator
        chart_repo_url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
        chart_version: 1.10.0
        release_values:
          podAnnotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          configGeneral:
            docker_image: ghcr.io/zalando/spilo-15:3.0-p1
          configKubernetes:
            enable_pod_antiaffinity: true
            pod_antiaffinity_preferred_during_scheduling: true
            pod_antiaffinity_topology_key: kubernetes.io/hostname
            custom_pod_annotations:
              cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          configConnectionPooler:
            connection_pooler_max_db_connections: 100
            connection_pooler_number_of_instances: 3
            connection_pooler_default_cpu_request: "100m"
            connection_pooler_default_memory_request: "10Mi"
            connection_pooler_default_cpu_limit: "500m"
            connection_pooler_default_memory_limit: "100Mi"
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 100Mi

    - name: create ops postgres cluster
      kubernetes.core.k8s:
        namespace: postgres
        definition:
          # browsable at https://github.com/zalando/postgres-operator/blob/v1.9.0/manifests/complete-postgres-manifest.yaml
          apiVersion: "acid.zalan.do/v1"
          kind: postgresql
          metadata:
            name: "{{ item.name }}-postgres-cluster"
          spec:
            dockerImage: ghcr.io/zalando/spilo-15:3.0-p1
            teamId: "{{ item.name }}"
            numberOfInstances: 3
            enableConnectionPooler: true
            enableReplicaConnectionPooler: true
            patroni:
              pg_hba:
                - local       all         all                     trust
                - local       replication standby                 md5
                - hostssl     replication standby   all           md5
                - hostssl     replication postgres  all           md5
                - hostssl     all         all       all           md5
                - hostnossl   all         all       all           reject
            postgresql:
              version: "15"
              parameters:  # Expert section
                tcp_keepalives_count: "5"
                tcp_keepalives_interval: "60"
                tcp_keepalives_idle: "60"
                shared_buffers: "{{ item.shared_buffers }}"
                max_connections: "300"
                log_statement: "none"
            volume:
              size: "{{ postgres_pvsize }}Gi"
              storageClass: "{{ storage_class_type }}"
            resources:
              requests:
                cpu: "{{ item.request_cpu }}"
                memory: "{{ item.request_mem }}"
              limits:
                cpu: "{{ item.limit_cpu }}"
                memory: "{{ item.limit_mem }}"
      loop:
        - { name: 'ops', namespace: 'postgres', shared_buffers: '1GB', request_cpu: '100m', request_mem: '2000Mi', limit_cpu: '1000m', limit_mem: '3000Mi' }
```

I installed the exporter with the following playbook.
```yaml
# This Playbooks installs the pgbouncer exporter (https://github.com/spreaker/prometheus-pgbouncer-exporter)
---
- hosts: "k8s-master"
  gather_facts: yes

  tasks:

    - name: install pgbouncer exporter
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            annotations:
            labels:
              app: pgbouncer-exporter
            name: pgbouncer-exporter
            namespace: postgres
          spec:
            selector:
              matchLabels:
                app: pgbouncer-exporter
            template:
              metadata:
                annotations:
                  prometheus.io/port: "9127"
                  prometheus.io/scrape: "true"
                  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
                labels:
                  app: pgbouncer-exporter
              spec:
                containers:
                - env:
                  - name: PGSSLMODE
                    value: require
                  - name: PGBOUNCER_EXPORTER_HOST
                    value: 0.0.0.0
                  - name: PGBOUNCER_HOST
                    value: ops-postgres-cluster-pooler
                  - name: PGBOUNCER_PORT
                    value: "5432"
                  - name: PGBOUNCER_USER
                    valueFrom:
                      secretKeyRef:
                        key: username
                        name: postgres.ops-postgres-cluster.credentials.postgresql.acid.zalan.do
                  - name: PGBOUNCER_PASS
                    valueFrom:
                      secretKeyRef:
                        key: password
                        name: postgres.ops-postgres-cluster.credentials.postgresql.acid.zalan.do
                  image: spreaker/prometheus-pgbouncer-exporter:2.1.1
                  imagePullPolicy: IfNotPresent
                  name: pgbouncer-exporter
                  resources:
                    limits:
                      cpu: 50m
                      memory: 40Mi
                    requests:
                      cpu: 10m
                      memory: 20Mi


```
