### ISSUE TITLE
How to Set the Time Zone of PostgreSQL Pod？

### ISSUE THREAD

**Issue by lkgGitHub** [zalando/postgres-operator#2356]
I found that the time zones in the PostgreSQL pod are all UTC, but it's not UTC.

Which image of the operator are you using?
registry.opensource.zalan.do/acid/postgres-operator:v1.8.2
spilo-14:2.1-p7

Where do you run it - cloud or metal? Kubernetes or OpenShift?
Kubernetes

Are you running Postgres Operator in production? [yes | no]
yes

**Comment by seekingua** [comment]
Add this to your cr
```
  additionalVolumes:
    - name: 'localtime'
      mountPath: '/etc/localtime'
      volumeSource:
        hostPath:
          path: '/etc/localtime'
```

**Comment by lkgGitHub** [comment]
add cr in postgresql 

```yaml
  additionalVolumes:
    - name: 'localtime'
      mountPath: '/etc/localtime'
      volumeSource:
        hostPath:
          path: '/etc/localtime'
```
