### ISSUE TITLE
readiness probe failure when using /readiness

### ISSUE THREAD

**Issue by devulm** [zalando/postgres-operator#2373]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. acid/postgres-operator:v1.8.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Openshift
- **Are you running Postgres Operator in production?** yes 
- **Type of issue?** Bug

readiness probe fails for the postgres pods when using /readiness as the path
It works fine if i update the path to /patroni

Have opened an issue with spilo as well. but no response there

https://github.com/zalando/spilo/issues/892

**Comment by devulm** [comment]
Any update here, is there any way to configure the the path in the operatorconfiguration

**Comment by devulm** [comment]
We are using image spilo-12:1.6-p3 on openshift 4.11 , via the postgres operator

The readiness does not work when path is set to /readiness . But works when updating it /patroni

let me know if i need to share the operatorconfiguration CRD.

```
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: 8008
            scheme: HTTP
          initialDelaySeconds: 6
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
```
Below config works.
```
   - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /patroni
            port: 8008
            scheme: HTTP
          initialDelaySeconds: 6
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
```
