### ISSUE TITLE
Setting - allowedSourceRanges: [] does not work

### ISSUE THREAD

**Issue by thpang** [zalando/postgres-operator#2385]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.9.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** metal - OSS Upstream Kubernetes
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

The services being created to not honor the empty list when assigned to `allowedSourceRanges`

This causes issues on bare metal systems that do not handle the `loadBalancerSourceRanges` entry in the service manifest.

If I set the following:
```yaml
allowedSourceRanges: []
```
It is always replaced by:
```yaml
  loadBalancerSourceRanges:
    - 127.0.0.1/32
```
in the service for the database

Here is the yaml being applied:
```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  namespace: "zalando-cluster-default"
  name: "zalando-cluster-default-db"
spec:
  teamId: "sas"
  enableMasterLoadBalancer: True
  enableReplicaLoadBalancer: False
  enableConnectionPooler: False
  enableReplicaConnectionPooler: False
  enableMasterPoolerLoadBalancer: False
  enableReplicaPoolerLoadBalancer: False
  numberOfInstances: 1
  allowedSourceRanges: []
  postgresql:
    version: "15"
    parameters:  # Expert section
      max_prepared_transactions: "1024"
      max_connections: "1024"
      log_statement: "all"
  volume:
    size: "50Gi"
    storageClass: "default"
```

Some general remarks when posting a bug report:
- Please, check the operator, pod (Patroni) and postgresql logs first. When copy-pasting many log lines please do it in a separate GitHub gist together with your Postgres CRD and configuration manifest.
- If you feel this issue might be more related to the [Spilo](https://github.com/zalando/spilo/issues) docker image or [Patroni](https://github.com/zalando/patroni/issues), consider opening issues in the respective repos.
