### ISSUE TITLE
CRD problem while installing postgres-operator via helm

### ISSUE THREAD

**Issue by PatrickHuetter** [zalando/postgres-operator#2438]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**
registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
helm Chart 1.10.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**
Bare Metal RKE2 Cluster with k8s 1.28
- **Are you running Postgres Operator in production?**
Not yet.
- **Type of issue?** 
Question or bug report.

Hi together,
i would like to install the postgres-operator in the current stable version 1.10.1 via helm.
I've used the newest helm release within your repository but can't install the operator.

Error message:
``` 
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "postgres-operator" namespace: "postgresql-system" from "": no matches for kind "OperatorConfiguration" in version "acid.zalan.do/v1" ensure CRDs are installed first
```

This is my helmfile:
```
repositories:
  - name: postgres-operator-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

releases:
  - name: postgres-operator
    namespace: postgresql-system
    createNamespace: true
    chart: postgres-operator-charts/postgres-operator
    version: 1.10.1
    values:
      - configGeneral:
          enable_crd_registration: true
```

Do i have to install the CRDs manually before using helmfile apply/ helm install?
