### ISSUE TITLE
S3 location is missing UID when configured against custom S3 provider

### ISSUE THREAD

**Issue by bo0ts** [zalando/postgres-operator#2457]
We are running:

- registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
- OpenShift 4.12
- S3 is provided through MinIO
- Operator is installed through Helm Charts

We use the following configmap to configure our postgres pods:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-pod-config
data:
  AWS_ACCESS_KEY_ID: ...
  AWS_SECRET_ACCESS_KEY: ...
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_REGION: us-east-1
  AWS_ENDPOINT: http://s3-backup.intern:9000
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  WALG_DISABLE_S3_SSE: "true"
  WAL_S3_BUCKET: backup
```

After that all backups end up in `s3://backup/spilo/${NAMESPACE_NAME}-${INSTANCE_NAME}/wal/${PG_VERSION}` and the cluster UID is missing.

Is this intentional and why is this the case? Backup/Restore works except the restore in-place case, which we would like to see working as well.
