### ISSUE TITLE
User Permission are not Synced

### ISSUE THREAD

**Issue by k86td** [zalando/postgres-operator#2467]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
I am using `registry.opensource.zalan.do/acid/postgres-operator:v1.10.1`.
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Metal, currently using `Kind`.
- **Are you running Postgres Operator in production?** [yes | no]
Not yet.
- **Type of issue?** [Bug report, question, feature request, etc.]
Bug report / question.

## Issue

When creating a `postgresql` resource with users with a role of `superuser`, if the cluster is edited, the roles are not updated.

### First Update

I use the following manifest for the cluster initialization:
```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    tlepine:
    - login
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
```

The cluster is fine and the users permissions works as expected. The user `tlepine` has `superuser` permissions.

### Second Update

Then, I modify the manifest with the following:
```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    tlepine:
    - nologin
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
```

The user `tlepine` still has `superuser` privileges. Is this normal behaviour? I tried to check around to find if anyone has a similar issue but couldn't find anything. I can see in the logs of the operator that the user role is now `nologin`, but the changes are not reflected. I tried restarted the StatefulSet with no success.

Thanks
