### ISSUE TITLE
How to set the TimescaleDB versions in the instance deployment manifest.yaml?

### ISSUE THREAD

**Issue by Jpignet** [zalando/postgres-operator#2477]
I use the helm for installing zalando operator. So, I use manifest.yaml for installing my postgres instances.

In my manifest.yaml i install and use the timescaleDB extension like that 

``` 
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    install:
      extensions:
        timescaledb: public
  timescaledb:
    version: 2.10.0
    
  postgresql:
    version: "15"
    parameters:
      shared_preload_libraries: timescaledb
```

I know that the Zalando image takes several versions of timescale DB.

However, I can not to set the version in the manifest.yaml. How to do?

It is possible to use a configMap by specifying the versions, but I would like to avoid making it complicated.
