### ISSUE TITLE
Helm chart lacks value for "loadBalancerSourceRanges"

### ISSUE THREAD

**Issue by stefanbildl** [zalando/postgres-operator#2494]
- **Are you running Postgres Operator in production?**  yes
- **Type of issue?** [feature request]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?**  [Bare Metal K8s]
- **Type of issue?** [feature request]

# Regarding Helm chart postgres-operator-1.10.1:

I am using a loadbalancer as service type. The helm chart doesn't provide a way to specify the loadBalancerSourceRanges in the service.yaml 

It defaults to this: 

```yaml
  loadBalancerSourceRanges:
  - 127.0.0.1/32
```
My user supplied values 

```yaml
USER-SUPPLIED VALUES:
configLoadBalancer:
  enable_master_load_balancer: true
service:
  type: LoadBalancer
```
