### ISSUE TITLE
pg_basebackup is killed

### ISSUE THREAD

**Issue by ArneRanvik** [zalando/postgres-operator#2495]
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
   - Operator: v1.8.2
   - Patronictl version 2.1.4
   - Spilo image: spilo-14:2.1-p6
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
   - Kubernetes Private
- **Are you running Postgres Operator in production?** [yes | no]
   - yes
- **Type of issue?** [Bug report, question, feature request, etc.]
   - Bug report/Questions

We have several postgres clusters that backup to a self hosted S3 server (minio). Two of them are unable to produce any base backups for some reason. Running a manual backup by entering shell of pod (spilo-role: master) and running:
```
export PGPASSWORD=super-secret
export PGUSER=postgres
root@special-db-1:/home/postgres# envdir "/run/etc/wal-e.d/env" /scripts/postgres_backup.sh "/home/postgres/pgdata/pgroot/data"
```

Produces output:
```
2023-12-12 20:07:59.477 - /scripts/postgres_backup.sh - I was called as: /scripts/postgres_backup.sh /home/postgres/pgdata/pgroot/data
2023-12-12 20:07:59.740 - /scripts/postgres_backup.sh - producing a new backup
INFO: 2023/12/12 20:07:59.860122 Calling pg_start_backup()
INFO: 2023/12/12 20:08:00.212976 Starting a new tar bundle
INFO: 2023/12/12 20:08:00.213022 Walking ...
INFO: 2023/12/12 20:08:00.217100 Starting part 1 ...
Killed
```
Without any further information about why the process was killed. Doing the same on another cluster where this works produces a base backup successfully.

Here is my cluster "postgresql" definition:
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: special-db
  namespace: tenant-special
  labels:
    application: special-db
    environment: production
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-14:2.1-p6
  teamId: "special"
  numberOfInstances: 3
  users:
    someuser:
      - superuser
      - createdb

  databases:
    apidb: someuser

  postgresql:
    version: "14"

  volume:
    size: 10.0Gi
    storageClass: local

  additionalVolumes:
    - name: socket-directory
      mountPath: /var/run/postgresql
      targetContainers:
        - all
      volumeSource:
        emptyDir: {}

  enableShmVolume: true
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"

  sidecars:
    - name: exporter
      image: bitnami/postgres-exporter:0.10.1
      ports:
        - name: pg-exporter
          containerPort: 9187
          protocol: TCP
      resources:
        requests:
          cpu: 30m
          memory: 128Mi
      env:
        - name: CLUSTER_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['cluster-name']
        - name: DATA_SOURCE_NAME
          value: >-
            host=/var/run/postgresql user=postgres
            application_name=postgres_exporter
        - name: PG_EXPORTER_CONSTANT_LABELS
          value: "release=$(CLUSTER_NAME),namespace=$(POD_NAMESPACE)"

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: special-db
  namespace: tenant-special
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      application: spilo      
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: infra-postgres
        podSelector:
          matchLabels:
            app.kubernetes.io/name: postgres-operator
    - ports:
      - port: 8008
      - port: 8080
      - port: 5432
```

And backup overlay is configured with the following env var:
```
AWS_ENDPOINT: http://100.74.89.174:9000
AWS_REGION: no-grimstad-1
WAL_BUCKET_SCOPE_PREFIX: ""
WAL_BUCKET_SCOPE_SUFFIX: ""
USE_WALG_BACKUP: "true"
USE_WALG_RESTORE: "true"
BACKUP_SCHEDULE: "45 00 * * *"
AWS_S3_FORCE_PATH_STYLE: "true"
WALG_DISABLE_S3_SSE: "true"
BACKUP_NUM_TO_RETAIN: "5"
CLONE_USE_WALG_RESTORE: "true"
WALG_COMPRESSION_METHOD: "brotli"
WAL_S3_BUCKET: "my-bucket/special-db"

- name: AWS_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: special-db-extra-env
      key: AWS_ACCESS_KEY_ID
      optional: true
- name: AWS_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: special-db-extra-env
      key: AWS_SECRET_ACCESS_KEY
      optional: true
```

Are there any way to get logs on why pg_basebackup was killed?
