### ISSUE TITLE
"spec.teamId: Required value", even when Teams API is disabled

### ISSUE THREAD

**Issue by jochenhebbrecht** [zalando/postgres-operator#2526]
- **Which image of the operator are you using?** registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** cloud - Azure AKS
- **Are you running Postgres Operator in production?** no
- **Type of issue?** question

Hi,

I have the `postgres-operator` installed using a Helm chart: 
```yaml
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    chart: postgres-operator
    targetRevision: 1.10.1
    helm:
      values: |
        configLoadBalancer:
          db_hosted_zone: dev.opc.tomtomgroup.com
          master_dns_name_format: "{cluster}.{hostedzone}"
        configTeamsApi:
          enable_teams_api: false
```

As you can see, we disable the Teams API. However, when I try to deploy a PostgreSQL database server, and I don't specify a team like:
```yaml
  teamId: "acid"
```
... I'm getting follow error during deployment:
```
"spec.teamId: Required value"
```

Is it possible the field `teamId` is *always* required, even if the Teams API is disabled?
