### ISSUE TITLE
Cant update timescale parameter

### ISSUE THREAD

**Issue by boskiv** [zalando/postgres-operator#2550]
Updating parameter in CRD but nothing applied, only max_standby_archive_delay and max_standby_streaming_delay
```
  postgresql:
    parameters:
      max_connections: '300'
      shared_buffers: '80MB'
      max_standby_archive_delay: "900"
      max_standby_streaming_delay: "900"
      timescaledb.max_background_workers: "64"
    version: "15"
 ```

```
postgres-operator-8595fcf9bc-c47r4 postgres-operator time="2024-02-21T11:54:54Z" level=debug msg="patching Postgres config via Patroni API on pod db-cluster-core/db-cluster-core-0 with following options: {\"postgresql\":{\"parameters\":{\"max_standby_archive_delay\":\"900\",\"max_standby_streaming_delay\":\"900\"}}}" cluster-name=db-cluster-core/db-cluster-core pkg=cluster
```
