### ISSUE TITLE
Allow specifying nodeSelector for cloned database

### ISSUE THREAD

**Issue by dmildh-absci** [zalando/postgres-operator#2572]
Please, answer some short questions which should help us to understand your problem / question better?

- Currently using registry.opensource.zalan.do/acid/postgres-operator:v1.10.1
- Kubernetes
- Running in Pord
- Bug report

When trying to create a clone database from s3 specifying nodeSelectors I get the following error:

```Error from server (BadRequest): error when creating "db-clone-test.yaml": postgresql in version "v1" cannot be handled as a postgresql: strict decoding error: unknown field "spec.nodeSelect```

My yaml is pretty basic and looks like 

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: db-clone
  namespace: test
spec:
  clone:
    uid: "0a4ascaf-159e-4cac-8ee3-5292fe46f5"
    cluster: "source-db"
    timestamp: "2024-03-12T00:00:33-08:00"
...
  nodeSelector:
    node-role.kubernetes.io/cluster-apps: ""
  tolerations:
    - key: node-role.kubernetes.io/cluster-apps
      operator: Equal
      effect: NoSchedule
```
