### ISSUE TITLE
`EnableDBAccess` defaults to `false` when using `OperatorConfiguration`

### ISSUE THREAD

**Issue by andsens** [zalando/postgres-operator#2575]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** `registry.opensource.zalan.do/acid/postgres-operator:v1.10.1`
- **Where do you run it** K8S with kops on AWS
- **Are you running Postgres Operator in production?** Not yet
- **Type of issue?** Bug report

When using `OperatorConfiguration` `EnableDBAccess` is `false`, when not specifying it as evidenced by the startup output (kudos for printing that during startup btw):
```
...
time="2024-03-13T14:19:41Z" level=info msg="   \"EnableEBSGp3Migration\": false," pkg=controller
time="2024-03-13T14:19:41Z" level=info msg="   \"EnableEBSGp3MigrationMaxSize\": 1000," pkg=controller
time="2024-03-13T14:19:41Z" level=info msg="   \"DebugLogging\": false," pkg=controller
time="2024-03-13T14:19:41Z" level=info msg="   \"EnableDBAccess\": false," pkg=controller
time="2024-03-13T14:19:41Z" level=info msg="   \"EnableTeamsAPI\": false," pkg=controller
time="2024-03-13T14:19:41Z" level=info msg="   \"EnableTeamSuperuser\": false," pkg=controller
time="2024-03-13T14:19:41Z" level=info msg="   \"TeamAdminRole\": \"admin\"," pkg=controller
...
```

[The documentation states it should be `true`](https://github.com/zalando/postgres-operator/blob/8bd9080798b306190ff537e0b49744a40a848d4d/docs/reference/operator_parameters.md#debugging-the-operator).

The OperatorConfiguration looks like this (slightly edited):
```
---
apiVersion: acid.zalan.do/v1
kind: OperatorConfiguration
metadata:
  name: main
configuration:
  enable_crd_registration: false
  kubernetes:
    watched_namespace: "*"
    inherited_labels:
    - app.kubernetes.io/name
    cluster_labels:
      app.kubernetes.io/component: postgresql
    pod_antiaffinity_preferred_during_scheduling: true
    pod_antiaffinity_topology_key: topology.kubernetes.io/zone
  teams_api:
    enable_teams_api: false
```

Adding
```
  debug:
    enable_database_access: true
```
 fixes this issue.
