### ISSUE TITLE
How to update a custom image in Postgres with custom hba.conf

### ISSUE THREAD

**Issue by bhanotjyoti** [zalando/postgres-operator#2610]
I am using Postgres cluster and Postgres operator in production. I have updated the `pg_hba.conf` manually and reloaded the configuration. How can I update the custom image in Postgres file as I don't see a spec section 

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- with .Values.databases }}
  databases:
  {{ toYaml . | indent 2 }}
  {{- end }}
  numberOfInstances: {{ .Values.replicas }}
  postgresql:
    version: "15"
  {{- with .Values.resources }}
  resources:
{{ toYaml . | indent 4 }}
  {{- end }}
  teamId: {{ .Values.teamId }}
  {{- with .Values.users }}
  users:
{{ toYaml . | indent 4 }}
  {{- end }}
  volume:
    size: {{ .Values.volume.storage }}
    storageClass: {{ .Values.volume.storageClass }}
  enableLogicalBackup: {{ default "true"  .Values.logicalBackup }}
  sidecars:
  - image: wrouesnel/postgres_exporter
    name: exporter
    ports:
    - containerPort: 9187
      name: exporter
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
```

Can someone help
