### ISSUE TITLE
postgres-operator-ui:v1.12.0 exec format error on ARM64

### ISSUE THREAD

**Issue by acelinkio** [zalando/postgres-operator#2649]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 
ghcr.io/zalando/postgres-operator:v1.12.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** 
metal.  kubernetes. k3s .v1.29.2+k3s1 
- **Are you running Postgres Operator in production?**
no
- **Type of issue?** 
bug

On v1.12.0 of the UI, I am getting exec error on ARM based host.  I see there is an ARM based image published to ghcr.io but still getting this exec format error.  Did not have this error on v1.11.0 of the ui.  Also do NOT have this error with 1.12.0 of the postgres-operator. 

```log
exec /usr/local/bin/python: exec format error
```

**Comment by hemakshis** [comment]
Hi, I am facing this issue in my k8s cluster when upgrading helm version to v1.12.0 -

```
Failed to pull image "registry.opensource.zalan.do/acid/postgres-operator:v1.12.0": rpc error: code = NotFound desc = failed to pull and unpack image "registry.opensource.zalan.do/acid/postgres-operator:v1.12.0": failed to resolve reference "registry.opensource.zalan.do/acid/postgres-operator:v1.12.0": registry.opensource.zalan.do/acid/postgres-operator:v1.12.0: not found
```

This is how I am applying the helm chart -
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  releaseName: postgres-operator
  chart:
    spec:
      chart: postgres-operator
      version: "1.12.0"
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
        namespace: postgres-operator
  interval: 10m
  values:
    installCRDs: true
    extraArgs: []
    image:
      registry: registry.opensource.zalan.do
      repository: acid/postgres-operator
      tag: v1.12.0
      pullPolicy: "IfNotPresent"
```
