### ISSUE TITLE
Image postgres-operator:v1.12.0 not able in zalando registry

### ISSUE THREAD

**Issue by hemakshis** [zalando/postgres-operator#2650]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**

ghcr.io/zalando/postgres-operator:v1.12.0

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]

AWS

- **Are you running Postgres Operator in production?** [yes | no]

Not yet...

- **Type of issue?** [Bug report, question, feature request, etc.]

Bug

Unable to pull v1.12.0 image - 
```
Failed to pull image "registry.opensource.zalan.do/acid/postgres-operator:v1.12.0": rpc error: code = NotFound desc = failed to pull and unpack image "registry.opensource.zalan.do/acid/postgres-operator:v1.12.0": failed to resolve reference "registry.opensource.zalan.do/acid/postgres-operator:v1.12.0": registry.opensource.zalan.do/acid/postgres-operator:v1.12.0: not found
```

My postgres-operator helm release yaml -
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  releaseName: postgres-operator
  chart:
    spec:
      chart: postgres-operator
      version: "1.12.0"
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
        namespace: postgres-operator
  interval: 10m
  values:
    installCRDs: true
    extraArgs: []
    image:
      registry: registry.opensource.zalan.do
      repository: acid/postgres-operator
      tag: v1.12.0
      pullPolicy: "IfNotPresent"
  ...
  ...
  ...
```
