### ISSUE TITLE
Improving Postgres CR Status with Additional Details

### ISSUE THREAD

**Issue by ravina-c** [zalando/postgres-operator#2669]
- **Which image of the operator are you using?** e.g. ghcr.io/zalando/postgres-operator:v1.12.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** Bare Metal K8s
- **Are you running Postgres Operator in production?** yes 
- **Type of issue?**   feature request

Hi,
Currently the status field of the `postgresql` CR looks something like:

```
status:
  PostgresClusterStatus: Running
```

I'd like to propose following changes to the status:
- **Number Of Instances** can be added to the status to indicate the number of running pods associated with the Postgres CR 
- **Label Selector**  can be included in the status to define the label criteria applied to pods linked with the Postgres CR and this is also required for scale subresource.
- **Observed generation:** It would be useful in identifying if the operator has made any changes to the CR after the CR spec has been updated.
- **LastTransitionTime**  can also be added to to provide insights into the state and lifecycle of resources.

post these changes, the status field of the `postgresql` CR would look something like this:
```
status:
  labelSelector: cluster-name=postgres-cluster-pvc-5
  numberOfInstances: 3
  conditions:
  - lastTransitionTime: "2024-06-03T10:18:04Z"
    status: "True"
    type: postgresClusterStatusRunning
  observedGeneration: 2
```
Along with this, I am proposing to add scale subresource in the CRD of `postgresql` as well, which would use some of the fields proposed above, and then this scale subresource can be further used by external systems to scale or monitor the CR. This scale subresource would look something like this:
```
 subresources:
   status: {}
   scale:
       specReplicasPath: .spec.numberOfInstances  
       statusReplicasPath: .status.numberOfInstances  
       labelSelectorPath: .status.labelSelector
```
