### ISSUE TITLE
Cluster creation getting stuck on StatefulSet pending

### ISSUE THREAD

**Issue by JanCizmar** [zalando/postgres-operator#2679]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** 

ghcr.io/zalando/postgres-operator:v1.12.2

- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
Azure AKS

- **Are you running Postgres Operator in production?** [yes | no]
not yet

- **Type of issue?** [Bug report, question, feature request, etc.]
Bug report/question

## Steps to reproduce
1. Create new cluster using the UI on AKS
```
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: tolgee-testing
  namespace: default
spec:
  allowedSourceRanges: null
  databases:
    tolgee: tolgee
  numberOfInstances: 1
  postgresql:
    version: '16'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    tolgee: []
  volume:
    size: 10Gi
```
2. hit create
3. It gets stuck on the `StatefulSet pending`
4. There is no ReplicaSet created

The logs:
```
│ time="2024-06-28T13:34:02Z" level=info msg="creating a new Postgres cluster" cluster-name=default/testing pkg=controller wo │
│ time="2024-06-28T13:34:02Z" level=info msg="endpoint \"default/testing\" has been successfully created" cluster-name=defaul │
│ time="2024-06-28T13:34:02Z" level=info msg="master service \"default/testing\" has been successfully created" cluster-name= │
│ time="2024-06-28T13:34:02Z" level=info msg="replica service \"default/testing-repl\" has been successfully created" cluster │
│ time="2024-06-28T13:34:02Z" level=debug msg="team API is disabled" cluster-name=default/testing pkg=cluster worker=0        │
│ time="2024-06-28T13:34:02Z" level=debug msg="team API is disabled" cluster-name=default/testing pkg=cluster worker=0        │
│ time="2024-06-28T13:34:02Z" level=info msg="users have been initialized" cluster-name=default/testing pkg=cluster worker=0  │
│ time="2024-06-28T13:34:02Z" level=info msg="syncing secrets" cluster-name=default/testing pkg=cluster worker=0              │
│ time="2024-06-28T13:34:02Z" level=debug msg="created new secret default/standby.testing.credentials.postgresql.acid.zalan.d │
│ time="2024-06-28T13:34:02Z" level=debug msg="created new secret default/postgres.testing.credentials.postgresql.acid.zalan. │
│ time="2024-06-28T13:34:02Z" level=info msg="secrets have been successfully created" cluster-name=default/testing pkg=cluste │
│ time="2024-06-28T13:34:02Z" level=info msg="pod disruption budget \"default/postgres-testing-pdb\" has been successfully cr │
```
