### ISSUE TITLE
regsitry/repository/tag-approach for spilo and logical-backup image

### ISSUE THREAD

**Issue by olivier-derom** [zalando/postgres-operator#2689]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** ghcr.io/zalando/postgres-operator:v1.12.2
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** AWS K8s/EKS
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** feature request

Some general remarks when posting a bug report:
- Please, check the operator, pod (Patroni) and postgresql logs first. When copy-pasting many log lines please do it in a separate GitHub gist together with your Postgres CRD and configuration manifest.
- If you feel this issue might be more related to the [Spilo](https://github.com/zalando/spilo/issues) docker image or [Patroni](https://github.com/zalando/patroni/issues), consider opening issues in the respective repos.

When using the helm chart, the operator allows to generate the image through
```
image:
  registry: ghcr.io
  repository: zalando/postgres-operator
  tag: v1.12.2
```
This is a good approach, as we can simply update the registry to point to our private-registry, while still rely on the Chart's default values to select the correct tag.
e.g.
```
image:
  registry: my-pullthrough-registry.com
  repository: zalando/postgres-operator
  tag: v1.12.2
```

However, the Spilo docker image `configGeneral.docker_image` and logicalbackup image `configLogicalBackup.logical_backup_docker_image` use a full image path, which means we cannot reply on the Chart's default values to update the `tag` when updating the chart version, as we use a custom registry.

It would be a small effort to follow the same, more dynamic regsitry/repository/tag-approach.

Let me know what you think.
Thanks!
