### ISSUE TITLE
Postgresql service timeout 3 of 5 requests without selector for master

### ISSUE THREAD

**Issue by OlegShal** [zalando/postgres-operator#2701]
ghcr.io/zalando/postgres-operator:v1.12.2
Runned in 1.25 k8s by vmware tanzu for dev/stage envs
It's seems like a bug without an added selector for service for master pod
```
labels:
    application: spilo
    cluster-name: stage-psql
    spilo-role: master

```
service response to a request 1 of 2-3 times. 
30 requests - 10 response, other 20 - timeout. Fully fixed with setting selector. Is there option of adding a selector by default to service, or any thougths how to fix it without adding a selector?
