### ISSUE TITLE
WAL-G backup broken since 1.13.0, works in 1.12.2

### ISSUE THREAD

**Issue by olivier-derom** [zalando/postgres-operator#2747]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?** v1.13.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** EKS
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug report

We create logical backups (pg_dump) and WAL-G+basebackups for our clusters.
We use a k8s service account which is bound to an IAM role for S3 access.
postgres-operator is deployed using helm.

When running operator version 1.12.2 (and spilo 16:3.2-p3), both logicalbackup cronjob and WAL-G+basebackups work as intented.
I validate the WAL backup using 
`PGUSER=postgres`
`envdir "/run/etc/wal-e.d/env" /scripts/postgres_backup.sh "/home/postgres/pgdata/pgroot/data"`

When I update the postgres-operator to 1.13.0 (and spilo to 16:3.3-p1), the logicalbackups still work, but the WAL+basebackup do not work anymore.
When manually trying to create a basebackup with the same command, I get error:
```
create S3 storage: create new AWS session: configure session: assume role by ARN: InvalidParameter: 1 validation error(s) found.
- minimum field size of 2, AssumeRoleInput.RoleSessionName.
```

It seems to be an error specific to using a service account assuming an IAM role to access S3, specifically when running basebackup.
Logicalbackup are able to put the pg_dump on S3 via the same authentication method

No other values were changed other than the spilo image, and helm chart version.

Let me know if you need additional information.

**Comment by FxKu** [comment]
Oh no! This doesn't sound nice. Can you share some snippets or your operator configuration and service account so we can try to replicate. Our setup is not that different but our backups continue to run.

Quite a few things have change and in your case maybe require a different configuration. Spilo has some config means but likely not managable yet by the operator.

**Comment by olivier-derom** [comment]
@FxKu 
Sure! Here are some snippets:

<details>
<summary>SA Yaml (manually deployed as additional resource, not part of zalando postgres helm) </summary>

```
apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
- name: mysecret
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::0123456789:role/my-IAM-role-w-S3-access
  labels:
    app.kubernetes.io/instance: postgres-operator
  name: postgres-operator
  namespace: dataplatform-prod
```
</details>

<details>
<summary>postgres operator helm values</summary>

```
postgres-operator:
  image:
    registry: privaterepo.com
    repository: zalando/postgres-operator
  imagePullSecrets:
    - name: mysecret

  configGeneral:
    # Spilo docker image, update manually when updating the operator
    # Tag and registry are not split, so we must update this manually and cannot rely on Helm default values
    docker_image: privaterepo.com/zalando/spilo-16:3.2-p3

  configKubernetes:
    app.kubernetes.io/managed-by: postgres-operator
    enable_secrets_deletion: true
    watched_namespace: dataplatform-dev
    cluster_labels:
      application: spilo
    cluster_name_label: cluster-name
    pod_environment_configmap: postgres-pod-config

    enable_pod_antiaffinity: true
    enable_readiness_probe: true

  configPostgresPodResources:
    default_cpu_limit: "1"
    default_cpu_request: 100m
    default_memory_limit: 500Mi
    default_memory_request: 100Mi
    min_cpu_limit: 250m
    min_memory_limit: 250Mi

  configDebug:
    debug_logging: true
    enable_database_access: true

  configAwsOrGcp:
    AWS_REGION: eu-west-1
    WAL_S3_BUCKET: mybucket/postgres-operator/WAL

  configLogicalBackup:
    # prefix for the backup job name
    logical_backup_job_prefix: "logical-backup-"
    logical_backup_provider: "s3"
    logical_backup_s3_region: "eu-west-1"
    logical_backup_s3_sse: "AES256"
    logical_backup_cronjob_environment_secret: ""
    # S3 retention time for stored backups for example "2 week" or "7 days"
    # recommended to also put S3 lifecycle policy on the bucket
    logical_backup_s3_retention_time: ""
    logical_backup_schedule: "30 00 * * *" # daily at 00.30 AM
    # Image for pods of the logical backup job (default pg_dumpall), update manually when updating the operator
    # Tag and registry are not split, so we must update this manually and cannot rely on Helm default values
    logical_backup_docker_image: privaterepo.com/zalando/postgres-operator/logical-backup:v1.12.2
    logical_backup_s3_bucket: mybucket/postgres-operator/logical-backups

  serviceAccount:
    create: false
    # The name of the ServiceAccount to use.
    name: postgres-operator

  podServiceAccount:
    name: postgres-operator
```
</details>

<details>
<summary>postgres cluster yaml</summary>

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: nessie-metastore
spec:
  postgresql:
    version: "16"
  teamId: "dataplatform"
  volume:
    size: 10Gi
  numberOfInstances: 1
  users:
    nessie:
      - superuser
      - createdb
    nessiegc:
      - superuser
      - createdb
  databases:
    nessiegc: nessiegc
    metastore: nessie

  enableLogicalBackup: true

  env:
  - name: AWS_REGION
    value: eu-west-1
  - name: WAL_S3_BUCKET
    value: mybucket/postgres-operator/WAL
  - name: USE_WALG_BACKUP
    value: "true"
  - name: USE_WALG_RESTORE
    value: "true"
  - name: BACKUP_SCHEDULE
    value: "00 * * * *"
  - name: BACKUP_NUM_TO_RETAIN
    value: "96" # For 1 backup per hour, keep 4 days of base backups
```
</details>

These are the config files of v1.12.2, but as stated earlier, the only thing I then changed is the helm chart version, and manually update spilo image and logical backup image as we use a private repo pull-through

Hope this can help!

**Comment by FxKu** [comment]
What if you change the docker image to the previous one? ghcr.io/zalando/spilo-16:3.2-p3 Does the v1.13.0 continues to work then?

**Comment by olivier-derom** [comment]
@FxKu I can confirm that the issue lies with the spilo image, by using chart 1.13.0 but spilo on 3.2-p3 the WAL archiving works correctly.

**Comment by nrobert13** [comment]
Sorry for chiming in, my question is not directly related but the snippets are very useful for my question. What is the reason of providing the wal_s3_bucket multiple times, once in operator config `configAwsOrGcp.WAL_S3_BUCKET` and once in the postgresql resource env `WAL_S3_BUCKET`? there would be a third way in the `pod_environment_secret/configmap` as well. I tried providing it only in the `pod_environment_secret` to keep all the archiving related S3 config in one place, but the `/run/etc/wal-e.d/env` is missing, so I assume the backup is not working either.

**Comment by nrobert13** [comment]
thanks for the quick reply. it make sense with the override, not sure though why must it be set in the operatorconfig. that seems to be the cuplrit of the missing `/run/etc/wal-e.d/env`.

**Comment by ihor-kokhan-onereach** [comment]
any news?

**Comment by FxKu** [comment]
Please, update the [docker_image](https://github.com/zalando/postgres-operator/blob/master/manifests/postgresql-operator-default-configuration.yaml#L6) parameter in the operator configuration to a newer Spilo image ghcr.io/zalando/spilo-16:3.3-p3

**Comment by FxKu** [comment]
Closing this ticket now that the new release is out. For 1.13.0 use a newer Spilo image, like I have mentioned.

**Comment by Jasper-Ben** [comment]
@FxKu Hi, not quite sure how the release of 1.13.0 fixes this, as the issue is still open in upstream wall-g and new spilo versions ship with newer wall-g versions, instead of the known-working v2.0.1, see: https://github.com/zalando/spilo/issues/1009

**Comment by gslaszlo** [comment]
Yes, this is still happening in [3.3-p3 ](https://github.com/zalando/spilo/releases/tag/3.3-p3).
The wal-g issue has [been solved](https://github.com/wal-g/wal-g/issues/1810), merged, but no wal-g release with the fixed version yet.
Is the only option for now is to downgrade to [3.2-p3](https://github.com/zalando/spilo/releases/tag/3.2-p3)?

**Comment by tomsozolins** [comment]
Have the same issue

Operator image: ghcr.io/zalando/postgres-operator:v1.14.0
Spilo image: ghcr.io/zalando/spilo-17:4.0-p2

**Comment by ihor-kokhan-onereach** [comment]
Same issue 
Operator image: ghcr.io/zalando/postgres-operator:v1.14.0
Spilo image: ghcr.io/zalando/spilo-17:4.0-p2

**Comment by Jasper-Ben** [comment]
> Same issue Operator image: ghcr.io/zalando/postgres-operator:v1.14.0 Spilo image: ghcr.io/zalando/spilo-17:4.0-p2

There is an open PR to fix this but unfortunately there has not been any maintainer activity there: https://github.com/zalando/spilo/pull/1121

**Comment by princessfruittt** [comment]
Same issue
Operator image: ghcr.io/zalando/postgres-operator:v1.14.0
Spilo image: ghcr.io/zalando/spilo-17:4.0-p2

**Comment by ihor-kokhan-onereach** [comment]
Same issue
Operator image: ghcr.io/zalando/postgres-operator:v1.14.0
Spilo image: ghcr.io/zalando/spilo-17:4.0-p3

**Comment by bootc** [comment]
I've just run into this problem again, over a year after I initially reported it (https://github.com/zalando/spilo/issues/1009).

Please re-open this issue, it's still a problem in the Postgres Operator as broken images have been the default for a long time now.

**Comment by a-thomas-22** [comment]
For anyone hitting this with IRSA and unable to upgrade Spilo immediately, we resolved it by adding an `initContainers` block to the postgresql CRD that pre-populates `AWS_ROLE_SESSION_NAME` in the WAL-G envdir before Spilo starts.

The root cause is that `configure_spilo.py` has a hardcoded list of AWS env vars it writes to `/run/etc/wal-e.d/env/`, and `AWS_ROLE_SESSION_NAME` is not included. Even though the var is set via `pod_environment_configmap`, the `envdir` command only reads from the filesystem directory, not the process environment.

Workaround — add this to your postgresql CRD spec (or the Helm values that template it):

```yaml
initContainers:
- name: walg-envdir-init
  image: busybox:1.36
  command:
  - sh
  - -c
  - mkdir -p /run/etc/wal-e.d/env && echo -n walg-backup > /run/etc/wal-e.d/env/AWS_ROLE_SESSION_NAME
  volumeMounts:
  - name: walg
    mountPath: /run/etc
additionalVolumes:
- name: walg
  mountPath: /run/etc
  targetContainers:
  - postgres
  volumeSource:
    emptyDir: {}
```

The `walg` emptyDir volume at `/run/etc` is the standard pattern for WAL-G backup-enabled clusters. The initContainer runs first, creates the envdir structure, and writes a valid session name so that when `envdir` executes WAL-G it picks up `AWS_ROLE_SESSION_NAME`.
