### ISSUE TITLE
wal-g backup retention not working since 1.13.0

### ISSUE THREAD

**Issue by bo0ts** [zalando/postgres-operator#2786]
- **Which image of the operator are you using?** ghcr.io/zalando/postgres-operator:v1.13.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** OpenShift 4.15
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** Bug

Since upgrading to postgres-operator 1.13.0 old wal-g backups are not deleted anymore.

We use the following backup related configuration:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-pod-config
data:
  AWS_ACCESS_KEY_ID: ...
  AWS_SECRET_ACCESS_KEY: ...
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_REGION: ...
  AWS_ENDPOINT: ...
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  WALG_DISABLE_S3_SSE: "true"
  WAL_S3_BUCKET: ...
```

We suspect that this is related to the following issue in Spilo https://github.com/zalando/spilo/issues/1015
