### ISSUE TITLE
chart CRD out-of-sync in 1.13.0

### ISSUE THREAD

**Issue by bo0ts** [zalando/postgres-operator#2788]
- **Which image of the operator are you using?** ghcr.io/zalando/postgres-operator:v1.13.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** OpenShift
- **Are you running Postgres Operator in production?** yes
- **Type of issue?** bug report

After upgrading to `1.13.0` to CRD in the chart is out-of-sync with the one installed through the helm chart.

Helm Chart:

```
# charts/postgres-operator/crds/postgresql.yaml
              maintenanceWindows:
                type: array
                items:
                  type: string
                  pattern: '^\ *((Mon|Tue|Wed|Thu|Fri|Sat|Sun):(2[0-3]|[01]?\d):([0-5]?\d)|(2[0-3]|[01]?\d):([0-5]?\d))-((2[0-3]|[01]?\d):([0-5]?\d)|(2[0-3]|[01]?\d):([0-5]?\d))\ *$'
```

Installed in the cluster:

```
# pkg/apis/acid.zalan.do/v1/crds.go
					"maintenanceWindows": {
						Type: "array",
						Items: &apiextv1.JSONSchemaPropsOrArray{
							Schema: &apiextv1.JSONSchemaProps{
								Type:    "string",
								Pattern: "^\\ *((Mon|Tue|Wed|Thu|Fri|Sat|Sun):(2[0-3]|[01]?\\d):([0-5]?\\d)|(2[0-3]|[01]?\\d):([0-5]?\\d))-((Mon|Tue|Wed|Thu|Fri|Sat|Sun):(2[0-3]|[01]?\\d):([0-5]?\\d)|(2[0-3]|[01]?\\d):([0-5]?\\d))\\ *$",
							},
						},
					},
```
