### ISSUE TITLE
FEATURE(imagePullSecrets) for logicalBackup

### ISSUE THREAD

**Issue by Mart-Kuc** [zalando/postgres-operator#2799]
We have the option to change the Docker image source (URL) for LogicalBackup. However, if we decide to use a private registry with authentication, we won’t be able to pull the image due to the absence of `imagePullSecrets` for this specific CronJob.

Would it be possible to add an `imagePullSecret` configuration to this CronJob to allow access to authenticated registries?

**Comment by Mart-Kuc** [comment]
Duplicate of [986](https://github.com/zalando/postgres-operator/issues/986)

**Comment by ihor-kokhan-onereach** [comment]
same issue

**Comment by HadrienVerrier** [comment]
Hello,

a possible workaround is to edit the serviceAccount in the Operator Configuration CR :

```yaml
configuration:
  kubernetes:
    pod_service_account_definition: |
        {
          "apiVersion": "v1",
          "kind": "ServiceAccount",
          "metadata": {
            "name": "<service account name>"
          },
          "imagePullSecrets": [
            { "name": "<image pull secret name>" }
          ]
        }
```
