### ISSUE TITLE
Unable to create timescaledb_toolkit using helm chart

### ISSUE THREAD

**Issue by odev-swe** [zalando/postgres-operator#2848]
Hi guys, recently i try to deploy timescaledb using helm chart on k8s, but unfortunely i can't find the timescaledb_toolkit extension after installed

- **Which image of the operator are you using?** 
- ghcr.io/zalando/postgres-operator:v1.14.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** [AWS K8s | GCP ... | Bare Metal K8s]
- Helm Chart Kubernetes
- **Are you running Postgres Operator in production?** [yes | no]
- yes
- **Type of issue?** [Bug report, question, feature request, etc.]
- Bug

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: insight-timescaledb
  namespace: insight-timescaledb
spec:
  teamId: "insight"
  volume:
    size: 32Gi
  numberOfInstances: 2
  users:
    insight:  # db owner
    - superuser
    - createdb
  databases:
    foo: insight
  preparedDatabases:
    insight:
      extensions:
        timescaledb: public
        timescaledb_toolkit: public
      schemas:
        public:
          defaultRoles: false
  postgresql:
    version: "16"
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "application"
              operator: In
              values:
                - dependency
  tolerations:
    - key: "application"
      operator: "Equal"
      value: "dependency"
      effect: "NoSchedule"
```

**Comment by lvijnck** [comment]
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: ec-ledger-cluster
spec:
  teamId: "acid"
  volume:
    size: 100Gi
  numberOfInstances: 1
  users:
    ec:  # database owner
    - superuser
    - createdb
  databases:
    ec: ec  # dbname: owner
  preparedDatabases:
    ec:
      extensions:
        timescaledb: public
  postgresql:
    parameters:
      shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,pg_cron,pg_stat_kcache,timescaledb
    version: "15"
```

Same here, the plugin seems to be loaded, but it's not being installed
