### ISSUE TITLE
What is the correct way to restore logical backups?

### ISSUE THREAD

**Issue by SergeiCherevko** [zalando/postgres-operator#2878]
I use the Postgres Operator to create a PostgreSQL database for Grafana:

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: grafana-playground-postgres
spec:
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi
  teamId: grafana
  numberOfInstances: 2
  postgresql:
    version: "14"
    parameters:
      max_connections: "1000"
  volume:
    size: 10Gi
  users:
    grafana:
      - login
  databases:
    grafana: grafana
```

This setup creates a primary (master) and a replica.

Now, I want to take a logical backup from the production Grafana PostgreSQL and restore it on this playground cluster.

I couldn't find any manuals explaining how to do this, but I assume the steps would be:

- Stop Grafana pods to prevent connections to the primary PostgreSQL pod.
- Drop the Grafana database.
- Upload the logical PostgreSQL dump to the primary PostgreSQL pod.
 - Restore the dump using:
```
psql -f /tmp/grafana_prod_pg_dump.sql
```
- Handle Patroni and the replica pod. (???)

Are these the correct steps? How can I ensure that the replica is properly synchronized with the new database after dropping it?
