### ISSUE TITLE
Specifying a nodeSelector for Postgres Pods

### ISSUE THREAD

**Issue by insertjokehere** [zalando/postgres-operator#420]
Hi,

Its entirely possible that I missed something when I looked through the documentation; if so, sorry in advance.

I'm trying to setup postgres-operator so that it only schedules Postgres pods on specific nodes; our cluster has several different types of nodes, including a mix of CPU architectures. In a 'normal' StatefulSet I would do this by setting `nodeSelector` - is there an equivalent field I can set on the `postgresql` object to achieve the same effect?

Thanks

**Comment by insertjokehere** [comment]
For those finding this in the future; currently (operator v1.1.0) it isn't possible to do this on a per-postgres-cluster level, but you can do it globally using the `node_readiness_label` config option.

* Label the nodes that you want to have Postgres pods on them: `kubectl label node <node name> should_have_pgdb_pods=true`
* Update the operator config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
data:  
  node_readiness_label: 'should_have_pgdb_pods:true'
```

I had to restart the operator pod for it pick up the config change, but once I did it automatically updated the existing StatefulSets and moved the pods onto the labeled nodes
