### ISSUE TITLE
Set user password?

### ISSUE THREAD

**Issue by abh** [zalando/postgres-operator#553]
I defined my roles in the cluster manifest and they got created as expected.

I see in the documentation how to define credentials for the "infrastructure roles", is there something similar for the "manifest roles"?

**Comment by FxKu** [comment]
It depends [what](https://github.com/zalando/postgres-operator/blob/master/docs/administrator.md#postgres-roles-supported-by-the-operator) you need. If it's just an application user that needs connection to Postgres than your setup is fine: Define in the manifest and they will get created in the DB + plus K8s secrets.

For human users we use an internal API that tells us which users get what privileges. Spilo itself also offers a [server-side procedure](https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/create_user_functions.sql#L49) to create users with safe passwords.

**Comment by FxKu** [comment]
closing it for now. Feel free to reopen, if the answer did not help.

**Comment by yusufgungor** [comment]
Hi,

Is it possible to set predefined passwords for users which defined in postgres manifest?

"Infrastructure roles" are not suitable for us because it creates roles in all Postgres clusters.

**Comment by anshudutta** [comment]
Hi,
This seems like a really important feature that is missing. We need to be able to control the password that gets set for system users like `postgres` when cluster is created. We need that for other jobs that need to connect to the dababase. We use automation terraform so there is no easy way to read the secret if its randomly generated

**Comment by yusufgungor** [comment]
Hi,

We have created the secrets for the usernames which are stated in postgres cluster manifest before creating the cluster. Postgres Operator then used that secrets and printed logs like "Secret xxx already exist" and created the cluster with that password.

The secret name must match as the postgres operator going to create if not exist.

For example, setting "postgres" user pass, create the secret below before creating the cluster:

```
### postgres user
apiVersion: v1
kind: Secret
metadata:
  labels:
    application: spilo
    postgresql-operator: test-postgresql-db
    team: test
  name: **postgres**.test-postgresql-db.credentials
  namespace: test-namespace
data:
  username: cG9zdGdyZXM=
  password: base64encodedpasswordforpostgresuser==
type: Opaque
---
```
As a temporary solution, it may helps you too.

**Comment by aditya1808** [comment]
@FxKu is there  a way to set password for manifest roles? and also is it possible to change a password once cluster is up and running. Could you provide link to any documnentation if available.

**Comment by ToonvanStrijp** [comment]
@FxKu this only works for the postgres user. Would be nice if we could have a predefined password for custom users as well. We have our yaml file like this:

```
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-hydra-database"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "13"
  numberOfInstances: 1
  volume:
    size: "10Gi"
  users:
    hydra: []
  databases:
    hydra: hydra
  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
```
and than the secret like:
```
apiVersion: v1
kind: Secret
metadata:
  name: hydra.acid-hydra-database.credentials.postgresql.acid.zalan.do
  labels:
    application: spilo
    cluster-name: acid-hydra-database
    team: acid
type: Opaque
data:
  password: WTJHV3Z3ckx4SnFpYTByemxCYk9zeU00cmJpYnY2VjRiSndtTXY3SnRjOFpHUWRNd0FLeWp0UFloU3prekprMw==
  username: aHlkcmEK
```
