### ISSUE TITLE
Document "Teams"

### ISSUE THREAD

**Issue by GeertJohan** [zalando/postgres-operator#617]
When reading the docs, terms "Teams" and "Teams API" are mentioned, but I had a hard time finding out what it was about. Eventually I found some specs on the API and the fake-teams-api, but from a postgres-operator user documentation perspective it wasn't clear at all what teams are about. Did I overlook something? Or perhaps the documentation around the concept of Teams and the teams-api can be improved?

**Comment by gertvdijk** [comment]
+1. I had the exact same experience. It's still a bit unclear to me - is this something Zalando-internal that the outside world can safely ignore in this context?

**Comment by Jan-M** [comment]
There was once a bit more docs and there is even manifests how to deploy the "fake" team API.

This is the most basic API: `/.../<teamname> -> ["name","anothername"]`

With this anyone can provide a minimal API around whatever service they use and how they want to bootstrap default human users and super user team members.

We will put this in the docs. It is not required for the operator to work, makes it just more convenient.

**Comment by GeertJohan** [comment]
"not required for the operator to work" is what I thought as well, but the `teamId` seems to be a mandatory field. The submission API errors about missing team name when submitting a Postgresql yaml manifest without `teamId`. When filling it with bogus, it's later ignored as no team API URL is configured. Perhaps `teamId` should be optional?

**Comment by Jan-M** [comment]
This team ID and the expected prefix imho serves a good purpose on ensuring unique cluster names and reducing the risk of colliding entities. It is very easy to create/apply changes to entities in K8S if your environment is lax.

But it may be worth discussing how a manifest or cluster setup could look like without it.

**Comment by CarlQLange** [comment]
I feel as though all that's missing is a simple explanation of the `teamId` in the docs. It doesn't seem clear to me what it is for, and so I can't give sensible values.

**Comment by rektide** [comment]
Hey. I was installing the postgres-operator & going through the config, trying to understand what the different pieces of it were. I ran into this comment about the teams api, for an oauth_token_secret_name, & couldn't find much info on what the Teams API is. This thread is one of the the things that's turned up.

Not sure if this Teams thing is a postgres thing, a zalando/spilo thing, or perhaps a [kube thing](https://kubernetes.io/docs/tasks/administer-cluster/namespaces/)? We got a little help in [this comment from Jan-M](https://github.com/zalando/postgres-operator/issues/617#issuecomment-512160082) but I'm still missing some of the ground-level info to understand what/whose Teams API is being talked about here.

**Comment by dajudge** [comment]
maybe it's worth considering making the teamId and the associated restrictions on the postgressql's name optionally optional (e.g. via a config setting for the operator)?

**Comment by PetterSa** [comment]
> This team ID and the expected prefix imho serves a good purpose on ensuring unique cluster names and reducing the risk of colliding entities. It is very easy to create/apply changes to entities in K8S if your environment is lax.
> 
> But it may be worth discussing how a manifest or cluster setup could look like without it.

I will have to politely disagree. We run the clusters per namespace and in S3 they have UUIDs to stop collisions. `teamId` is not only useless to us, but a trap to fall in then using prefixes from kustomize, as that will change the name of the cluster without changing the `teamId`. 

As far as I can see, the UUID of the cluster should be sufficient to avoid naming collision.

**Comment by devlifealways** [comment]
I'm a big fan Zalando's PostgreSQL operator, I'm using it for quite a long time, it helps a lot, but whenever someone new tries to use it on our team, a pattern keeps repeating itself, the **teams API documentation** is not really clear. It would help if we had some kind of schema like we do for the other aspects.

**Comment by lowercase00** [comment]
Same experience here, been having a really hard time dealing with the team/users human users thing. Different errors each time (pooler won't start, specific name formats, do I need `additionalMembers`?). So far I spent most of the time trying with the manifests (config + rbac + operator), will spend a bit more time trying with the helm configurations to see if I can make something work (not that it would matter... but it's worth the shot). Couldn't quite understand the description of the options, and couldn't find much information on the errors online. Will post here if I can manage to make it work without using "acid" as the team.

**Comment by lowercase00** [comment]
So if anyone stumbles with the same issue in the future, this is what worked for me, disabling the teams API and use an arbitrary `teamID`. The `teamID` and `clusterName` need to be related though, the format has to be `{teamID-clusterName}` (or something like that).

Install with Helm and custom values

```bash
helm repo add postgres-operator https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
helm install postgres-operator postgres-operator/postgres-operator --values k8s/postgres/values.yml
```

```yaml
# values.yml

configUsers:
  replication_username: standby
  super_username: postgres

configKubernetes:
  cluster_domain: cluster.local
  cluster_labels:
    application: myproject-db-cluster
  cluster_name_label: myproject-db-cluster

configPostgresPodResources:
  default_cpu_limit: "1"
  default_cpu_request: 50m
  default_memory_limit: 500Mi
  default_memory_request: 100Mi
  min_cpu_limit: 250m
  min_memory_limit: 250Mi

configLogicalBackup:
  logical_backup_job_prefix: "logical-backup-"
  logical_backup_provider: "s3"
  logical_backup_s3_access_key_id: "MY_ACCESS_KEY"
  logical_backup_s3_secret_access_key: "MY_SECRET_KEY"
  logical_backup_s3_bucket: "myproject-backup"
  logical_backup_s3_region: "us-east-1"
  logical_backup_s3_sse: "AES256"
  logical_backup_schedule: "0 0 * * *"

configTeamsApi:
  enable_team_superuser: true
  enable_teams_api: false

configConnectionPooler:
  connection_pooler_schema: "pooler"
  connection_pooler_user: "pooler"
  connection_pooler_image: "registry.opensource.zalan.do/acid/pgbouncer:master-22"
  connection_pooler_max_db_connections: 50
  connection_pooler_mode: "transaction"
  connection_pooler_number_of_instances: 1
  connection_pooler_default_cpu_request: 50m
  connection_pooler_default_memory_request: 100Mi
  connection_pooler_default_cpu_limit: "1"
  connection_pooler_default_memory_limit: 100Mi

configAwsOrGcp:
  wal_s3_bucket: "myproject-backup"

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 150Mi
```

After the installation, wait until the operator is available, and then apply the cluster:

```yaml
# mycluster.yml

apiVersion: "acid.zalan.do/v1"
kind: postgresql

metadata:
  name: myproject-db
  namespace: default

spec:
  teamId: "myproject"
  numberOfInstances: 2
  enableLogicalBackup: true
  enableConnectionPooler: true
  connectionPooler:
    numberOfInstances: 1
    mode: "transaction"
  postgresql:
    version: "14"
  volume:
    size: 15Gi
  users:
    myuser:
      - superuser
      - createdb
  databases:
    myproject: myuser
```

After that, I've been experiencing an erratic behavior with the creation of the pooler, sometimes it works, sometime it doesn't. What I've done, was manually change the `cluster` to `enableConnectionPooler` to `false` (Im using Lens IDE), and then setting it to `true` right after. 

I've tried in a few different clusters, and couldn't find any particular scenario on when/why the pooler worked, or why it didn't, logs seem ok (both operator and cluster), so a bit hard to troubleshoot. Anyways, that worked, I'll be testing how things go from now on.

I still don't see the CronJob for the backup (I do in another setup), but I'll keep looking, maybe it will only be created next to the next run.

Hope this helps someone that's having trouble as I was, spent quite a few hours trying to sort this out.
