### ISSUE TITLE
CRD: add additionalPrinterColumns for kubectl/kube-web-view

### ISSUE THREAD

**Issue by hjacobs** [zalando/postgres-operator#635]
`additionalPrinterColumns` are awesome to make `kubectl`and [kube-web-view](https://codeberg.org/hjacobs/kube-web-view/) more useful.

Example columns which would make sense:

```yaml
additionalPrinterColumns:
  - JSONPath: .spec.teamId
    name: Team
    type: string
  - JSONPath: .status.PostgresClusterStatus
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: Age of the PlatformCredentialsSet
    name: Age
    type: date
```

The result would be for kubectl:
```
kubectl get postgresqls
NAME                                  TEAM       STATUS       AGE
test-db-foo-test                      test       Running      61d
test-elephant-chat-bot-test-db        test       Running      101d
test-source-for-pg-clone-smoke-test   test       Running      18d
ci-repo-manager-db                    ci         Running      102d
foobarzz-grafana                      foobarzz   Running      17d
foobarzz-lightstep-manager            foobarzz   Running      83d                                                                                                                                                                                                              
foobarzz-postgres-sentry              foobarzz   Running      39d
foobarzz-zmon-main                    foobarzz   Running      102d
lollypop-inciders-db                  lollypop   Running      101d
teapot-cluster-registry-db            teapot     Running      55d
teapot-grafana-db                     teapot     Running      92d
teapot-test                           teapot     SyncFailed   39d
```

And in kube-web-view:

![Screenshot_2019-07-29 postgresqls - Kubernetes Web UI](https://user-images.githubusercontent.com/510328/62037367-f493b180-b1f3-11e9-8aca-54827543a003.png)



Related change for Zalando's PlatformCredentialsSet CRD: https://github.com/zalando-incubator/kubernetes-on-aws/pull/2365
