### ISSUE TITLE
could not parse volume size from the manifest

### ISSUE THREAD

**Issue by winterrmute** [zalando/postgres-operator#660]
Hi, i am trying to set up the postgres operator on our test kubernetes. We got two nodes, persistent volume is created. 

PV looks like that:
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume01
  labels: 
    environment: dev
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /path/to/share
    server: 192.168.10.20`

The message i get after starting the database is following:
`time="2019-09-03T13:58:10Z" level=error msg="could not create cluster: could not create statefulset: could not generate statefulset: could not generate volume claim template: could not parse volume size: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'" cluster-name=dev-port/db-port pkg=controller worker=0
time="2019-09-03T13:58:35Z" level=info msg="\"SYNC\" event has been queued" cluster-name=my-cluster/db-port pkg=controller worker=0
time="2019-09-03T13:58:35Z" level=info msg="there are 1 clusters running" pkg=controller
time="2019-09-03T13:58:35Z" level=info msg="Creating the role binding postgres-operator-serviceaccount in the namespace my-cluster" pkg=controller
time="2019-09-03T13:58:35Z" level=warning msg="Pods and/or Patroni may misfunction due to the lack of permissions: could not create role binding postgres-operator-serviceaccount : cannot bind the pod service account \"postgres-operator-serviceaccount\" defined in the config map to the cluster role in the \"my-cluster\" namespace: clusterroles.rbac.authorization.k8s.io \"postgres-operator-serviceaccount\" not found" pkg=controller`

Any ideas why I get this error? Where should I look for possible issues?

**Comment by FxKu** [comment]
How does `volume` setting in your manifest look like? `size: 100Gi`?

**Comment by winterrmute** [comment]
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume01
  labels: 
    environment: dev
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /path/to/share
    server: 10.20.30.40

**Comment by FxKu** [comment]
I meant the volume setting in your `postgresql` manifest :)

So far, I have only worked with automatic volume provisioning and have not used predefined ones like you have there. PVCs and PVs are created automatically when creating a new cluster.

**Comment by winterrmute** [comment]
That sounds even better. I would prefer to not to use self configured PVs. Anyway, I deletet the PV and tried to create the cluster without it. The error message is the same.

My postgresql manifest looks like that:

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: mydb
  namespace: mynamespace
spec:
  teamId: "db"
  volumes:
    volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    # database owner
    admin:
    - superuser
    - createdb

    my-database: []

  #databases: name->owner
  databases:
    my-database: db_owner
  postgresql:
    version: "10"
```

**Comment by FxKu** [comment]
Well, that looks wrong, indeed. It should be:
```
spec:
  teamId: "db"
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    # database owner
    admin:
    - superuser
    - createdb
    db_owner: []

  #databases: name->owner
  databases:
    my_database: db_owner
  postgresql:
    version: "10"
```

For a database name, I would not use dashes but underscores. And your DB owner should also appear in the `users` section. Flags can empty. `my-database: []` is wrong there.
