### ISSUE TITLE
Users and databases not being created

### ISSUE THREAD

**Issue by jamessewell** [zalando/postgres-operator#663]
Hello,

I'm using Spilo / Patroni on K8s (deployed via the master branch of postgres-operator)

All works like magic, except my databases and users aren't being created:

I have this in my config:

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: f-postgres-cluster
  namespace: f
spec:
  teamId: "fg"
  volume:
    size: 11Gi
    storageClass: postgres
  numberOfInstances: 3
  users:
    fuser:
    - superuser
    - createdb
  databases:
    db1: fuser
    db2 : fuser
  postgresql:
    version: "11"
```

When I look in my operator log I can see that use users and databases keys are not making it into the created config.

`\"users\":{\"zalandos\":{\"password\":\"\",\"options\":[\"CREATEDB\",\"NOLOGIN\"]}}`

However some other options are making it in.to the config - which is odd.

**Comment by jamessewell** [comment]
I can also see that the secret for my user has been made:
```
#kubectl get secret fuser.fg-postgres-cluster.credentials
NAME                                  TYPE     DATA   AGE
fuser.fg-postgres-cluster.credentials   Opaque   2      60m
```

**Comment by FxKu** [comment]
Hi,
I cannot reproduce this. But while using your manifest I get this error:
```
level=debug msg="skipping \"ADD\" event for the invalid cluster: name must match {TEAM}-{NAME} format" cluster-name=default/f-postgres-cluster pkg=controller
```

After renaming the cluster to `fg-postgres-cluster` everything worked fine (see also #617). Note, that the roles and databases are not there right after Pod startup. They will be created when all Pods are ready.

**Comment by jamessewell** [comment]
Hi,

Sorry that was an artifact of me changing names for the paste.

So if you change team to f then you get a cluster with the correct db and user?

I do not get this - I’ve redeployed many times also basing some on the complete example.

**Comment by FxKu** [comment]
have another look at the operator logs. Does it say that the cluster could be created successfully? Are there no errors regarding the databases and users?

**Comment by johannwagner** [comment]
You may want to check the cluster_domain in your operator config.

It seems, that the operator fails to set the values correctly, if it is not able to connect to the postgres instances.

**Comment by FxKu** [comment]
Closing this one for now. Feel free to reopen if the problem still exists when using the latest release.

**Comment by kurbar** [comment]
I think I might be running into the same issue and was setting it up following the quickstart tutorial. Though my difference is that the user does get created but databases are not.

1. Cloned master branch today
2. Installed the postgres-operator using Helm v3
```
helm install postgres-operator ./charts/postgres-operator -f ./charts/postgres-operator/values-crd.yaml
```

I took the `complete-cluster-manifest.yaml` as a base. To hide the project I have replaced it with "hidden" in below snippets.

I assigned my cluster to a namespace under metadata:
```
metadata:
  name: hidden-postgres-cluster
  namespace: hidden-micro
```

I then changed the storage class and user & added a few database:
```
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p16
  teamId: "hidden"
  volume:
    size: 10Gi
    storageClass: standard
  numberOfInstances: 2
  users:  # Application/Robot users
    hidden:
    - superuser
    - createdb
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  allowedSourceRanges:  # load balancers' source ranges for both master and replica services
  - 127.0.0.1/32
  databases:
    hidden-service-guideline: hidden
    hidden-service-import: hidden
    hidden-service-region: hidden
    hidden-service-translate: hidden
```

Everything else I left as-is in the manifest.

Finally, I deployed it:
```
kubectl apply -f deployment/static/postgres/cluster.yaml
```

I waited for the 2 pods to finish by watching the logs. During the startup, I did not see any indication of either the my hidden user being created or any of the databases. I can add the startup logs if needed.

Although the secret for my user is created and it does seem to work. I shell'd into one of the pods and tried accessing one of the databases but to no avail:
```
root@hidden-postgres-cluster-1:/home/postgres# psql -U hidden -d hidden-service-region
psql: error: could not connect to server: FATAL:  database "hidden-service-region" does not exist
```

I also examined the `postgres.yml` that was created in the pod, funnily enough, there is no indication of the databases or even the user I wanted, it has only the defaults of the `zalandos` user
```
root@hidden-postgres-cluster-1:/home/postgres# cat postgres.yml 
bootstrap:
  ...
  post_init: /scripts/post_init.sh "zalandos"
  users:
    zalandos:
      options:
      - CREATEDB
      - NOLOGIN
      password: ''
kubernetes:
  labels:
    application: spilo
  pod_ip: 10.44.0.69
  ports:
  - name: postgresql
    port: 5432
  role_label: spilo-role
  scope_label: cluster-name
  use_endpoints: true
namespace: hidden-micro
postgresql:
  authentication:
    replication:
      password: ***
      username: standby
    superuser:
      password: ***
      username: postgres
  bin_dir: /usr/lib/postgresql/11/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: 10.44.0.69:5432
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: hidden-postgres-cluster-1
  ...
scope: hidden-postgres-cluster
```

I'm completely lost and can't figure out what I might have done wrong. I've tried tearing everything down with `kubectl delete postgresql -n hidden-micro hidden-postgres-cluster` and starting over but that hasn't helped as well.

**Comment by kurbar** [comment]
Ah, finally I figured it out. postgres-operator does not like database names that have dashes in them. Postgres accepts such names but postgres-operator does not like them.

Is this intended due to some limitations or a bug?

**Comment by srflaxu40** [comment]
How could I deploy my own custom patroni yaml to kubernetes that is running postgresql-operator?

IE how do I wrap it within pg operator CRD?

**Comment by FxKu** [comment]
@kurbar good to read! Improving database name checks is an open issue see #667

**Comment by XavierLevaux** [comment]
@srflaxu40 Did you figured out if it is possible to customise Patroni config.yml file?
https://blog.seocahill.com/docker-postgres-cluster-with-high-availability-and-disaster-recovery-part-2/

I wonder if I could configure Patroni to have a custom script as callback for "on_role_change".
The goal is to monitor database failover.

**Comment by georg-schwarz** [comment]
We had the same issue that databases were not created at the startup of the database. In our case, it was a combination of (i) taking `postgres` as `user` and using `database` names with dashes (`my-service-db`). Hope this helps anyone stumbling a similar issue, so I attached the debugging process we followed to find out what was wrong.

## Broken Configuration

```yaml
users:
    postgres:
      - superuser
      - createdb
databases:
    postgres: postgres
    my-service-db: postgres
```
```bash
❯ kubectl logs postgres-operator-5645754694-76dx2 | grep "my-service-db"
time="2023-03-30T16:12:15Z" level=info msg="skipping creation of the \"my-service-db\" database, user \"postgres\" does not exist"
```

## Fixed User

```yaml
users:
    myuser:
      - superuser
      - createdb
databases:
    postgres: myuser
    my-service-db: myuser
```
```bash
❯ kubectl logs postgres-operator-5645754694-76dx2 | grep "my-service-db"
time="2023-03-31T07:19:35Z" level=info msg="database \"my-service-db\" has invalid name"
```

## Working Config

```yaml
users:
    myuser:
      - superuser
      - createdb
databases:
    postgres: myuser
    myservicedb: myuser
```
