### ISSUE TITLE
Unable to update labels with istio sidecar injected

### ISSUE THREAD

**Issue by mc1711** [zalando/postgres-operator#680]
We are running Istio in Kubernetes with automatic sidecar injection. When we turn on the sidecar injection on the postgres statefulset we face an issue, the postgres operator is not able to update the statefulset pods label. Specifically the spilo-role label is not generated, resulting in Endpoints not getting generated. 
Is there a way to get around this issue? 

We are currently using postgres-operator version 1.1.0

**Comment by FxKu** [comment]
Sounds related to what uses reported in PR #657

**Comment by mc1711** [comment]
@FxKu  thanks for your answer. I'll follow pr 657 btw I'm not sure we are in the same scenario of PR #657.

In our case what is missing is the pod_role_label (spilo-role), it doesn't get injected in the pod, consequently we don't get the endpoints associated to the service.

**Comment by FxKu** [comment]
@mc1711 can you check the operator logs? (logs of operator pod). How do you configure your operator?

**Comment by mc1711** [comment]
This is the postgres operator log when sidecar injection is enabled 

```
level=info msg="\"SYNC\" event has been queued" cluster-name=default/at-db pkg=controller worker=0
level=info msg="there are 1 clusters running" pkg=controller
 level=info msg="Creating the role binding zalando-postgres-operator in the namespace default" pkg=controller
 level=warning msg="Pods and/or Patroni may misfunction due to the lack of permissions: could not create role binding zalando-postgres-operator : cannot bind the pod service account \"postgres-operator\" defined in the config map to the cluster role in the \"default\" namespace: clusterroles.rbac.authorization.k8s.io \"zalando-postgres-operator\" not found" pkg=controller
level=info msg="syncing of the cluster started" cluster-name=default/at-db pkg=controller worker=0
level=debug msg="team API is disabled, returning empty list of members for team \"at\"" cluster-name=default/at-db pkg=cluster
level=debug msg="syncing secrets" cluster-name=default/at-db pkg=cluster
level=debug msg="secret \"default/at.at-db.credentials\" already exists, fetching its password" cluster-name=default/at-db pkg=cluster
level=debug msg="secret \"default/postgres.at-db.credentials\" already exists, fetching its password" cluster-name=default/at-db pkg=cluster
level=debug msg="secret \"default/standby.at-db.credentials\" already exists, fetching its password" cluster-name=default/at-db pkg=cluster
level=debug msg="syncing services" cluster-name=default/at-db pkg=cluster
level=debug msg="syncing master service" cluster-name=default/at-db pkg=cluster
level=debug msg="final load balancer source ranges as seen in a service spec (not necessarily applied): [\"127.0.0.1/32\"]" cluster-name=default/at-db pkg=cluster
level=debug msg="syncing replica service" cluster-name=default/at-db pkg=cluster
level=debug msg="No load balancer created for the replica service" cluster-name=default/at-db pkg=cluster
level=debug msg="syncing persistent volumes" cluster-name=default/at-db pkg=cluster
level=warning msg="cannot shrink persistent volume" cluster-name=default/at-db pkg=cluster
level=warning msg="cannot shrink persistent volume" cluster-name=default/at-db pkg=cluster
level=warning msg="cannot shrink persistent volume" cluster-name=default/at-db pkg=cluster
level=info msg="volumes have been synced successfully" cluster-name=default/at-db pkg=cluster
level=debug msg="syncing statefulsets" cluster-name=default/at-db pkg=cluster
level=debug msg="cached StatefulSet value exists, rollingUpdate flag is true" cluster-name=default/at-db pkg=cluster
level=debug msg="Generating Spilo container, environment variables: [{SCOPE at-db nil} {PGROOT /home/postgres/pgdata/pgroot nil} {POD_IP  &EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:status.podIP,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {POD_NAMESPACE  &EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}} {PGUSER_SUPERUSER postgres nil} {KUBERNETES_SCOPE_LABEL version nil} {KUBERNETES_ROLE_LABEL spilo-role nil} {KUBERNETES_LABELS application=spilo nil} {PGPASSWORD_SUPERUSER  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:postgres.at-db.credentials,},Key:password,Optional:nil,},}} {PGUSER_STANDBY standby nil} {PGPASSWORD_STANDBY  &EnvVarSource{FieldRef:nil,ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:standby.at-db.credentials,},Key:password,Optional:nil,},}} {PAM_OAUTH2 https://info.example.com/oauth2/tokeninfo?access_token= uid realm=/employees nil} {SPILO_CONFIGURATION {\"postgresql\":{\"bin_dir\":\"/usr/lib/postgresql/10/bin\",\"pg_hba\":[\"hostssl all all 0.0.0.0/0 md5\",\"host    all all 0.0.0.0/0 md5\"]},\"bootstrap\":{\"initdb\":[{\"auth-host\":\"md5\"},{\"auth-local\":\"trust\"},\"data-checksums\",{\"encoding\":\"UTF8\"},{\"locale\":\"en_US.UTF-8\"}],\"users\":{\"zalandos\":{\"password\":\"\",\"options\":[\"CREATEDB\",\"NOLOGIN\"]}},\"dcs\":{}}} nil} {DCS_ENABLE_KUBERNETES_API true nil}]" cluster-name=default/at-db pkg=cluster
level=debug msg="statefulset's rolling update annotation has been set to false" cluster-name=default/at-db pkg=cluster
level=info msg="statefulset \"default/at-db\" is not in the desired state and needs to be updated" cluster-name=default/at-db pkg=cluster
level=debug msg="spec diff between old and new statefulsets: \nTemplate.Spec.Containers[0].TerminationMessagePath: \"/dev/termination-log\" != \"\"\nTemplate.Spec.Containers[0].TerminationMessagePolicy: \"File\" != \"\"\nTemplate.Spec.RestartPolicy: \"Always\" != \"\"\nTemplate.Spec.DNSPolicy: \"ClusterFirst\" != \"\"\nTemplate.Spec.DeprecatedServiceAccount: \"postgres-operator\" != \"\"\nTemplate.Spec.SecurityContext: &v1.PodSecurityContext{} != nil\nTemplate.Spec.SchedulerName: \"default-scheduler\" != \"\"\nTemplate.Spec.Tolerations: []v1.Toleration(nil) != []v1.Toleration{}\nVolumeClaimTemplates[0].Spec.VolumeMode: &\"Filesystem\" != nil\nVolumeClaimTemplates[0].Status.Phase: \"Pending\" != \"\"\nPodManagementPolicy: \"OrderedReady\" != \"\"\nUpdateStrategy.Type: \"OnDelete\" != \"\"\nRevisionHistoryLimit: &int32(10) != nil\n" cluster-name=default/at-db pkg=cluster
level=info msg="reason: \"new statefulset's volumeClaimTemplates specification for volume \\\"pgdata\\\" doesn't match the current one\"" cluster-name=default/at-db pkg=cluster
level=debug msg="replacing statefulset" cluster-name=default/at-db pkg=cluster
level=debug msg="waiting for the statefulset to be deleted" cluster-name=default/at-db pkg=cluster
level=debug msg="syncing roles" cluster-name=default/at-db pkg=cluster
level=error msg="could not connect to PostgreSQL database: read tcp 10.244.0.150:40882->10.103.158.38:5432: read: connection reset by peer" cluster-name=default/at-db pkg=cluster
level=error msg="could not connect to PostgreSQL database: read tcp 10.244.0.150:41804->10.103.158.38:5432: read: connection reset by peer" cluster-name=default/at-db pkg=cluster
level=error msg="could not connect to PostgreSQL database: read tcp 10.244.0.150:42606->10.103.158.38:5432: read: connection reset by peer" cluster-name=default/at-db pkg=cluster
level=error msg="could not connect to PostgreSQL database: read tcp 10.244.0.150:43536->10.103.158.38:5432: read: connection reset by peer" cluster-name=default/at-db pkg=cluster
level=error msg="could not connect to PostgreSQL database: read tcp 10.244.0.150:44348->10.103.158.38:5432: read: connection reset by peer" cluster-name=default/at-db pkg=cluster
level=error msg="could not connect to PostgreSQL database: read tcp 10.244.0.150:45288->10.103.158.38:5432: read: connection reset by peer" cluster-name=default/at-db pkg=cluster
level=error msg="could not connect to PostgreSQL database: read tcp 10.244.0.150:46100->10.103.158.38:5432: read: connection reset by peer" cluster-name=default/at-db pkg=cluster
level=error msg="could not connect to PostgreSQL database: read tcp 10.244.0.150:47036->10.103.158.38:5432: read: connection reset by peer" cluster-name=default/at-db pkg=cluster
level=warning msg="error while syncing cluster state: could not sync roles: could not init db connection: could not init db connection: still failing after 8 retries" cluster-name=default/at-db pkg=cluster
level=error msg="could not sync cluster: could not sync roles: could not init db connection: could not init db connection: still failing after 8 retries" cluster-name=default/at-db pkg=controller worker=0
```
the db-spec.yml

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: at-db
  namespace: default
spec:
  teamId: "at"
  volume:
    size: 5Gi
  numberOfInstances: 3
  users:
    at:
    - superuser
    - createdb
  databases:
    at: at
  postgresql:
    version: "10"
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
    - hostssl all all 0.0.0.0/0 md5
    - host    all all 0.0.0.0/0 md5[root@xxx ~]#
```


Just for completeness there is no role set when side car injection enabled, and no endpoints are generated

```
$kubectl get pod at-db-0 -o yaml | grep label -A7
  labels:
    application: spilo
    controller-revision-hash: at-db-587b8f4446
    statefulset.kubernetes.io/pod-name: at-db-0
    team: at
    version: at-db
  name: at-db-0
  namespace: default

$kubectl get pod at-db-1 -o yaml | grep label -A7
  labels:
    application: spilo
    controller-revision-hash: at-db-587b8f4446
    statefulset.kubernetes.io/pod-name: at-db-1
    team: at
    version: at-db
  name: at-db-1
  namespace: default

$kubectl get pod at-db-2 -o yaml | grep label -A7
  labels:
    application: spilo
    controller-revision-hash: at-db-587b8f4446
    statefulset.kubernetes.io/pod-name: at-db-2
    team: at
    version: at-db
  name: at-db-2
  namespace: default


$kubectl get endpoints                        

NAME                              ENDPOINTS                                               AGE
at-db                           <none>                                                  1d
at-db-repl                      <none>                                                  1d

```

This is how labels look like when no sidecar injected

```
$kubectl get pod at-db-0 -o yaml | grep label -A7
  labels:
    application: spilo
    controller-revision-hash: at-db-587b8f4446
    spilo-role: master
    statefulset.kubernetes.io/pod-name: at-db-0
    team: at
    version: at-db
  name: at-db-0

$kubectl get pod at-db-1 -o yaml | grep label -A7
  labels:
    application: spilo
    controller-revision-hash: at-db-587b8f4446
    spilo-role: replica
    statefulset.kubernetes.io/pod-name: at-db-1
    team: at
    version: at-db
  name: at-db-1

$kubectl get pod at-db-2 -o yaml | grep label -A7
  labels:
    application: spilo
    controller-revision-hash: at-db-587b8f4446
    spilo-role: replica
    statefulset.kubernetes.io/pod-name: at-db-2
    team: at
    version: at-db
  name: at-db-2

kubectl get endpoints                          

NAME                           ENDPOINTS                                                  AGE
at-db                           10.244.0.176:5432                                          6d23h
at-db-repl                    10.244.0.177:5432,10.244.0.178:5432           6d23h
```

**Comment by mc1711** [comment]
@FxKu, first of all thanks for your help, If can be useful, the postgres-operator is deployed via helm .. this is the helm configuration. hopefully it helps

```

helm get postgres-operator
REVISION: 1
RELEASED: Wed Oct  9 11:05:42 2019
CHART: postgres-operator-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
config:
  api_port: "8080"
  aws_region: eu-central-1
  cluster_history_entries: "1000"
  cluster_labels: application:spilo
  cluster_name_label: version
  db_hosted_zone: db.example.com
  debug_logging: "true"
  docker_image: registry.opensource.zalan.do/acid/spilo-cdp-11:1.5-p70
  enable_master_load_balancer: "true"
  enable_pod_antiaffinity: "false"
  enable_replica_load_balancer: "false"
  enable_teams_api: "false"
  master_dns_name_format: '{cluster}.{team}.staging.{hostedzone}'
  pdb_name_format: postgres-{cluster}-pdb
  pod_antiaffinity_topology_key: kubernetes.io/hostname
  pod_deletion_wait_timeout: 10m
  pod_label_wait_timeout: 10m
  pod_management_policy: ordered_ready
  pod_role_label: spilo-role
  pod_terminate_grace_period: 5m
  ready_wait_interval: 3s
  ready_wait_timeout: 30s
  replica_dns_name_format: '{cluster}-repl.{team}.staging.{hostedzone}'
  replication_username: standby
  resource_check_interval: 3s
  resource_check_timeout: 10m
  resync_period: 5m
  ring_log_lines: "100"
  secret_name_template: '{username}.{cluster}.credentials'
  spilo_privileged: "false"
  super_username: postgres
  watched_namespace: '*'
  workers: "4"
image:
  pullPolicy: IfNotPresent
  registry: registry.opensource.zalan.do
  repository: acid/postgres-operator
  tag: v1.1.0
nodeSelector: {}
podAnnotations: {}
podLabels: {}
priorityClassName: ""
rbac:
  create: true
resources: {}
serviceAccount:
  create: true
  name: null
tolerations: []

HOOKS:
MANIFEST:

---
# Source: postgres-operator/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-0.1.0
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: postgres-operator
data:
  pod_service_account_name: postgres-operator
  api_port: "8080"
  aws_region: eu-central-1
  cluster_history_entries: "1000"
  cluster_labels: application:spilo
  cluster_name_label: version
  db_hosted_zone: db.example.com
  debug_logging: "true"
  docker_image: registry.opensource.zalan.do/acid/spilo-cdp-11:1.5-p70
  enable_master_load_balancer: "true"
  enable_pod_antiaffinity: "false"
  enable_replica_load_balancer: "false"
  enable_teams_api: "false"
  master_dns_name_format: '{cluster}.{team}.staging.{hostedzone}'
  pdb_name_format: postgres-{cluster}-pdb
  pod_antiaffinity_topology_key: kubernetes.io/hostname
  pod_deletion_wait_timeout: 10m
  pod_label_wait_timeout: 10m
  pod_management_policy: ordered_ready
  pod_role_label: spilo-role
  pod_terminate_grace_period: 5m
  ready_wait_interval: 3s
  ready_wait_timeout: 30s
  replica_dns_name_format: '{cluster}-repl.{team}.staging.{hostedzone}'
  replication_username: standby
  resource_check_interval: 3s
  resource_check_timeout: 10m
  resync_period: 5m
  ring_log_lines: "100"
  secret_name_template: '{username}.{cluster}.credentials'
  spilo_privileged: "false"
  super_username: postgres
  watched_namespace: '*'
  workers: "4"
---
# Source: postgres-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-operator
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-0.1.0
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: postgres-operator
---
# Source: postgres-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: postgres-operator
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-0.1.0
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: postgres-operator
rules:
- apiGroups:
  - acid.zalan.do
  resources:
  - postgresqls
  - operatorconfigurations
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch # needed if zalando-postgres-operator account is used for pods as well
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - update # only for resizing AWS volumes
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - create
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - rolebindings
  verbs:
  - get
  - create
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  verbs:
  - bind
  resourceNames:
  - postgres-operator
---
# Source: postgres-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: postgres-operator
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-0.1.0
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: postgres-operator
subjects:
- kind: ServiceAccount
# note: the cluster role binding needs to be defined
# for every namespace the operator service account lives in.
  name: postgres-operator
  namespace: default
---
# Source: postgres-operator/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-0.1.0
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: postgres-operator
  name: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-operator
      app.kubernetes.io/instance: postgres-operator
  template:
    metadata:
      annotations:
        checksum/config: 25369a194d6547d38ca8f573d428e01b543c30fb2075fac9ffae15d3545df009
      labels:
        app.kubernetes.io/name: postgres-operator
        app.kubernetes.io/instance: postgres-operator
    spec:
      serviceAccountName: postgres-operator
      containers:
      - name: postgres-operator
        image: "registry.opensource.zalan.do/acid/postgres-operator:v1.1.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_MAP_NAME
          value: postgres-operator
        resources:
          {}

      affinity:
        {}

      nodeSelector:
        {}

      tolerations:
        []

```

**Comment by FxKu** [comment]
@mc1711 could you check, if your errors still persist using the latest release?

**Comment by patrickleet** [comment]
@FxKu 

I enabled istio injection and am seeing the label set:

```
k get pods -n jx-production -L spilo-role production-postgresql-2 -o yaml | grep label -A10
  labels:
    application: spilo
    cluster-name: production-postgresql
    controller-revision-hash: production-postgresql-795b6f998c
    istio.io/rev: default
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: production-postgresql
    service.istio.io/canonical-revision: latest
    spilo-role: replica
    statefulset.kubernetes.io/pod-name: production-postgresql-2
    team: production
```

**Comment by batistein** [comment]
I'm currently facing the same issues. Any updates on this topic?

**Comment by FxKu** [comment]
@batistein and others. No istio experience on my side but just found [this comment](https://github.com/zalando/postgres-operator/issues/772#issuecomment-567321183). Maybe it helps in your case, too.

**Comment by rappjaco** [comment]
I ended up configuring an Istio PeerAuthentication policy that sets port 8008 and 5432 to permissive. This allows the cluster pods to not require istio MTLS between replica and master. 

It seems that the base label of application=spilo was good enough. I ended up throwing this into a Kyverno mutate policy to dynamically apply it to all new namespaces. 


```
apiVersion: security.istio.io/v1
kind: PeerAuthentication
name: spilo-peer-auth
namespace: foo
data:
  metadata:
    labels:
      application: spilo
  spec:
    selector:
      matchLabels:
        application: spilo
    mtls:
      mode: STRICT
    portLevelMtls:
      5432:
        mode: PERMISSIVE
      8008:
        mode: PERMISSIVE
```
