### ISSUE TITLE
Document SSL req: k8s internal connection fails; LB connection works

### ISSUE THREAD

**Issue by haf-afa** [zalando/postgres-operator#709]
I'm having a rough time getting started; I can connect to the minimal PGSQL db as provisioned via the operator, but only via the LoadBalancer service on the Host (my laptop). From inside, via Grafana, I get

```
t=2019-11-05T13:47:23+0000 lvl=info msg="Starting Grafana" logger=server version=6.4.2 commit=443a0ba branch=HEAD compiled=2019-10-08T09:10:35+0000
[snip]
t=2019-11-05T13:47:23+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_USER=grafana"
t=2019-11-05T13:47:23+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_DATABASE_PASSWORD=*********"
[snip]
t=2019-11-05T13:47:23+0000 lvl=info msg="App mode production" logger=settings
t=2019-11-05T13:47:23+0000 lvl=info msg="Initializing SqlStore" logger=server
t=2019-11-05T13:47:23+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=postgres
t=2019-11-05T13:47:23+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2019-11-05T13:47:23+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: pq: pg_hba.conf rejects connection for host \"10.1.3.152\", user \"grafana\", database \"grafana\", SSL off"
```

There are no logs from 

```
grafana-pg-0                        1/1     Running            0          44m
grafana-pg-1                        1/1     Running            0          44m
```

indicating connection failures; neither are there logs from the operator available.

I can't find the file `pg_hba.conf` mentioned in the error message; but from googling, it would seem it's responsible for firewalling ip ranges that are allowed to connect to PGSQL from the outside. Perhaps the loadbalancer makes the connection appear to come from 127.0.0.1 when I connect from the Host but from an internal 10.x.y.z IP when I connect from within Kubernetes? In any case, I hope you read this and take mercy on my soul and help me out. ;)

I've triple and quadruple checked the password; e.g. by doing a `printenv` as the main command of the grafana deployment, so it should be the right password in use. In fact, the deployment is configured as such:

```yaml

      containers:
      - name: grafana
        image: "grafana/grafana"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: "/etc/grafana/grafana.ini"
          subPath: grafana.ini
        - name: sc-datasources-volume
          mountPath: "/etc/grafana/provisioning/datasources"

        ports:
        - name: service
          containerPort: 80
          protocol: TCP
        - name: http
          containerPort: 3000

        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-password
        - name: GF_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: grafana.grafana-pg.credentials
              key: username
        - name: GF_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana.grafana-pg.credentials
              key: password

```

**Comment by FxKu** [comment]
Did you create the grafana role via the manifest? I think, an [infrastructure role](https://github.com/zalando/postgres-operator/blob/master/docs/user.md#infrastructure-roles) is what you want, probably. Which host address are you using to connect to grafana? The one which is listed in the load balancer service?

**Comment by haf-afa** [comment]
It's created via

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: grafana-pg
spec:
  teamId: grafana
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    grafana:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    grafana: grafana  # dbname: owner
  postgresql:
    version: "11"
```

I just want to have a db for the grafana service, really. It's like HelloWorld to me ;) I'm not sure I've created a role -- is that the same as a database owner above?

I actually don't want to monitor pgsql with Grafana nor fetch metrics from it, I just want a persistence store for Grafana's admin features, so is it really an infrastructure role I need?

I have these services:

```

Your database services:
kubectl get svc -n monitoring -l application=spilo -L spilo-role
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE   SPILO-ROLE
grafana-pg          LoadBalancer   10.97.126.188    localhost     5432:31029/TCP   20h   master
grafana-pg-config   ClusterIP      None             <none>        <none>           20h
grafana-pg-repl     ClusterIP      10.102.253.128   <none>        5432/TCP         20h   replica


Your database pods:
kubectl get pods -n monitoring -l application=spilo -L spilo-role
NAME           READY   STATUS    RESTARTS   AGE   SPILO-ROLE
grafana-pg-0   1/1     Running   0          20h   master
grafana-pg-1   1/1     Running   0          20h   replica
```

And I've specified this in grafana.ini:

```ini
# https://grafana.com/docs/installation/configuration/#database
[database]
type = postgres
host = grafana-pg:5432
name = grafana
```
