### ISSUE TITLE
podAnnotations section seems not to work

### ISSUE THREAD

**Issue by thepotatocannon** [zalando/postgres-operator#719]
I tried to add custom annotations to postgres pods using _podAnnotations_ option in the cluster manifest:
```
  podAnnotations:
    prometheus.io/scrape: "true"
```
But it seems that this option does nothing, here are annotations from pods created after deployment:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    status: '{"conn_url":"postgres://10.244.2.178:5432/postgres","api_url":"http://10.244.2.178:8008/patroni","state":"running","role":"replica","version":"1.6.0","xlog_location":1845494080,"timeline":1}'
```
