### ISSUE TITLE
Enable pg_rewind config via manifest

### ISSUE THREAD

**Issue by Jabbl** [zalando/postgres-operator#741]
Half my patroni-cluster recently had a power outage which the active master was affected by.

The master-role was successfully transferred to one of the slaves, but when the power came back the previous master refused to act as a slave, since the timelines had diverged by a couple seconds (the few values the master never got to send to it's slaves).

To fix this, I found the parameters `remove_data_directory_on_rewind_failure` and `remove_data_directory_on_diverged_timelines` [in the patroni documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html), and would like to enable these two.\
However, I have found no way of adding any of these parameters to the `postgres.yaml`.\
I've tried adding them under both the `posgresql` and `patroni` top-level parameters in the cluster manifest, but none of them seems to have worked:
```yaml 
  postgresql:
    version: "11"
  patroni:
    use_pg_rewind: true
    remove_data_directory_on_rewind_failure: true
    remove_data_directory_on_diverged_timelines: true
```

Is there something I'm missing, or is there really no way of adding more `posgres.yml`-parameters through the operator?\
If there isn't, is this something that could be added?

**Comment by FxKu** [comment]
The Patroni struct only allows you to specify the [documented](https://github.com/zalando/postgres-operator/blob/master/docs/reference/cluster_manifest.md#patroni-parameters) fields. Try to use the generic `parameters` field under `postgresql` key which is also passed to Patroni:

```
  postgresql:
    version: "11"
    parameters:
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true
      remove_data_directory_on_diverged_timelines: true
```

By looking at the Patroni docs, I'm not sure if it will work for the two `remove_...` parameters

**Comment by Jabbl** [comment]
It seems `parameters: ` is the wrong place to add these.
The operator complains about the bools it seems:
```
level=debug msg="skipping \"UPDATE\" event for the invalid cluster: json: cannot unmarshal bool into Go struct field PostgresqlParam.parameters of type string" cluster-name=patroni/patroni-cluster pkg=controller
```

Manifest at this point:
```yaml
  postgresql:
    version: "11"
    parameters:
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true
      remove_data_directory_on_diverged_timelines: true
```
