### ISSUE TITLE
Unable to clone from wal on s3: AuthorizationHeaderMalformed - the region 'loca' is wrong

### ISSUE THREAD

**Issue by vitobotta** [zalando/postgres-operator#761]
Hi, I am trying to test cloning from a wal backup on an s3 compatible storage, but whatever I do I get this error:

```
AuthorizationHeaderMalformed: The authorization header is malformed; the region 'loca' is wrong; expecting 'de-fra-1'
```

I'm using Exoscale as s3 compatible storage, and backing up works fine. de-fra-1 is the correct region. I have tried cloning in two ways:

a) adding a `clone` section to the cluster's manifest:

```yaml
  clone:
    uid: "889918f8-0c89-455d-b0bb-8cf0b799c011"
    cluster: "postgres-cluster"
    timestamp: "2020-12-19T12:40:33+00:00"
    s3_endpoint: https://sos-de-fra-1.exo.io
    s3_region: de-fra-1
    s3_access_key_id: ...
    s3_secret_access_key: ...
   s3_wal_path: "s3://mybucket/spilo/postgres-cluster/889918f8-0c89-455d-b0bb-8cf0b799c011/wal"
```

b) in the pod config map

```yaml
  USEWALG_RESTORE: "true" 
  CLONE_WITH_WALE: "true" 
  CLONE_METHOD: CLONE_WITH_WALE
  CLONE_AWS_ACCESS_KEY_ID: ... 
  CLONE_AWS_SECRET_ACCESS_KEY: ...
  CLONE_AWS_ENDPOINT: https://sos-de-fra-1.exo.io 
  CLONE_WAL_S3_BUCKET: mybucket 
  CLONE_WAL_BUCKET_SCOPE_SUFFIX: "/889918f8-0c89-455d-b0bb-8cf0b799c011"
  CLONE_TARGET_TIME: "2025-12-19T12:40:33+00:00"
  CLONE_SCOPE: postgres-cluster 
```

With both methods I get the error about this "loca" region and I have no idea where that region is set/taken from. 

What am I missing? Thanks
