### ISSUE TITLE
CRD-based config attempts to bind the incorrect clusterrole when deploying cluster

### ISSUE THREAD

**Issue by funkypenguin** [zalando/postgres-operator#769]
Hey folks!

I'm using the latest helm chart, and the :latest image. I've deployed the operator into the `postgres-operator` namespace, with the release name `postgres-operator`. Clusterrole and Clusterrolebindings appear to have been created successfully as `postgres-operator`.

When I attempt to apply the [minimal manifest](https://github.com/zalando/postgres-operator/blob/master/manifests/minimal-postgres-manifest.yaml) to a `dev` namespace, the operator logs the following:

```
time="2019-12-17T08:58:50Z" level=info msg="Creating the role binding operator in the namespace dev" pkg=controller
time="2019-12-17T08:58:50Z" level=warning msg="Pods and/or Patroni may misfunction due to the lack of permissions: could not create role binding operator : cannot bind the pod service account \"operator\" defined in the config map to the cluster role in the \"dev\" namespace: clusterroles.rbac.authorization.k8s.io \"operator\" not found" pkg=controller
```

Thing is, the clusterrole is called `postgres-operator`, not `operator`, and I'm thinking that this is why the attempted role binding has failed.

I'm using the CRD-based `values-crd.yml` with helm v2, on Kubernetes 1.16, with the default values per the repo.

Am I missing something? :)

Thanks!
David

**Comment by FxKu** [comment]
Hm, I've seen this error before. When we started with helm charts we specified the `operator` service account in the [values-crd.yaml](https://github.com/zalando/postgres-operator/blob/182e3bc7db0fd6c7b2617286c324167c7f0c158e/charts/postgres-operator/values-crd.yaml#L271). You could try this as well in the meantime while I will try to reproduce this error.

**Comment by frittentheke** [comment]
@FxKu  isn't this the issue https://github.com/zalando/postgres-operator/issues/528 ?

**Comment by funkypenguin** [comment]
I added the suggested workaround to values-crd.yaml (snippet below), but this doesn't seem to have altered the behaviour. The workaround was intended for values.yaml though, does it need to be adapted for the CRD?

```
<snip>
# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

postgres-operator:
  config:
    pod_service_account_role_binding_definition: |
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: RoleBinding
      metadata:
        name: postgres-operator
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: postgres-operator
      subjects:
      - kind: ServiceAccount
        name: postgres-operator 
```
