### ISSUE TITLE
Failed to run logical backup cronjob:  CLUSTER_NAME_LABEL: unbound variable

### ISSUE THREAD

**Issue by gemoya** [zalando/postgres-operator#774]
Hi,

I'm trying to check the logical backups cronjobs, but it fails with:
```
+ export CURRENT_NODENAME
+ for search in "${search_strategy[@]}"
++ eval list_all_replica_pods_current_node
+++ list_all_replica_pods_current_node
/dump.sh: line 71: CLUSTER_NAME_LABEL: unbound variable
+++ head -n 1
+ PGHOST=
```

I have deployed postgres-operator v1.3.0 from helm-chart using helmv3 with configmap option, my values at configKubernetes are:
```
configKubernetes:
  # default DNS domain of K8s cluster where operator is running
  cluster_domain: cluster.local
  # additional labels assigned to the cluster objects
  cluster_labels: application:spilo
  # label assigned to Kubernetes objects created by the operator
  cluster_name_label: version
  # annotations attached to each database pod
  # custom_pod_annotations: "keya:valuea,keyb:valueb"

  # enables initContainers to run actions before Spilo is started
  enable_init_containers: "true"
  # toggles pod anti affinity on the Postgres pods
  enable_pod_antiaffinity: "false"
  # toggles PDB to set to MinAvailabe 0 or 1
  enable_pod_disruption_budget: "true"
  # enables sidecar containers to run alongside Spilo in the same pod
  enable_sidecars: "true"
  # name of the secret containing infrastructure roles names and passwords
  # infrastructure_roles_secret_name: postgresql-infrastructure-roles

  # list of labels that can be inherited from the cluster manifest
  inherited_labels: application,environment,version

  # timeout for successful migration of master pods from unschedulable node
  # master_pod_move_timeout: 20m

  # set of labels that a running and active node should possess to be considered ready
  # node_readiness_label: ""

  # name of the secret containing the OAuth2 token to pass to the teams API
  # oauth_token_secret_name: postgresql-operator

  # defines the template for PDB (Pod Disruption Budget) names
  pdb_name_format: "postgres-{cluster}-pdb"
  # override topology key for pod anti affinity
  pod_antiaffinity_topology_key: "kubernetes.io/hostname"
  # name of the ConfigMap with environment variables to populate on every pod
  # pod_environment_configmap: ""

  # specify the pod management policy of stateful sets of Postgres clusters
  pod_management_policy: "ordered_ready"
  # label assigned to the Postgres pods (and services/endpoints)
  pod_role_label: spilo-role
  # Postgres pods are terminated forcefully after this timeout
  pod_terminate_grace_period: 5m
  # template for database user secrets generated by the operator
  secret_name_template: '{username}.{cluster}.credentials'
  # group ID with write-access to volumes (required to run Spilo as non-root process)
  # spilo_fsgroup: "103"

  # whether the Spilo container should run in privileged mode
  spilo_privileged: "false"
  # operator watches for postgres objects in the given namespace
  watched_namespace: "*"  # listen to all namespaces
```
Additionally at configLogicalBackup I have:
```
configLogicalBackup:
  # image for pods of the logical backup job (example runs pg_dumpall)
  logical_backup_docker_image: "registry.opensource.zalan.do/acid/logical-backup"
  # S3 Access Key ID
  logical_backup_s3_access_key_id: "secret"
  # S3 bucket to store backup results
  logical_backup_s3_bucket: "BUCKET_MAME"
  # S3 endpoint url when not using AWS
  logical_backup_s3_endpoint: ""
  # S3 Secret Access Key
  logical_backup_s3_secret_access_key: "secret"
  # S3 server side encription
  logical_backup_s3_sse: "AES256"
  # backup schedule in the cron format
  logical_backup_schedule: "*/10 * * * *"
```
My postgresql cluster spec has this config:
```
  enableLogicalBackup: true
  logicalBackupSchedule: "*/10 * * * *"
```
The generated pods by cronjob have the following labels:
```
Name:           logical-backup-acid-test-cluster-gemoya-1577369400-qbkrn
Namespace:      gemoya
Priority:       0
Node:           -
Start Time:     Thu, 26 Dec 2019 11:11:18 -0300
Labels:         application=spilo-logical-backup
                controller-uid=6adbf3ee-27e9-11ea-836a-1231276944d8
                job-name=logical-backup-acid-test-cluster-gemoya-1577369400
                version=acid-test-cluster-gemoya
Annotations:    cni.projectcalico.org/podIP: x.x.x.x/32
Status:         Failed
IP:             -
IPs:            <none>
Controlled By:  Job/logical-backup-acid-test-cluster-gemoya-1577369400
```

The environment from logical-backup pod has:
```
 - env:
    - name: SCOPE
      value: acid-test-cluster-gemoya
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: LOGICAL_BACKUP_S3_BUCKET
      value: zalando-operator-logical-backup
    - name: LOGICAL_BACKUP_S3_BUCKET_SCOPE_SUFFIX
      value: /55941946-27e8-11ea-93fb-028335d86a29
    - name: PG_VERSION
      value: "11"
    - name: PGPORT
      value: "5432"
    - name: PGUSER
      value: postgres
    - name: PGDATABASE
      value: postgres
    - name: PGSSLMODE
      value: require
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: postgres.acid-test-cluster-gemoya.credentials
```
I don't see any relation to `CLUSTER_NAME_LABEL` at pod spec so Am I missing some configuration? where should be  `CLUSTER_NAME_LABEL` defined ? AFAIK there is some relation between `cluster_name_label: version` and pod's label with `version=acid-test-cluster-gemoya` but I don't see where the pod take those values.

**Comment by gemoya** [comment]
We have checked the code and we have there are some environment injection by postgres-operator at cronjob creation, so we changed operator's image tag to `latest`  and now we can see this at pod environmnent:
```
  containers:
  - env:
    - name: SCOPE
      value: acid-test-cluster-gemoya
    - name: CLUSTER_NAME_LABEL
      value: version
...
```
Do you have plans to get this changes to an image with some tag like v1.3.x or something like that?
