### ISSUE TITLE
Clone from gcs using wal-g

### ISSUE THREAD

**Issue by jaroslav-muller** [zalando/postgres-operator#788]
Hi,
I created a cluster that backups using wal-g to gcs. However when I try to clone that cluster (to point in time) from gcs it fails.
The source of failure is that envdir `/home/postgres/etc/wal-e.d/env-clone-jarin-db-cluster` doesn't contain variables that are needed (and are present in `/home/postgres/etc/wal-e.d/env`.
I can actually make the clone work by manually copying two variables from env to env-clone-jarin-db-cluster - `GOOGLE_APPLICATION_CREDENTIALS` and `USE_WALG_RESTORE`.

I use custom `postgres-pod-config.yaml` to set the variables:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: default
data:
  USE_WALG_BACKUP: true
  USE_WALG_RESTORE: true
  WALG_GS_PREFIX: gs://jarin-test-backup/spilo/$(SCOPE)
  CLONE_WALG_GS_PREFIX: gs://jarin-test-backup/spilo/$(CLONE_SCOPE)
  WALE_BACKUP_THRESHOLD_PERCENTAGE: "100"
  GOOGLE_APPLICATION_CREDENTIALS: /gcs/backup-google-credentials.json
```
Is there a way to set env variables in the clone envdir? If not I'd consider it a bug.
