### ISSUE TITLE
Operator cannot move pod, in case of using node_readiness_label 

### ISSUE THREAD

**Issue by DeamonMV** [zalando/postgres-operator#792]
Hello.

### What is a problem 

Operator not able to move pod when node_readiness_label was deleted from k8s node and this node was cordoned. 

```
time="2020-01-14T14:38:32Z" level=warning msg="failed to move master pods from the node \"test-k8s-worker-2\": timeout of 0s minutes expired" pkg=controller
```

### What is my ENV

Part of OperatorConfiguration:
```
apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: postgresql-operator-configuration
configuration:
  etcd_host: ""
  docker_image: registry.opensource.zalan.do/acid/spilo-11:1.6-p1
.....................................................................
    node_readiness_label:
      lifecycle-status: ready
```

Postgres Operator image `registry.opensource.zalan.do/acid/postgres-operator:v1.3.0`

That is how configured workers, as you can see one of them cordoned and does not have appropriate label  

```
test-k8s-worker-1   Ready                      <none>   92d   v1.13.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,ceph-role=worker,kubernetes.io/hostname=test-k8s-worker-1,lifecycle-status=ready
test-k8s-worker-2   Ready,SchedulingDisabled   <none>   92d   v1.13.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,ceph-role=worker,kubernetes.io/hostname=test-k8s-worker-2
test-k8s-worker-3   Ready                      <none>   92d   v1.13.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,ceph-role=worker,kubernetes.io/hostname=test-k8s-worker-3,lifecycle-status=ready
```

Pods:
```
grafana-acid-postgres-0                     2/2     Running     0          176m    10.233.81.7    test-k8s-worker-3   <none>           <none>
grafana-acid-postgres-1                     2/2     Running     0          176m    10.233.64.10   test-k8s-worker-2   <none>           <none>```


### What I want to achieve

It will be good if operator was able to reschedule pod from unlabeled and cordoned , to another k8s node

**Comment by FxKu** [comment]
Is this `timeout of 0s minutes expired` the only message you see? Did you configured the `0s`? So immediate timeout? :smiley: 

Looking at the [code](https://github.com/zalando/postgres-operator/blob/e6ce00050f84dd2d894da1e7718e54e80f9945f4/pkg/controller/node.go#L176) makes me wonder, if the move is even tried once. Especially, when you don't see the inner error message in the logs. 

And btw, use the `v1.3.1` image, please.

**Comment by DeamonMV** [comment]
@FxKu thank you for quick response)

>Is this timeout of 0s minutes expired the only message you see?

Yes, only this. As a first step - I do  unlabel, wait for 5 sec and do cordon, after this i see this message and that all.

> Did you configured the 0s? So immediate timeout? 😃

I'm use "default" configuration, copy-pasted from Github. Section with timeouts looks like this

```
  timeouts:
    pod_label_wait_timeout: 10m
    pod_deletion_wait_timeout: 10m
    ready_wait_interval: 4s
    ready_wait_timeout: 30s
    resource_check_interval: 3s
    resource_check_timeout: 10m
```

Updated operator to 1.3.1 - this didn't helped.
