### ISSUE TITLE
postgres-operator and cluster in different namespace result in operator being unable to initdb

### ISSUE THREAD

**Issue by vfrans** [zalando/postgres-operator#806]
Hello,

I'm trying to use the postgres-operator in a different namespace than the namespace of the managed cluster.

Here is my config:

Namespace of the operator:
```
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
```
Default service account rbac from install instructions.
```
Operator:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator
  template:
    metadata:
      labels:
        name: postgres-operator
    spec:
      serviceAccountName: zalando-postgres-operator
      containers:
      - name: postgres-operator
        image: registry.opensource.zalan.do/acid/postgres-operator:v1.3.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 250Mi
          limits:
            cpu: 2000m
            memory: 500Mi
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        env:
        # provided additional ENV vars can overwrite individual config map entries
        - name: CONFIG_MAP_NAME
          value: "postgres-operator"
```
Cluster:
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: cluster-namespace
spec:
  teamId: "acid"
  volume:
    size: 1Gi
    storageClass: postgres-storageclass
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
  databases:
    foo: zalando  # dbname: owner
  postgresql:
    version: "11"
```
I'm pretty sure i'm missing some rbac access here and there but the strange behavior is that the cluster ends up in the CreateFailed status with the following logs:
```
time="2020-01-28T14:31:42Z" level=info msg="waiting for the cluster being ready" cluster-name=cluster-namespace/acid-minimal-cluster pkg=cluster worker=0
time="2020-01-28T14:37:03Z" level=debug msg="Waiting for 2 pods to become ready" cluster-name=cluster-namespace/acid-minimal-cluster pkg=cluster worker=0
time="2020-01-28T14:37:45Z" level=info msg="pods are ready" cluster-name=cluster-namespace/acid-minimal-cluster pkg=cluster worker=0
time="2020-01-28T14:37:45Z" level=error msg="could not create cluster: could not create users: could not init db connection: could not init db connection: pq: password authentication failed for user \"postgres\"" cluster-name=cluster-namespace/acid-minimal-cluster pkg=controller worker=0
```
What am i missing here?

**Comment by FxKu** [comment]
Logs say pod are ready. Hm, can you

- check the logs from DB pods?
- exec into Pod to see if Postgres is running?
- look if secrets were created for postgres user of acid.minimal-cluster?

Which K8s environment are you using?

**Comment by vfrans** [comment]
Sure, here you are:
Logs:
On pod -0:
```
...
(usual sql statement while bootstraping the cluser)
...
CREATE FUNCTION
REVOKE
GRANT
GRANT
CREATE VIEW
REVOKE
GRANT
GRANT
RESET
2020-01-28 14:37:40,075 INFO: Lock owner: acid-minimal-cluster-0; I am acid-minimal-cluster-0
2020-01-28 14:37:40,096 INFO: no action.  i am the leader with the lock
(repeats that he is master)
...
```
On pod -1:
```
2020-01-28 15:31:44,718 INFO: Lock owner: acid-minimal-cluster-0; I am acid-minimal-cluster-1
2020-01-28 15:31:44,718 INFO: does not have lock
2020-01-28 15:31:44,739 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 653, in get_local_timeline_lsn_from_replication_connection
    with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 647, in get_replication_connection_cursor
    with get_connection_cursor(**conn_kwargs) as cur:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
    with psycopg2.connect(**kwargs) as conn:
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "standby"
FATAL:  no pg_hba.conf entry for replication connection from host "::1", user "standby", SSL off
```

Execs:
On pod -0:
```root@acid-minimal-cluster-0:/home/postgres# ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      1949  0.7  0.2  22032  4244 pts/0    Ss   15:37   0:00 /bin/bash
root      1969  0.0  0.1  37788  3268 pts/0    R+   15:37   0:00  \_ ps faux
root         1  0.0  0.0   4380   636 ?        Ss   14:36   0:00 /usr/bin/dumb-init -c --rewrite 1:0 -- /bin/sh /launch.sh
root        11  0.0  0.0   4624   672 ?        S    14:37   0:00 /bin/sh /launch.sh
root        24  0.0  0.0   4548   776 ?        S    14:37   0:00  \_ /usr/bin/runsvdir -P /etc/service
root        25  0.0  0.0   4396   748 ?        Ss   14:37   0:00      \_ runsv pgqd
postgres    28  0.0  0.3 108040  7964 ?        S    14:37   0:00      |   \_ /usr/bin/pgqd /home/postgres/pgq_ticker.ini
root        26  0.0  0.0   4396   744 ?        Ss   14:37   0:00      \_ runsv cron
root        29  0.0  0.1  28352  2652 ?        S    14:37   0:00      |   \_ /usr/sbin/cron -f
root        27  0.0  0.0   4396   684 ?        Ss   14:37   0:00      \_ runsv patroni
postgres    30  0.0  1.7 619004 36776 ?        Sl   14:37   0:03          \_ /usr/bin/python3 /usr/local/bin/patroni /home/postgres/postgres.yml
postgres    60  0.0  1.6 426900 33700 ?        S    14:37   0:01 /usr/lib/postgresql/11/bin/postgres -D /home/postgres/pgdata/pgroot/data --config-file=/home/postgres/pgdata/pgro
postgres    62  0.0  0.1 195408  3576 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: logger
postgres    64  0.5  0.6 509912 12304 ?        Ssl  14:37   0:18  \_ postgres: acid-minimal-cluster: bg_mon
postgres    67  0.0  0.9 427136 18500 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: checkpointer
postgres    68  0.0  0.3 427036  6692 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: background writer
postgres    69  0.0  0.2 197788  4592 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: stats collector
postgres    74  0.0  0.7 428464 16176 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: postgres postgres [local] idle
postgres    90  0.0  0.5 426900 11388 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: walwriter
postgres    91  0.0  0.3 427616  6724 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: autovacuum launcher
postgres    92  0.0  0.2 197528  5588 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: archiver   last was 000000020000000000000007
postgres    93  0.0  0.5 427936 11752 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: pg_cron scheduler
postgres    94  0.0  0.3 427448  6792 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: TimescaleDB Background Worker Launcher
postgres    95  0.0  0.3 427448  6452 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: logical replication launcher
```
On pod -1:
```
root@acid-minimal-cluster-1:/home/postgres# ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      2608  1.0  0.2  22028  4240 pts/0    Ss   15:37   0:00 /bin/bash
root      2626  0.0  0.1  37788  3380 pts/0    R+   15:37   0:00  \_ ps faux
root         1  0.0  0.0   4380   796 ?        Ss   14:37   0:00 /usr/bin/dumb-init -c --rewrite 1:0 -- /bin/sh /launch.sh
root        12  0.0  0.0   4624   856 ?        S    14:37   0:00 /bin/sh /launch.sh
root        25  0.0  0.0   4548   812 ?        S    14:37   0:00  \_ /usr/bin/runsvdir -P /etc/service
root        26  0.0  0.0   4396   796 ?        Ss   14:37   0:00      \_ runsv pgqd
postgres    30  0.0  0.1  18372  3104 ?        S    14:37   0:00      |   \_ /bin/bash /scripts/patroni_wait.sh --role master -- /usr/bin/pgqd /home/postgres/pgq_ticker.ini
postgres  2601  0.0  0.0   4528   800 ?        S    15:37   0:00      |       \_ sleep 60
root        27  0.0  0.0   4396   732 ?        Ss   14:37   0:00      \_ runsv cron
root        29  0.0  0.1  28352  2676 ?        S    14:37   0:00      |   \_ /usr/sbin/cron -f
root        28  0.0  0.0   4396   820 ?        Ss   14:37   0:00      \_ runsv patroni
postgres    31  0.1  1.8 619016 36936 ?        Sl   14:37   0:05          \_ /usr/bin/python3 /usr/local/bin/patroni /home/postgres/postgres.yml
postgres    62  0.0  1.6 426900 33988 ?        S    14:37   0:01 /usr/lib/postgresql/11/bin/postgres -D /home/postgres/pgdata/pgroot/data --config-file=/home/postgres/pgdata/pgro
postgres    64  0.0  0.1 195408  3520 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: logger
postgres    65  0.0  0.3 427032  6144 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: startup   recovering 00000003000000000000000A
postgres    66  0.5  0.5 509864 11744 ?        Ssl  14:37   0:18  \_ postgres: acid-minimal-cluster: bg_mon
postgres    69  0.0  0.2 426900  4116 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: checkpointer
postgres    70  0.0  0.2 426900  4116 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: background writer
postgres    71  0.0  0.1 197660  3552 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: stats collector
postgres    78  0.0  0.7 428320 15000 ?        Ss   14:37   0:00  \_ postgres: acid-minimal-cluster: postgres postgres [local] idle
```

Secrets:
```
francois@Datapartner-MBP 5. postgres-database % kubectl get secret -n cluster-namespace
NAME                                        TYPE                                  DATA   AGE
default-token-f8dqp                         kubernetes.io/service-account-token   3      80m
postgres.acid-minimal-cluster.credentials   Opaque                                2      80m
standby.acid-minimal-cluster.credentials    Opaque                                2      80m
zalando-postgres-operator-token-6ldtn       kubernetes.io/service-account-token   3      80m
zalando.acid-minimal-cluster.credentials    Opaque                                2      69m
```
```
francois@Datapartner-MBP 5. postgres-database % kubectl get secret -n postgres-operator
NAME                                    TYPE                                  DATA   AGE
default-token-zwd7s                     kubernetes.io/service-account-token   3      94m
zalando-postgres-operator-token-7kh55   kubernetes.io/service-account-token   3      94m
```

I'm using kind with the following configuration if that is of any interest to you :)
```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /Users/francois/git/k8s/data/pg0
    containerPath: /db
  - hostPath: /Users/francois/git/k8s/data/zk0
    containerPath: /zk
  - hostPath: /Users/francois/git/k8s/data/kafka0
    containerPath: /kafka
- role: worker
  extraMounts:
  - hostPath: /Users/francois/git/k8s/data/pg1
    containerPath: /db
  - hostPath: /Users/francois/git/k8s/data/zk1
    containerPath: /zk
  - hostPath: /Users/francois/git/k8s/data/kafka1
    containerPath: /kafka
- role: worker
- role: worker
  extraMounts:
  - hostPath: /Users/francois/git/k8s/postgres-localvolumes/data/pg3
    containerPath: /db
  - hostPath: /Users/francois/git/k8s/data/zk3
    containerPath: /zk
  - hostPath: /Users/francois/git/k8s/data/kafka3
    containerPath: /kafka
```
