### ISSUE TITLE
master service gets no selectors on OpenShift

### ISSUE THREAD

**Issue by dejwsz** [zalando/postgres-operator#855]
Service for masters gets no selectors at all - they must be added manually. Without this cluster is not able to sync properly. Tested with operator 1.3.1 and spilo image: registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p16.
I needed to patch my "test-minimal-cluster" service dedicated to master PODs adding such 
```
selectors:
  selector:
    application: spilo
    cluster-name: test-minimal-cluster
    spilo-role: master
```
Replica service has selectors in place so it is fine. This is probably a bug?
