### ISSUE TITLE
Adding new user and database to already existing cluster does not work

### ISSUE THREAD

**Issue by vfrans** [zalando/postgres-operator#878]
Hello,

After having deployed a cluster with the following deploy file:
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: somename
  namespace: somesoft
spec:
  teamId: "somesoftcompany"
  volume:
    size: 1Gi
    storageClass: postgres-storageclass
  numberOfInstances: 3
  users:
    softwareuser:
  databases:
    softwaredb: softwareuser  # dbname: owner
  postgresql:
    version: "11"
    parameters:
      shared_buffers: "256MB"
      log_min_duration_statement: "1s"
      log_statement: "ddl"
      log_connections: "on"
      log_disconnections: "on"
      log_checkpoints: "on"
      checkpoint_timeout: "5min"
      max_connections: "500"
      wal_log_hints: "on"
```
However, after adding user and db "keycloak" with the following deploy:
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: somename
  namespace: somesoft
spec:
  teamId: "somesoftcompany"
  volume:
    size: 1Gi
    storageClass: postgres-storageclass
  numberOfInstances: 3
  users:
    softwareuser:
    keycloak:
  databases:
    softwaredb: softwareuser  # dbname: owner
    keycloak: keycloak
  postgresql:
    version: "11"
    parameters:
      shared_buffers: "256MB"
      log_min_duration_statement: "1s"
      log_statement: "ddl"
      log_connections: "on"
      log_disconnections: "on"
      log_checkpoints: "on"
      checkpoint_timeout: "5min"
      max_connections: "500"
      wal_log_hints: "on"
```
This is displayed in the operator logs:
```time="2020-03-25T14:59:39Z" level=info msg="syncing databases" cluster-name=somesoft/somename pkg=cluster worker=0
time="2020-03-25T14:59:39Z" level=info msg="skipping creation of the \"keycloak\" database, user \"keycloak\" does not exist" cluster-name=somesoft/somename pkg=cluster worker=0
time="2020-03-25T14:59:39Z" level=debug msg="closing database connection" cluster-name=somesoft/somename pkg=cluster worker=0
time="2020-03-25T14:59:39Z" level=info msg="cluster has been updated" cluster-name=somesoft/somename pkg=controller worker=0
```

However, (as you can see) keycloak user is present in the user list...

What am I missing?

thanks a lot,
