### ISSUE TITLE
unsafe management of s3 key and secret

### ISSUE THREAD

**Issue by cortopy** [zalando/postgres-operator#915]
I've tried many variations but it all seems that the management of aws s3 secrets is unsafe in the operator.

The key is and secret in `logical_backup` gets passed to the Job as environment variables in plain text, and so it's enough to just inspect the pod to get the values of the secrets.

Also, in the case of WAL uploads to s3, I need to create a [configMap](https://postgres-operator.readthedocs.io/en/latest/administrator/#custom-pod-environment-variables) to pass aws/s3 secrets to the cluster pods. Without the configMap, the pod doesn't get `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` and so there are no uploads of WAL files to s3 bucket.

This means that:
- Keys are passed around in plain text
- Patroni aws secrets live unsecurely in a configMap 
- Secrets mounted in the pod are accessible with a simple `kubectl describe`

I'm using S3 compatible storage by UKFast with the following cluster config (using CDR):

```yaml
aws_or_gcp:
    aws_region: ""
    log_s3_bucket: postgres-log-staging
    wal_s3_bucket: postgres-wal-staging
logical_backup:
    logical_backup_docker_image: registry.opensource.zalan.do/acid/logical-backup
    logical_backup_s3_access_key_id: "<key-id>"
    logical_backup_s3_bucket: <buckey-name>
    logical_backup_s3_endpoint: vault.ecloud.co.uk
    logical_backup_s3_region: ''
    logical_backup_s3_secret_access_key: "<secret>"
    logical_backup_s3_sse: ''
    logical_backup_schedule: 30 02 * * *
```
