### ISSUE TITLE
Cluster nodes restarts on resync

### ISSUE THREAD

**Issue by b8rq** [zalando/postgres-operator#927]
I'm trying to start using postgresql-operator and I have a trouble: my clusters are restarts every 30 minutes.

As far as I can see, this time is due to cluster' parameter `resync_period` (exactly 30 minutes by default). When I change `resync_period`,  restart period changes too.

Restarting cluster nodes on resync — is it intended behaviour or a problem?

My configs are listed below, logs are attached

## OperatorConfiguration
```yaml
apiVersion: acid.zalan.do/v1
kind: OperatorConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: zalando
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgres-operator
    helm.sh/chart: postgres-operator-1.4.0
  name: zalando-postgres-operator
  namespace: zalando-postgres-operator
configuration:
  aws_or_gcp:
    aws_region: eu-central-1
  debug:
    debug_logging: true
    enable_database_access: true
  docker_image: acid/spilo-12:1.6-p2
  enable_crd_validation: true
  enable_shm_volume: true
  etcd_host: etcd-postgres-cluster-client.zalando-postgres-operator:2379
  kubernetes:
    cluster_domain: cluster.local
    cluster_labels:
      application: spilo
    cluster_name_label: cluster-name
    enable_init_containers: true
    enable_pod_antiaffinity: true
    enable_pod_disruption_budget: false
    enable_sidecars: true
    oauth_token_secret_name: zalando-postgres-operator
    pdb_name_format: postgres-{cluster}-pdb
    pod_antiaffinity_topology_key: kubernetes.io/hostname
    pod_management_policy: ordered_ready
    pod_role_label: spilo-role
    pod_service_account_name: postgres-pod
    pod_terminate_grace_period: 5m
    secret_name_template: '{username}.{cluster}.credentials.{tprkind}.{tprgroup}'
    spilo_privileged: false
    watched_namespace: '*'
  load_balancer:
    custom_service_annotations:
      metallb.universe.tf/address-pool: shared-pool
    db_hosted_zone: db.example.com
    enable_master_load_balancer: false
    enable_replica_load_balancer: false
    master_dns_name_format: '{cluster}.{team}.{hostedzone}'
    replica_dns_name_format: '{cluster}-repl.{team}.{hostedzone}'
  logging_rest_api:
    api_port: 8080
    cluster_history_entries: 1000
    ring_log_lines: 100
  logical_backup:
    logical_backup_docker_image: acid/logical-backup
    logical_backup_s3_access_key_id: KEYID
    logical_backup_s3_bucket: zalando-porstgresql-operator
    logical_backup_s3_endpoint: S3
    logical_backup_s3_region: REGION
    logical_backup_s3_secret_access_key: KEY
    logical_backup_s3_sse: AES256
    logical_backup_schedule: 0 * * * *
  max_instances: -1
  min_instances: -1
  postgres_pod_resources:
    default_cpu_limit: "1"
    default_cpu_request: 100m
    default_memory_limit: 500Mi
    default_memory_request: 100Mi
    min_cpu_limit: 250m
    min_memory_limit: 250Mi
  repair_period: 5m
  resync_period: 30m
  scalyr:
    scalyr_cpu_limit: "1"
    scalyr_cpu_request: 100m
    scalyr_memory_limit: 500Mi
    scalyr_memory_request: 50Mi
  teams_api:
    enable_team_superuser: false
    enable_teams_api: false
    pam_role_name: zalandos
    protected_role_names:
    - admin
    team_admin_role: admin
    team_api_role_configuration:
      log_statement: all
  timeouts:
    pod_deletion_wait_timeout: 10m
    pod_label_wait_timeout: 10m
    ready_wait_interval: 3s
    ready_wait_timeout: 30s
    resource_check_interval: 3s
    resource_check_timeout: 10m
  users:
    replication_username: standby
    super_username: postgres
  workers: 4
```

## postgresql 
```yaml
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: xavier
  name: xavier-postgresql-test
  namespace: xavier-develop
spec:
  allowedSourceRanges:
  - 0.0.0.0/0
  connectionPooler:
    mode: transaction
    numberOfInstances: 2
    resources:
      limits:
        cpu: "1"
        memory: 100Mi
      requests:
        cpu: 500m
        memory: 100Mi
    schema: pooler
    user: pooler
  enableConnectionPooler: true
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  numberOfInstances: 2
  patroni:
    pg_hba:
    - hostnossl all all all md5
    ttl: 60
  postgresql:
    version: "12"
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 4Gi
  sidecars:
  - env:
    - name: DATA_SOURCE_URI
      value: 127.0.0.1:5432/postgres?sslmode=disable
    - name: DATA_SOURCE_USER
      value: postgres
    - name: DATA_SOURCE_PASS
      valueFrom:
        secretKeyRef:
          key: password
          name: postgres.xavier-postgresql-test.credentials.postgresql.acid.zalan.do
    image: postgres-exporter:v0.8.0
    name: exporter
    ports:
    - containerPort: 9187
      name: metrics
  teamId: xavier
  volume:
    size: 50Gi
status:
  PostgresClusterStatus: Running
```
[operator_logs.txt](https://github.com/zalando/postgres-operator/files/4524031/operator_logs.txt)
[pg_logs.txt](https://github.com/zalando/postgres-operator/files/4524032/pg_logs.txt)

**Comment by FxKu** [comment]
Hm, it's confusing to find `xavier-postgresql-test-2` in the logs and number of instances is 2 in your manifest. Did you scaled in before? Was there some error so that the rolling update annotation remained true? The operator logs start with the typical lines when the operator is launched. You should print on sync cycle so that we can see what go's wrong.

**Comment by frittentheke** [comment]
@FxKu  @b8rq could this be causes by this issue https://github.com/zalando/postgres-operator/issues/924 maybe?

**Comment by evilrussian** [comment]
@frittentheke maybe that it is

I see #924  is fixed in PR https://github.com/zalando/postgres-operator/pull/890 (version v1.5.0)

But we still have problem in v1.5.0

When we making sidecar's with this port protocol description all fine:
```
      ports:
      - containerPort: 9187
        name: metrics
        protocol: TCP
```
When we making sidecar's without defining port protocol, operator sees diff's and recreating cluster due resync period:
```
      ports:
      - containerPort: 9187
        name: metrics
```
```
spec diff between old and new statefulsets: \nTemplate.Spec.Containers[0].Resources.Limits["cpu"].i.value: 8 != 8000\nTemplate.Spec.Containers[0].Resources.Limits["cpu"].i.scale: 0 != -3\nTemplate.Spec.Containers[0].Resources.Limits["cpu"].s: "8" != ""\nTemplate.Spec.Containers[0].TerminationMessagePath: "/dev/termination-log" != ""\nTemplate.Spec.Containers[0].TerminationMessagePolicy: "File" != ""\nTemplate.Spec.Containers[1].Ports[0].Protocol: "TCP" != ""\nTemplate.Spec.Containers[1].TerminationMessagePath: "/dev/termination-log" != ""\nTemplate.Spec.Containers[1].TerminationMessagePolicy: "File" != ""\nTemplate.Spec.Containers[1].ImagePullPolicy: "IfNotPresent" != ""\nTemplate.Spec.Containers[2].TerminationMessagePath: "/dev/termination-log" != ""\nTemplate.Spec.Containers[2].TerminationMessagePolicy: "File" != ""\nTemplate.Spec.Containers[2].ImagePullPolicy: "IfNotPresent" != ""\nTemplate.Spec.RestartPolicy: "Always" != ""\nTemplate.Spec.DNSPolicy: "ClusterFirst" != ""\nTemplate.Spec.DeprecatedServiceAccount: "postgres-pod" != ""\nTemplate.Spec.SchedulerName: "default-scheduler" != ""\nTemplate.Spec.Tolerations: []v1.Toleration(nil) != []v1.Toleration{}\nVolumeClaimTemplates[0].Status.Phase: "Pending" != ""\nRevisionHistoryLimit: &int32(10) != nil\n" cluster-name=postgres-operator/ha-postgresql-cluster pkg=cluster
```
