### ISSUE TITLE
How to enable TimescaleDB for a cluster?

### ISSUE THREAD

**Issue by bergkvist** [zalando/postgres-operator#938]
## Logging into the container
```
$ kubectl exec -it acid-test-0 sh
# psql -U postgres

postgres=# CREATE EXTENSION postgis;
CREATE EXTENSION

postgres=# ALTER EXTENSION timescaledb UPDATE;
ERROR:  extension "timescaledb" does not exist

postgres=# CREATE EXTENSION timescaledb;
ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/timescaledb.control": No such file or directory
```

## From the README:
![image](https://user-images.githubusercontent.com/410028/80402626-723d3880-88be-11ea-9a20-0119e5955937.png)

I've followed the quickstart guide, and added the following:
### postgres-operator
```sh
git clone https://github.com/zalando/postgres-operator.git
cd postgres-operator

kubectl create -f manifests/configmap.yaml  # configuration
kubectl create -f manifests/operator-service-account-rbac.yaml  # identity and permissions
kubectl create -f manifests/postgres-operator.yaml  # deployment
kubectl create -f manifests/api-service.yaml  # operator API to be used by UI
```

### postgres-operator-ui
```sh
kubectl apply -f ui/manifests/
kubectl port-forward "$(kubectl get pod -l name=postgres-operator-ui --output='name')" 8081
```

### A cluster:
![image](https://user-images.githubusercontent.com/410028/80403373-c72d7e80-88bf-11ea-8116-16392c37fb5d.png)
![image](https://user-images.githubusercontent.com/410028/80403237-9c432a80-88bf-11ea-85c4-df079555fff1.png)

**Comment by FxKu** [comment]
Afaik, in the used Spilo image timescale extension is not available for Postgres 12. Use 11 and you should find. However, the next Spilo release will [have](https://github.com/zalando/spilo/pull/431) it.

**Comment by bergkvist** [comment]
Yeah, you were right about the postgres version being the reason. It seems to work with Postgres 11.
![image](https://user-images.githubusercontent.com/410028/80524316-b51b1100-898f-11ea-927e-f34a06d8f053.png)

When will the new Spilo release be available?

**Comment by FxKu** [comment]
Use `registry.opensource.zalan.do/acid/spilo-cdp-12:1.6-p115`. This is the image we will also ship with the new operator release.

**Comment by andy-v-h** [comment]
@bergkvist  I'm struggling to get timescaledb too, what was the prepared db yaml you added?

**Comment by manuel-koch** [comment]
I created a new cluster using latest helm chart (v1.7.1) and don's see a timescaledb extension in the running postgres instances.

The used image is `registry.opensource.zalan.do/acid/spilo-14:2.1-p3`

```
testdb=# SHOW extwlist.extensions;
                                                    extwlist.extensions
---------------------------------------------------------------------------------------------------------------------------
 btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,hypopg,pg_partman
 
 testdb=# SHOW shared_preload_libraries ;
                             shared_preload_libraries
----------------------------------------------------------------------------------
 bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,pg_cron,pg_stat_kcache
 ```

**Comment by ffais** [comment]
I'm using the latest version of the operator (1.8.2) installed with helm.
I have tried both solutions proposed by @manuel-koch , but the automatic loading of timescaledb doesn't work.
Adding the extension with psql works!
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgresql-test-cluster
  namespace: playngo-dev
spec:
  teamId: "postgresql"
  volume:
    size: 128Gi
  numberOfInstances: 1
  users:
    gamificationstats:  # database owner
    - superuser
    - createdb
  databases:
    gamificationstats: gamificationstats
  preparedDatabases:
    gamificationstats:
      extensions:
        timescaledb: "public"
  postgresql:
    version: "14"
```
