### ISSUE TITLE
unable to recognize "STDIN": no matches for kind "postgresql" in version "acid.zalan.do/v1"

### ISSUE THREAD

**Issue by tparrott-cse** [zalando/postgres-operator#959]
Hey there,

I'm currently trying to replace my Postgres container with a PGO and have started with the manifests provided in order to try to get something going.  I'm using the a very basic manifest for the deployment:

```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: test-minimal-cluster
  namespace: api
spec:
  teamId: "test"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    test_user:  # database owner
    - superuser
    - createdb
  postgresql:
    version: "12"
```
And I'm getting the following error when I try to apply the manifests:

`error: unable to recognize "STDIN": no matches for kind "postgresql" in version "acid.zalan.do/v1"
`

Not really sure where to go from here -- I haven't been able to turn up anything on this with my searches.
