### ISSUE TITLE
Multi Kubernetes Cluster

### ISSUE THREAD

**Issue by yaroslavkasatikov** [zalando/postgres-operator#989]
Hello team,

I'm starting to explore your postgres-operator and have the first question about Multi Kubernetes Cluster.

Is it possible to have two (or more) Postgres cluster in different Kubernetes Clusters which are synced each other?  
There are two scenariois:
1) Disaster Recovery. Active PG  cluster is  in one K8S cluster and standby is in another. In case of active is broken, we promote standby to active (manually or automatic)
2) H/A. Both cluster are replicated between each other and clients work with both cluster at the same time

Thanks a lot!

**Comment by CyberDem0n** [comment]
The [standby cluster](https://github.com/zalando/postgres-operator/blob/master/docs/user.md#setting-up-a-standby-cluster) feature is probably what you are looking for.

**Comment by Jan-M** [comment]
1) Using standby cluster, you should have a look into how Postgres works and how basebackup plus WAL shipping/archiving can help you to setup a second region.

2) Given how Postgres works, there is only a single master Pod, so replicated between each other does not exist.

**Comment by caniko** [comment]
But the standby cluster is read-only. How about sharding or partitioning so that we can have a master in every cluster?

**Comment by strowi** [comment]
Came here to ask about sharding too. (Had some fun with chatgpt, and it told me sharding was supported here. Even showed me an example, but can't find anything related in this repository..) 

```yaml
apiVersion: acid.zalan.do/v1
kind: PostgreSQL
metadata:
  name: my-sharded-database
spec:
  replicas: 3
  shards: 2
  serviceType: ClusterIP
  shardName: my-shard
  database: mydb
  username: myuser
  password: mypass
  pgBouncer: false
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
  initdbScripts:
  - /opt/initdb/init.sql
```
